-- ---------------------------------------------------------------------------------------------
-- Metadata seed delta: point the four AI-authoring prompts at Gemini 3.6 Flash.
--
-- WHY THIS MODEL. It is the newest Gemini this instance carries. "Gemini 3.7" does not exist in
-- MJ's model metadata — the Gemini LLMs available are 3, 3.1, 3.5 and 3.6, and 3.6 Flash is the
-- highest of them. It is vendored by Google through the same `GeminiLLM` driver the previous pin
-- used, so nothing about how the call is made changes.
--
-- IT IS A FLASH TIER, and that is a deliberate accepted trade. The stages this drives are the ones
-- that gate how quickly an author sees a form, so speed is the thing being bought; the cost is
-- somewhat weaker judgement on question wording and conditional logic than the Pro tier gave.
-- Reverting is a metadata operation on the `MJ: AI Prompt Models` rows below and needs no deploy —
-- which is the whole reason model selection was kept out of code.
--
-- WHAT IT DOES NOT TOUCH. 'Forms: Response Analyzer' stays on Gemini 3.1 Pro. It is the on-submit
-- answer scorer, not an authoring prompt, and re-tiering a neighbouring feature nobody asked about
-- is how an unrelated behaviour changes without anyone noticing.
--
-- Generated the same way as its predecessors: pushed against MJ_Install_Rehearsal, restored from a
-- pre-feature backup and brought to head through the SHIPPED CHAIN, 0 Form rows throughout. Every
-- `${flyway:defaultSchema}` became `${mjSchema}` — all calls here are CORE procedures. No
-- Forms-schema SP calls and no Form Respondent permission records, so #41's watershed is untouched.
-- ---------------------------------------------------------------------------------------------

-- SQL Logging Session
-- Session ID: 2c4f357a-fbc1-4fc3-806f-f0f685cb1017
-- Started: 2026-08-20T22:45:07.096Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: AI Prompt Models (core SP call only)
DECLARE @PromptID_40ccd759 UNIQUEIDENTIFIER,
@ModelID_40ccd759 UNIQUEIDENTIFIER,
@VendorID_40ccd759 UNIQUEIDENTIFIER,
@ConfigurationID_40ccd759 UNIQUEIDENTIFIER,
@Priority_40ccd759 INT,
@ExecutionGroup_40ccd759 INT,
@ModelParameters_40ccd759 NVARCHAR(MAX),
@Status_40ccd759 NVARCHAR(20),
@ParallelizationMode_40ccd759 NVARCHAR(20),
@ParallelCount_40ccd759 INT,
@ParallelConfigParam_40ccd759 NVARCHAR(100),
@EffortLevel_40ccd759 INT,
@ID_40ccd759 UNIQUEIDENTIFIER
SET
  @PromptID_40ccd759 = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829304'
SET
  @ModelID_40ccd759 = 'BD266132-109B-4701-86F8-52F90C8A9E3E'
SET
  @VendorID_40ccd759 = 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_40ccd759 = 100
SET
  @ExecutionGroup_40ccd759 = 0
SET
  @Status_40ccd759 = N'Active'
SET
  @ParallelizationMode_40ccd759 = N'None'
SET
  @ParallelCount_40ccd759 = 1
SET
  @ID_40ccd759 = '5A6B7C8D-9E0F-4A1B-2C3D-4E5F60718293' EXEC [${mjSchema}].spUpdateAIPromptModel @PromptID = @PromptID_40ccd759,
  @ModelID = @ModelID_40ccd759,
  @VendorID = @VendorID_40ccd759,
  @ConfigurationID = @ConfigurationID_40ccd759,
  @ConfigurationID_Clear = 1,
  @Priority = @Priority_40ccd759,
  @ExecutionGroup = @ExecutionGroup_40ccd759,
  @ModelParameters = @ModelParameters_40ccd759,
  @ModelParameters_Clear = 1,
  @Status = @Status_40ccd759,
  @ParallelizationMode = @ParallelizationMode_40ccd759,
  @ParallelCount = @ParallelCount_40ccd759,
  @ParallelConfigParam = @ParallelConfigParam_40ccd759,
  @ParallelConfigParam_Clear = 1,
  @EffortLevel = @EffortLevel_40ccd759,
  @EffortLevel_Clear = 1,
  @ID = @ID_40ccd759;

GO

-- Save MJ: AI Prompt Models (core SP call only)
DECLARE @PromptID_a22f9e8c UNIQUEIDENTIFIER,
@ModelID_a22f9e8c UNIQUEIDENTIFIER,
@VendorID_a22f9e8c UNIQUEIDENTIFIER,
@ConfigurationID_a22f9e8c UNIQUEIDENTIFIER,
@Priority_a22f9e8c INT,
@ExecutionGroup_a22f9e8c INT,
@ModelParameters_a22f9e8c NVARCHAR(MAX),
@Status_a22f9e8c NVARCHAR(20),
@ParallelizationMode_a22f9e8c NVARCHAR(20),
@ParallelCount_a22f9e8c INT,
@ParallelConfigParam_a22f9e8c NVARCHAR(100),
@EffortLevel_a22f9e8c INT,
@ID_a22f9e8c UNIQUEIDENTIFIER
SET
  @PromptID_a22f9e8c = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829305'
SET
  @ModelID_a22f9e8c = 'BD266132-109B-4701-86F8-52F90C8A9E3E'
SET
  @VendorID_a22f9e8c = 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_a22f9e8c = 100
SET
  @ExecutionGroup_a22f9e8c = 0
SET
  @Status_a22f9e8c = N'Active'
SET
  @ParallelizationMode_a22f9e8c = N'None'
SET
  @ParallelCount_a22f9e8c = 1
SET
  @ID_a22f9e8c = '5A6B7C8D-9E0F-4A1B-2C3D-4E5F60718294' EXEC [${mjSchema}].spUpdateAIPromptModel @PromptID = @PromptID_a22f9e8c,
  @ModelID = @ModelID_a22f9e8c,
  @VendorID = @VendorID_a22f9e8c,
  @ConfigurationID = @ConfigurationID_a22f9e8c,
  @ConfigurationID_Clear = 1,
  @Priority = @Priority_a22f9e8c,
  @ExecutionGroup = @ExecutionGroup_a22f9e8c,
  @ModelParameters = @ModelParameters_a22f9e8c,
  @ModelParameters_Clear = 1,
  @Status = @Status_a22f9e8c,
  @ParallelizationMode = @ParallelizationMode_a22f9e8c,
  @ParallelCount = @ParallelCount_a22f9e8c,
  @ParallelConfigParam = @ParallelConfigParam_a22f9e8c,
  @ParallelConfigParam_Clear = 1,
  @EffortLevel = @EffortLevel_a22f9e8c,
  @EffortLevel_Clear = 1,
  @ID = @ID_a22f9e8c;

GO

-- Save MJ: AI Prompt Models (core SP call only)
DECLARE @PromptID_90488a8e UNIQUEIDENTIFIER,
@ModelID_90488a8e UNIQUEIDENTIFIER,
@VendorID_90488a8e UNIQUEIDENTIFIER,
@ConfigurationID_90488a8e UNIQUEIDENTIFIER,
@Priority_90488a8e INT,
@ExecutionGroup_90488a8e INT,
@ModelParameters_90488a8e NVARCHAR(MAX),
@Status_90488a8e NVARCHAR(20),
@ParallelizationMode_90488a8e NVARCHAR(20),
@ParallelCount_90488a8e INT,
@ParallelConfigParam_90488a8e NVARCHAR(100),
@EffortLevel_90488a8e INT,
@ID_90488a8e UNIQUEIDENTIFIER
SET
  @PromptID_90488a8e = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829306'
SET
  @ModelID_90488a8e = 'BD266132-109B-4701-86F8-52F90C8A9E3E'
SET
  @VendorID_90488a8e = 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_90488a8e = 100
SET
  @ExecutionGroup_90488a8e = 0
SET
  @Status_90488a8e = N'Active'
SET
  @ParallelizationMode_90488a8e = N'None'
SET
  @ParallelCount_90488a8e = 1
SET
  @ID_90488a8e = '5A6B7C8D-9E0F-4A1B-2C3D-4E5F60718295' EXEC [${mjSchema}].spUpdateAIPromptModel @PromptID = @PromptID_90488a8e,
  @ModelID = @ModelID_90488a8e,
  @VendorID = @VendorID_90488a8e,
  @ConfigurationID = @ConfigurationID_90488a8e,
  @ConfigurationID_Clear = 1,
  @Priority = @Priority_90488a8e,
  @ExecutionGroup = @ExecutionGroup_90488a8e,
  @ModelParameters = @ModelParameters_90488a8e,
  @ModelParameters_Clear = 1,
  @Status = @Status_90488a8e,
  @ParallelizationMode = @ParallelizationMode_90488a8e,
  @ParallelCount = @ParallelCount_90488a8e,
  @ParallelConfigParam = @ParallelConfigParam_90488a8e,
  @ParallelConfigParam_Clear = 1,
  @EffortLevel = @EffortLevel_90488a8e,
  @EffortLevel_Clear = 1,
  @ID = @ID_90488a8e;

GO

-- Save MJ: AI Prompt Models (core SP call only)
DECLARE @PromptID_d03e88ed UNIQUEIDENTIFIER,
@ModelID_d03e88ed UNIQUEIDENTIFIER,
@VendorID_d03e88ed UNIQUEIDENTIFIER,
@ConfigurationID_d03e88ed UNIQUEIDENTIFIER,
@Priority_d03e88ed INT,
@ExecutionGroup_d03e88ed INT,
@ModelParameters_d03e88ed NVARCHAR(MAX),
@Status_d03e88ed NVARCHAR(20),
@ParallelizationMode_d03e88ed NVARCHAR(20),
@ParallelCount_d03e88ed INT,
@ParallelConfigParam_d03e88ed NVARCHAR(100),
@EffortLevel_d03e88ed INT,
@ID_d03e88ed UNIQUEIDENTIFIER
SET
  @PromptID_d03e88ed = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829307'
SET
  @ModelID_d03e88ed = 'BD266132-109B-4701-86F8-52F90C8A9E3E'
SET
  @VendorID_d03e88ed = 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_d03e88ed = 100
SET
  @ExecutionGroup_d03e88ed = 0
SET
  @Status_d03e88ed = N'Active'
SET
  @ParallelizationMode_d03e88ed = N'None'
SET
  @ParallelCount_d03e88ed = 1
SET
  @ID_d03e88ed = '5A6B7C8D-9E0F-4A1B-2C3D-4E5F60718296' EXEC [${mjSchema}].spUpdateAIPromptModel @PromptID = @PromptID_d03e88ed,
  @ModelID = @ModelID_d03e88ed,
  @VendorID = @VendorID_d03e88ed,
  @ConfigurationID = @ConfigurationID_d03e88ed,
  @ConfigurationID_Clear = 1,
  @Priority = @Priority_d03e88ed,
  @ExecutionGroup = @ExecutionGroup_d03e88ed,
  @ModelParameters = @ModelParameters_d03e88ed,
  @ModelParameters_Clear = 1,
  @Status = @Status_d03e88ed,
  @ParallelizationMode = @ParallelizationMode_d03e88ed,
  @ParallelCount = @ParallelCount_d03e88ed,
  @ParallelConfigParam = @ParallelConfigParam_d03e88ed,
  @ParallelConfigParam_Clear = 1,
  @EffortLevel = @EffortLevel_d03e88ed,
  @EffortLevel_Clear = 1,
  @ID = @ID_d03e88ed;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_7a547db9 UNIQUEIDENTIFIER,
@EntityID_7a547db9 UNIQUEIDENTIFIER,
@Name_7a547db9 NVARCHAR(100),
@Description_7a547db9 NVARCHAR(MAX),
@CategoryID_7a547db9 UNIQUEIDENTIFIER,
@IsShared_7a547db9 BIT,
@IsDefault_7a547db9 BIT,
@GridState_7a547db9 NVARCHAR(MAX),
@FilterState_7a547db9 NVARCHAR(MAX),
@CustomFilterState_7a547db9 BIT,
@SmartFilterEnabled_7a547db9 BIT,
@SmartFilterPrompt_7a547db9 NVARCHAR(MAX),
@SmartFilterWhereClause_7a547db9 NVARCHAR(MAX),
@SmartFilterExplanation_7a547db9 NVARCHAR(MAX),
@WhereClause_7a547db9 NVARCHAR(MAX),
@CustomWhereClause_7a547db9 BIT,
@SortState_7a547db9 NVARCHAR(MAX),
@Thumbnail_7a547db9 NVARCHAR(MAX),
@CardState_7a547db9 NVARCHAR(MAX),
@DisplayState_7a547db9 NVARCHAR(MAX),
@ViewTypeID_7a547db9 UNIQUEIDENTIFIER,
@ID_7a547db9 UNIQUEIDENTIFIER
SET
  @UserID_7a547db9 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_7a547db9 = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_7a547db9 = N'All Forms'
SET
  @Description_7a547db9 = N''
SET
  @IsShared_7a547db9 = 1
SET
  @IsDefault_7a547db9 = 0
SET
  @GridState_7a547db9 = N'{}'
SET
  @FilterState_7a547db9 = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_7a547db9 = 0
SET
  @SmartFilterEnabled_7a547db9 = 0
SET
  @WhereClause_7a547db9 = N''
SET
  @CustomWhereClause_7a547db9 = 0
SET
  @ID_7a547db9 = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_7a547db9,
  @EntityID = @EntityID_7a547db9,
  @Name = @Name_7a547db9,
  @Description = @Description_7a547db9,
  @CategoryID = @CategoryID_7a547db9,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_7a547db9,
  @IsDefault = @IsDefault_7a547db9,
  @GridState = @GridState_7a547db9,
  @FilterState = @FilterState_7a547db9,
  @CustomFilterState = @CustomFilterState_7a547db9,
  @SmartFilterEnabled = @SmartFilterEnabled_7a547db9,
  @SmartFilterPrompt = @SmartFilterPrompt_7a547db9,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_7a547db9,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_7a547db9,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_7a547db9,
  @CustomWhereClause = @CustomWhereClause_7a547db9,
  @SortState = @SortState_7a547db9,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_7a547db9,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_7a547db9,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_7a547db9,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_7a547db9,
  @ViewTypeID_Clear = 1,
  @ID = @ID_7a547db9;

GO


-- End of SQL Logging Session
-- Session ID: 2c4f357a-fbc1-4fc3-806f-f0f685cb1017
-- Completed: 2026-08-20T22:45:12.983Z
-- Duration: 5887ms
-- Total Statements: 5
