-- ---------------------------------------------------------------------------------------------
-- Metadata seed delta: make the AI-authoring prompts' OutputExamples say which fields are optional.
--
-- THE DEFECT THIS FIXES, which only a real run could find.
--   `AIPromptRunner` validates a model's output against the prompt's `OutputExample`, and it treats
--   EVERY key there as REQUIRED unless the key name ends in '?'. Our examples showed optional fields
--   — confirmationMessage, renderMode, screens, screens.welcome, imagePrompt, buttonLabel — without
--   that marker, so `ValidationBehavior='Strict'` rejected perfectly valid output and burned all
--   three retries on EVERY generation.
--
--   It did not fail loudly: the runner returns the last attempt once retries are exhausted, so a
--   form still came out. What it cost was three model calls where one was needed, on both the
--   single-shot Designer and the staged Outline — an 82-second build that should take under thirty,
--   and triple the token spend, on every form anybody generates.
--
--   Unit tests cannot see this: it lives entirely in the interaction between metadata on a host
--   database and MJ's runner. It surfaced the first time the pipeline was pointed at a real model.
--
-- WHAT THIS CARRIES
--   * Four `MJ: AI Prompts` OutputExample updates — Form Designer, Form Outline, Page Detail and
--     Theme Designer — with '?' on every field the zod schema treats as optional.
--   * Template-param and user-view rows MetadataSync rewrote alongside them. No behaviour change;
--     they are descriptions and bookkeeping the previous seed wrote from an older metadata/ state.
--
-- A SECOND DELTA RATHER THAN AN EDIT to V202608211700, per migrations/README.md: seeds are
-- append-only history, and that file is already applied on databases here. The exception the README
-- grants is for a migration that CANNOT APPLY AT ALL, which is not this.
--
-- HOW IT WAS GENERATED
--   Pushed against MJ_Install_Rehearsal, restored from a pre-feature backup and brought back to head
--   through the SHIPPED CHAIN (core `npx mj migrate -t v6.1.0-edge.2`, then `npm run mj:migrate`),
--   so the delta diffs against what a fresh install actually has and not against dev work. 0 Form
--   rows throughout. All 27 `${flyway:defaultSchema}` placeholders became `${mjSchema}` — every call
--   here is a CORE procedure. No Forms-schema SP calls and no Form Respondent permission records, so
--   the #41 watershed is untouched.
-- ---------------------------------------------------------------------------------------------

-- SQL Logging Session
-- Session ID: 5d684731-bd70-4c6b-8b81-08916283b185
-- Started: 2026-08-20T20:59:29.383Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_5afd7ad7 UNIQUEIDENTIFIER,
@Name_5afd7ad7 NVARCHAR(255),
@Description_5afd7ad7 NVARCHAR(MAX),
@Type_5afd7ad7 NVARCHAR(20),
@DefaultValue_5afd7ad7 NVARCHAR(MAX),
@IsRequired_5afd7ad7 BIT,
@LinkedParameterName_5afd7ad7 NVARCHAR(255),
@LinkedParameterField_5afd7ad7 NVARCHAR(500),
@ExtraFilter_5afd7ad7 NVARCHAR(MAX),
@EntityID_5afd7ad7 UNIQUEIDENTIFIER,
@RecordID_5afd7ad7 NVARCHAR(2000),
@OrderBy_5afd7ad7 NVARCHAR(MAX),
@TemplateContentID_5afd7ad7 UNIQUEIDENTIFIER,
@ID_5afd7ad7 UNIQUEIDENTIFIER
SET
  @TemplateID_5afd7ad7 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_5afd7ad7 = N'InputMode'
SET
  @Description_5afd7ad7 = N'Optional: ''brief'' (default) when Brief describes the form to build, or ''questions'' when it is a list of questions the author already wrote and whose wording must be preserved verbatim.'
SET
  @Type_5afd7ad7 = N'Scalar'
SET
  @IsRequired_5afd7ad7 = 0
SET
  @ID_5afd7ad7 = '4F5A6B7C-8D9E-4F0A-8B2C-3D4E5F607182' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_5afd7ad7,
  @Name = @Name_5afd7ad7,
  @Description = @Description_5afd7ad7,
  @Type = @Type_5afd7ad7,
  @DefaultValue = @DefaultValue_5afd7ad7,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_5afd7ad7,
  @LinkedParameterName = @LinkedParameterName_5afd7ad7,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_5afd7ad7,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_5afd7ad7,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_5afd7ad7,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_5afd7ad7,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_5afd7ad7,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_5afd7ad7,
  @TemplateContentID_Clear = 1,
  @ID = @ID_5afd7ad7;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_e68e20a3 UNIQUEIDENTIFIER,
@Name_e68e20a3 NVARCHAR(255),
@Description_e68e20a3 NVARCHAR(MAX),
@Type_e68e20a3 NVARCHAR(20),
@DefaultValue_e68e20a3 NVARCHAR(MAX),
@IsRequired_e68e20a3 BIT,
@LinkedParameterName_e68e20a3 NVARCHAR(255),
@LinkedParameterField_e68e20a3 NVARCHAR(500),
@ExtraFilter_e68e20a3 NVARCHAR(MAX),
@EntityID_e68e20a3 UNIQUEIDENTIFIER,
@RecordID_e68e20a3 NVARCHAR(2000),
@OrderBy_e68e20a3 NVARCHAR(MAX),
@TemplateContentID_e68e20a3 UNIQUEIDENTIFIER,
@ID_e68e20a3 UNIQUEIDENTIFIER
SET
  @TemplateID_e68e20a3 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_e68e20a3 = N'ValidationError'
SET
  @Description_e68e20a3 = N'Optional: the blueprint validation error from the prior attempt, fed back on a retry.'
SET
  @Type_e68e20a3 = N'Scalar'
SET
  @IsRequired_e68e20a3 = 0
SET
  @ID_e68e20a3 = '3E4F5A6B-7C8D-4E9F-0A1B-2C3D4E5F6071' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_e68e20a3,
  @Name = @Name_e68e20a3,
  @Description = @Description_e68e20a3,
  @Type = @Type_e68e20a3,
  @DefaultValue = @DefaultValue_e68e20a3,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_e68e20a3,
  @LinkedParameterName = @LinkedParameterName_e68e20a3,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_e68e20a3,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_e68e20a3,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_e68e20a3,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_e68e20a3,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_e68e20a3,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_e68e20a3,
  @TemplateContentID_Clear = 1,
  @ID = @ID_e68e20a3;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_60fbbe27 UNIQUEIDENTIFIER,
@Name_60fbbe27 NVARCHAR(255),
@Description_60fbbe27 NVARCHAR(MAX),
@Type_60fbbe27 NVARCHAR(20),
@DefaultValue_60fbbe27 NVARCHAR(MAX),
@IsRequired_60fbbe27 BIT,
@LinkedParameterName_60fbbe27 NVARCHAR(255),
@LinkedParameterField_60fbbe27 NVARCHAR(500),
@ExtraFilter_60fbbe27 NVARCHAR(MAX),
@EntityID_60fbbe27 UNIQUEIDENTIFIER,
@RecordID_60fbbe27 NVARCHAR(2000),
@OrderBy_60fbbe27 NVARCHAR(MAX),
@TemplateContentID_60fbbe27 UNIQUEIDENTIFIER,
@ID_60fbbe27 UNIQUEIDENTIFIER
SET
  @TemplateID_60fbbe27 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_60fbbe27 = N'Brief'
SET
  @Description_60fbbe27 = N'The natural-language description of the form to design.'
SET
  @Type_60fbbe27 = N'Scalar'
SET
  @IsRequired_60fbbe27 = 1
SET
  @ID_60fbbe27 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E5F' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_60fbbe27,
  @Name = @Name_60fbbe27,
  @Description = @Description_60fbbe27,
  @Type = @Type_60fbbe27,
  @DefaultValue = @DefaultValue_60fbbe27,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_60fbbe27,
  @LinkedParameterName = @LinkedParameterName_60fbbe27,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_60fbbe27,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_60fbbe27,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_60fbbe27,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_60fbbe27,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_60fbbe27,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_60fbbe27,
  @TemplateContentID_Clear = 1,
  @ID = @ID_60fbbe27;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_bdedcd85 UNIQUEIDENTIFIER,
@Name_bdedcd85 NVARCHAR(255),
@Description_bdedcd85 NVARCHAR(MAX),
@Type_bdedcd85 NVARCHAR(20),
@DefaultValue_bdedcd85 NVARCHAR(MAX),
@IsRequired_bdedcd85 BIT,
@LinkedParameterName_bdedcd85 NVARCHAR(255),
@LinkedParameterField_bdedcd85 NVARCHAR(500),
@ExtraFilter_bdedcd85 NVARCHAR(MAX),
@EntityID_bdedcd85 UNIQUEIDENTIFIER,
@RecordID_bdedcd85 NVARCHAR(2000),
@OrderBy_bdedcd85 NVARCHAR(MAX),
@TemplateContentID_bdedcd85 UNIQUEIDENTIFIER,
@ID_bdedcd85 UNIQUEIDENTIFIER
SET
  @TemplateID_bdedcd85 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_bdedcd85 = N'PreviousAttempt'
SET
  @Description_bdedcd85 = N'Optional: the model''s prior invalid output, fed back on a retry attempt.'
SET
  @Type_bdedcd85 = N'Scalar'
SET
  @IsRequired_bdedcd85 = 0
SET
  @ID_bdedcd85 = '2D3E4F5A-6B7C-4D8E-9F0A-1B2C3D4E5F60' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_bdedcd85,
  @Name = @Name_bdedcd85,
  @Description = @Description_bdedcd85,
  @Type = @Type_bdedcd85,
  @DefaultValue = @DefaultValue_bdedcd85,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_bdedcd85,
  @LinkedParameterName = @LinkedParameterName_bdedcd85,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_bdedcd85,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_bdedcd85,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_bdedcd85,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_bdedcd85,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_bdedcd85,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_bdedcd85,
  @TemplateContentID_Clear = 1,
  @ID = @ID_bdedcd85;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_671598d1 UNIQUEIDENTIFIER,
@Name_671598d1 NVARCHAR(255),
@Description_671598d1 NVARCHAR(MAX),
@Type_671598d1 NVARCHAR(20),
@DefaultValue_671598d1 NVARCHAR(MAX),
@IsRequired_671598d1 BIT,
@LinkedParameterName_671598d1 NVARCHAR(255),
@LinkedParameterField_671598d1 NVARCHAR(500),
@ExtraFilter_671598d1 NVARCHAR(MAX),
@EntityID_671598d1 UNIQUEIDENTIFIER,
@RecordID_671598d1 NVARCHAR(2000),
@OrderBy_671598d1 NVARCHAR(MAX),
@TemplateContentID_671598d1 UNIQUEIDENTIFIER,
@ID_671598d1 UNIQUEIDENTIFIER
SET
  @TemplateID_671598d1 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F62'
SET
  @Name_671598d1 = N'Brief'
SET
  @Description_671598d1 = N'The natural-language description of the form, or the author''s own list of questions.'
SET
  @Type_671598d1 = N'Scalar'
SET
  @IsRequired_671598d1 = 1
SET
  @ID_671598d1 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E60' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_671598d1,
  @Name = @Name_671598d1,
  @Description = @Description_671598d1,
  @Type = @Type_671598d1,
  @DefaultValue = @DefaultValue_671598d1,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_671598d1,
  @LinkedParameterName = @LinkedParameterName_671598d1,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_671598d1,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_671598d1,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_671598d1,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_671598d1,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_671598d1,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_671598d1,
  @TemplateContentID_Clear = 1,
  @ID = @ID_671598d1;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_711c7732 UNIQUEIDENTIFIER,
@Name_711c7732 NVARCHAR(255),
@Description_711c7732 NVARCHAR(MAX),
@Type_711c7732 NVARCHAR(20),
@DefaultValue_711c7732 NVARCHAR(MAX),
@IsRequired_711c7732 BIT,
@LinkedParameterName_711c7732 NVARCHAR(255),
@LinkedParameterField_711c7732 NVARCHAR(500),
@ExtraFilter_711c7732 NVARCHAR(MAX),
@EntityID_711c7732 UNIQUEIDENTIFIER,
@RecordID_711c7732 NVARCHAR(2000),
@OrderBy_711c7732 NVARCHAR(MAX),
@TemplateContentID_711c7732 UNIQUEIDENTIFIER,
@ID_711c7732 UNIQUEIDENTIFIER
SET
  @TemplateID_711c7732 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F62'
SET
  @Name_711c7732 = N'InputMode'
SET
  @Description_711c7732 = N'Optional: ''brief'' (default) or ''questions'' when Brief is a list the author wrote and whose wording must be preserved verbatim.'
SET
  @Type_711c7732 = N'Scalar'
SET
  @IsRequired_711c7732 = 0
SET
  @ID_711c7732 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E61' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_711c7732,
  @Name = @Name_711c7732,
  @Description = @Description_711c7732,
  @Type = @Type_711c7732,
  @DefaultValue = @DefaultValue_711c7732,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_711c7732,
  @LinkedParameterName = @LinkedParameterName_711c7732,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_711c7732,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_711c7732,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_711c7732,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_711c7732,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_711c7732,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_711c7732,
  @TemplateContentID_Clear = 1,
  @ID = @ID_711c7732;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_31bff583 UNIQUEIDENTIFIER,
@Name_31bff583 NVARCHAR(255),
@Description_31bff583 NVARCHAR(MAX),
@Type_31bff583 NVARCHAR(20),
@DefaultValue_31bff583 NVARCHAR(MAX),
@IsRequired_31bff583 BIT,
@LinkedParameterName_31bff583 NVARCHAR(255),
@LinkedParameterField_31bff583 NVARCHAR(500),
@ExtraFilter_31bff583 NVARCHAR(MAX),
@EntityID_31bff583 UNIQUEIDENTIFIER,
@RecordID_31bff583 NVARCHAR(2000),
@OrderBy_31bff583 NVARCHAR(MAX),
@TemplateContentID_31bff583 UNIQUEIDENTIFIER,
@ID_31bff583 UNIQUEIDENTIFIER
SET
  @TemplateID_31bff583 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F62'
SET
  @Name_31bff583 = N'PreviousAttempt'
SET
  @Description_31bff583 = N'Optional: the model''s prior invalid output, fed back on a retry attempt.'
SET
  @Type_31bff583 = N'Scalar'
SET
  @IsRequired_31bff583 = 0
SET
  @ID_31bff583 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E62' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_31bff583,
  @Name = @Name_31bff583,
  @Description = @Description_31bff583,
  @Type = @Type_31bff583,
  @DefaultValue = @DefaultValue_31bff583,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_31bff583,
  @LinkedParameterName = @LinkedParameterName_31bff583,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_31bff583,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_31bff583,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_31bff583,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_31bff583,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_31bff583,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_31bff583,
  @TemplateContentID_Clear = 1,
  @ID = @ID_31bff583;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_088ccdc8 UNIQUEIDENTIFIER,
@Name_088ccdc8 NVARCHAR(255),
@Description_088ccdc8 NVARCHAR(MAX),
@Type_088ccdc8 NVARCHAR(20),
@DefaultValue_088ccdc8 NVARCHAR(MAX),
@IsRequired_088ccdc8 BIT,
@LinkedParameterName_088ccdc8 NVARCHAR(255),
@LinkedParameterField_088ccdc8 NVARCHAR(500),
@ExtraFilter_088ccdc8 NVARCHAR(MAX),
@EntityID_088ccdc8 UNIQUEIDENTIFIER,
@RecordID_088ccdc8 NVARCHAR(2000),
@OrderBy_088ccdc8 NVARCHAR(MAX),
@TemplateContentID_088ccdc8 UNIQUEIDENTIFIER,
@ID_088ccdc8 UNIQUEIDENTIFIER
SET
  @TemplateID_088ccdc8 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F62'
SET
  @Name_088ccdc8 = N'ValidationError'
SET
  @Description_088ccdc8 = N'Optional: the validation error from the prior attempt, fed back on a retry.'
SET
  @Type_088ccdc8 = N'Scalar'
SET
  @IsRequired_088ccdc8 = 0
SET
  @ID_088ccdc8 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E63' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_088ccdc8,
  @Name = @Name_088ccdc8,
  @Description = @Description_088ccdc8,
  @Type = @Type_088ccdc8,
  @DefaultValue = @DefaultValue_088ccdc8,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_088ccdc8,
  @LinkedParameterName = @LinkedParameterName_088ccdc8,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_088ccdc8,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_088ccdc8,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_088ccdc8,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_088ccdc8,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_088ccdc8,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_088ccdc8,
  @TemplateContentID_Clear = 1,
  @ID = @ID_088ccdc8;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_ead63969 UNIQUEIDENTIFIER,
@Name_ead63969 NVARCHAR(255),
@Description_ead63969 NVARCHAR(MAX),
@Type_ead63969 NVARCHAR(20),
@DefaultValue_ead63969 NVARCHAR(MAX),
@IsRequired_ead63969 BIT,
@LinkedParameterName_ead63969 NVARCHAR(255),
@LinkedParameterField_ead63969 NVARCHAR(500),
@ExtraFilter_ead63969 NVARCHAR(MAX),
@EntityID_ead63969 UNIQUEIDENTIFIER,
@RecordID_ead63969 NVARCHAR(2000),
@OrderBy_ead63969 NVARCHAR(MAX),
@TemplateContentID_ead63969 UNIQUEIDENTIFIER,
@ID_ead63969 UNIQUEIDENTIFIER
SET
  @TemplateID_ead63969 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_ead63969 = N'Brief'
SET
  @Description_ead63969 = N'The original natural-language request, so the page is written for the form the author asked for.'
SET
  @Type_ead63969 = N'Scalar'
SET
  @IsRequired_ead63969 = 1
SET
  @ID_ead63969 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E70' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_ead63969,
  @Name = @Name_ead63969,
  @Description = @Description_ead63969,
  @Type = @Type_ead63969,
  @DefaultValue = @DefaultValue_ead63969,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_ead63969,
  @LinkedParameterName = @LinkedParameterName_ead63969,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_ead63969,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_ead63969,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_ead63969,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_ead63969,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_ead63969,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_ead63969,
  @TemplateContentID_Clear = 1,
  @ID = @ID_ead63969;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_670bfd9b UNIQUEIDENTIFIER,
@Name_670bfd9b NVARCHAR(255),
@Description_670bfd9b NVARCHAR(MAX),
@Type_670bfd9b NVARCHAR(20),
@DefaultValue_670bfd9b NVARCHAR(MAX),
@IsRequired_670bfd9b BIT,
@LinkedParameterName_670bfd9b NVARCHAR(255),
@LinkedParameterField_670bfd9b NVARCHAR(500),
@ExtraFilter_670bfd9b NVARCHAR(MAX),
@EntityID_670bfd9b UNIQUEIDENTIFIER,
@RecordID_670bfd9b NVARCHAR(2000),
@OrderBy_670bfd9b NVARCHAR(MAX),
@TemplateContentID_670bfd9b UNIQUEIDENTIFIER,
@ID_670bfd9b UNIQUEIDENTIFIER
SET
  @TemplateID_670bfd9b = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_670bfd9b = N'InputMode'
SET
  @Description_670bfd9b = N'Optional: ''brief'' (default) or ''questions'' when the author''s own wording must be preserved verbatim.'
SET
  @Type_670bfd9b = N'Scalar'
SET
  @IsRequired_670bfd9b = 0
SET
  @ID_670bfd9b = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E71' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_670bfd9b,
  @Name = @Name_670bfd9b,
  @Description = @Description_670bfd9b,
  @Type = @Type_670bfd9b,
  @DefaultValue = @DefaultValue_670bfd9b,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_670bfd9b,
  @LinkedParameterName = @LinkedParameterName_670bfd9b,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_670bfd9b,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_670bfd9b,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_670bfd9b,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_670bfd9b,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_670bfd9b,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_670bfd9b,
  @TemplateContentID_Clear = 1,
  @ID = @ID_670bfd9b;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_aa889c6a UNIQUEIDENTIFIER,
@Name_aa889c6a NVARCHAR(255),
@Description_aa889c6a NVARCHAR(MAX),
@Type_aa889c6a NVARCHAR(20),
@DefaultValue_aa889c6a NVARCHAR(MAX),
@IsRequired_aa889c6a BIT,
@LinkedParameterName_aa889c6a NVARCHAR(255),
@LinkedParameterField_aa889c6a NVARCHAR(500),
@ExtraFilter_aa889c6a NVARCHAR(MAX),
@EntityID_aa889c6a UNIQUEIDENTIFIER,
@RecordID_aa889c6a NVARCHAR(2000),
@OrderBy_aa889c6a NVARCHAR(MAX),
@TemplateContentID_aa889c6a UNIQUEIDENTIFIER,
@ID_aa889c6a UNIQUEIDENTIFIER
SET
  @TemplateID_aa889c6a = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_aa889c6a = N'Outline'
SET
  @Description_aa889c6a = N'The whole outline as JSON, so this page does not repeat or contradict another page.'
SET
  @Type_aa889c6a = N'Scalar'
SET
  @IsRequired_aa889c6a = 1
SET
  @ID_aa889c6a = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E72' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_aa889c6a,
  @Name = @Name_aa889c6a,
  @Description = @Description_aa889c6a,
  @Type = @Type_aa889c6a,
  @DefaultValue = @DefaultValue_aa889c6a,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_aa889c6a,
  @LinkedParameterName = @LinkedParameterName_aa889c6a,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_aa889c6a,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_aa889c6a,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_aa889c6a,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_aa889c6a,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_aa889c6a,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_aa889c6a,
  @TemplateContentID_Clear = 1,
  @ID = @ID_aa889c6a;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_c1569704 UNIQUEIDENTIFIER,
@Name_c1569704 NVARCHAR(255),
@Description_c1569704 NVARCHAR(MAX),
@Type_c1569704 NVARCHAR(20),
@DefaultValue_c1569704 NVARCHAR(MAX),
@IsRequired_c1569704 BIT,
@LinkedParameterName_c1569704 NVARCHAR(255),
@LinkedParameterField_c1569704 NVARCHAR(500),
@ExtraFilter_c1569704 NVARCHAR(MAX),
@EntityID_c1569704 UNIQUEIDENTIFIER,
@RecordID_c1569704 NVARCHAR(2000),
@OrderBy_c1569704 NVARCHAR(MAX),
@TemplateContentID_c1569704 UNIQUEIDENTIFIER,
@ID_c1569704 UNIQUEIDENTIFIER
SET
  @TemplateID_c1569704 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_c1569704 = N'PageIndex'
SET
  @Description_c1569704 = N'0-based index of the page being detailed, within the outline''s pages.'
SET
  @Type_c1569704 = N'Scalar'
SET
  @IsRequired_c1569704 = 1
SET
  @ID_c1569704 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E73' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_c1569704,
  @Name = @Name_c1569704,
  @Description = @Description_c1569704,
  @Type = @Type_c1569704,
  @DefaultValue = @DefaultValue_c1569704,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_c1569704,
  @LinkedParameterName = @LinkedParameterName_c1569704,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_c1569704,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_c1569704,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_c1569704,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_c1569704,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_c1569704,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_c1569704,
  @TemplateContentID_Clear = 1,
  @ID = @ID_c1569704;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_803980f4 UNIQUEIDENTIFIER,
@Name_803980f4 NVARCHAR(255),
@Description_803980f4 NVARCHAR(MAX),
@Type_803980f4 NVARCHAR(20),
@DefaultValue_803980f4 NVARCHAR(MAX),
@IsRequired_803980f4 BIT,
@LinkedParameterName_803980f4 NVARCHAR(255),
@LinkedParameterField_803980f4 NVARCHAR(500),
@ExtraFilter_803980f4 NVARCHAR(MAX),
@EntityID_803980f4 UNIQUEIDENTIFIER,
@RecordID_803980f4 NVARCHAR(2000),
@OrderBy_803980f4 NVARCHAR(MAX),
@TemplateContentID_803980f4 UNIQUEIDENTIFIER,
@ID_803980f4 UNIQUEIDENTIFIER
SET
  @TemplateID_803980f4 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_803980f4 = N'PageTitle'
SET
  @Description_803980f4 = N'Title of the page being detailed.'
SET
  @Type_803980f4 = N'Scalar'
SET
  @IsRequired_803980f4 = 0
SET
  @ID_803980f4 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E74' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_803980f4,
  @Name = @Name_803980f4,
  @Description = @Description_803980f4,
  @Type = @Type_803980f4,
  @DefaultValue = @DefaultValue_803980f4,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_803980f4,
  @LinkedParameterName = @LinkedParameterName_803980f4,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_803980f4,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_803980f4,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_803980f4,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_803980f4,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_803980f4,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_803980f4,
  @TemplateContentID_Clear = 1,
  @ID = @ID_803980f4;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_9f2c8bfe UNIQUEIDENTIFIER,
@Name_9f2c8bfe NVARCHAR(255),
@Description_9f2c8bfe NVARCHAR(MAX),
@Type_9f2c8bfe NVARCHAR(20),
@DefaultValue_9f2c8bfe NVARCHAR(MAX),
@IsRequired_9f2c8bfe BIT,
@LinkedParameterName_9f2c8bfe NVARCHAR(255),
@LinkedParameterField_9f2c8bfe NVARCHAR(500),
@ExtraFilter_9f2c8bfe NVARCHAR(MAX),
@EntityID_9f2c8bfe UNIQUEIDENTIFIER,
@RecordID_9f2c8bfe NVARCHAR(2000),
@OrderBy_9f2c8bfe NVARCHAR(MAX),
@TemplateContentID_9f2c8bfe UNIQUEIDENTIFIER,
@ID_9f2c8bfe UNIQUEIDENTIFIER
SET
  @TemplateID_9f2c8bfe = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_9f2c8bfe = N'PageStubs'
SET
  @Description_9f2c8bfe = N'That page''s sketched questions as JSON — matched back by position, so order matters.'
SET
  @Type_9f2c8bfe = N'Scalar'
SET
  @IsRequired_9f2c8bfe = 1
SET
  @ID_9f2c8bfe = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E75' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_9f2c8bfe,
  @Name = @Name_9f2c8bfe,
  @Description = @Description_9f2c8bfe,
  @Type = @Type_9f2c8bfe,
  @DefaultValue = @DefaultValue_9f2c8bfe,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_9f2c8bfe,
  @LinkedParameterName = @LinkedParameterName_9f2c8bfe,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_9f2c8bfe,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_9f2c8bfe,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_9f2c8bfe,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_9f2c8bfe,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_9f2c8bfe,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_9f2c8bfe,
  @TemplateContentID_Clear = 1,
  @ID = @ID_9f2c8bfe;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_c38bf5f8 UNIQUEIDENTIFIER,
@Name_c38bf5f8 NVARCHAR(255),
@Description_c38bf5f8 NVARCHAR(MAX),
@Type_c38bf5f8 NVARCHAR(20),
@DefaultValue_c38bf5f8 NVARCHAR(MAX),
@IsRequired_c38bf5f8 BIT,
@LinkedParameterName_c38bf5f8 NVARCHAR(255),
@LinkedParameterField_c38bf5f8 NVARCHAR(500),
@ExtraFilter_c38bf5f8 NVARCHAR(MAX),
@EntityID_c38bf5f8 UNIQUEIDENTIFIER,
@RecordID_c38bf5f8 NVARCHAR(2000),
@OrderBy_c38bf5f8 NVARCHAR(MAX),
@TemplateContentID_c38bf5f8 UNIQUEIDENTIFIER,
@ID_c38bf5f8 UNIQUEIDENTIFIER
SET
  @TemplateID_c38bf5f8 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_c38bf5f8 = N'PreviousAttempt'
SET
  @Description_c38bf5f8 = N'Optional: the model''s prior invalid output, fed back on a retry attempt.'
SET
  @Type_c38bf5f8 = N'Scalar'
SET
  @IsRequired_c38bf5f8 = 0
SET
  @ID_c38bf5f8 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E76' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_c38bf5f8,
  @Name = @Name_c38bf5f8,
  @Description = @Description_c38bf5f8,
  @Type = @Type_c38bf5f8,
  @DefaultValue = @DefaultValue_c38bf5f8,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_c38bf5f8,
  @LinkedParameterName = @LinkedParameterName_c38bf5f8,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_c38bf5f8,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_c38bf5f8,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_c38bf5f8,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_c38bf5f8,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_c38bf5f8,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_c38bf5f8,
  @TemplateContentID_Clear = 1,
  @ID = @ID_c38bf5f8;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_c4c51c34 UNIQUEIDENTIFIER,
@Name_c4c51c34 NVARCHAR(255),
@Description_c4c51c34 NVARCHAR(MAX),
@Type_c4c51c34 NVARCHAR(20),
@DefaultValue_c4c51c34 NVARCHAR(MAX),
@IsRequired_c4c51c34 BIT,
@LinkedParameterName_c4c51c34 NVARCHAR(255),
@LinkedParameterField_c4c51c34 NVARCHAR(500),
@ExtraFilter_c4c51c34 NVARCHAR(MAX),
@EntityID_c4c51c34 UNIQUEIDENTIFIER,
@RecordID_c4c51c34 NVARCHAR(2000),
@OrderBy_c4c51c34 NVARCHAR(MAX),
@TemplateContentID_c4c51c34 UNIQUEIDENTIFIER,
@ID_c4c51c34 UNIQUEIDENTIFIER
SET
  @TemplateID_c4c51c34 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @Name_c4c51c34 = N'ValidationError'
SET
  @Description_c4c51c34 = N'Optional: the validation error from the prior attempt, fed back on a retry.'
SET
  @Type_c4c51c34 = N'Scalar'
SET
  @IsRequired_c4c51c34 = 0
SET
  @ID_c4c51c34 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E77' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_c4c51c34,
  @Name = @Name_c4c51c34,
  @Description = @Description_c4c51c34,
  @Type = @Type_c4c51c34,
  @DefaultValue = @DefaultValue_c4c51c34,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_c4c51c34,
  @LinkedParameterName = @LinkedParameterName_c4c51c34,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_c4c51c34,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_c4c51c34,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_c4c51c34,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_c4c51c34,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_c4c51c34,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_c4c51c34,
  @TemplateContentID_Clear = 1,
  @ID = @ID_c4c51c34;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_dbc7c223 UNIQUEIDENTIFIER,
@Name_dbc7c223 NVARCHAR(255),
@Description_dbc7c223 NVARCHAR(MAX),
@Type_dbc7c223 NVARCHAR(20),
@DefaultValue_dbc7c223 NVARCHAR(MAX),
@IsRequired_dbc7c223 BIT,
@LinkedParameterName_dbc7c223 NVARCHAR(255),
@LinkedParameterField_dbc7c223 NVARCHAR(500),
@ExtraFilter_dbc7c223 NVARCHAR(MAX),
@EntityID_dbc7c223 UNIQUEIDENTIFIER,
@RecordID_dbc7c223 NVARCHAR(2000),
@OrderBy_dbc7c223 NVARCHAR(MAX),
@TemplateContentID_dbc7c223 UNIQUEIDENTIFIER,
@ID_dbc7c223 UNIQUEIDENTIFIER
SET
  @TemplateID_dbc7c223 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_dbc7c223 = N'Brief'
SET
  @Description_dbc7c223 = N'The original natural-language request, so the theme is about the form the author asked for.'
SET
  @Type_dbc7c223 = N'Scalar'
SET
  @IsRequired_dbc7c223 = 1
SET
  @ID_dbc7c223 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E80' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_dbc7c223,
  @Name = @Name_dbc7c223,
  @Description = @Description_dbc7c223,
  @Type = @Type_dbc7c223,
  @DefaultValue = @DefaultValue_dbc7c223,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_dbc7c223,
  @LinkedParameterName = @LinkedParameterName_dbc7c223,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_dbc7c223,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_dbc7c223,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_dbc7c223,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_dbc7c223,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_dbc7c223,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_dbc7c223,
  @TemplateContentID_Clear = 1,
  @ID = @ID_dbc7c223;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_775b54c6 UNIQUEIDENTIFIER,
@Name_775b54c6 NVARCHAR(255),
@Description_775b54c6 NVARCHAR(MAX),
@Type_775b54c6 NVARCHAR(20),
@DefaultValue_775b54c6 NVARCHAR(MAX),
@IsRequired_775b54c6 BIT,
@LinkedParameterName_775b54c6 NVARCHAR(255),
@LinkedParameterField_775b54c6 NVARCHAR(500),
@ExtraFilter_775b54c6 NVARCHAR(MAX),
@EntityID_775b54c6 UNIQUEIDENTIFIER,
@RecordID_775b54c6 NVARCHAR(2000),
@OrderBy_775b54c6 NVARCHAR(MAX),
@TemplateContentID_775b54c6 UNIQUEIDENTIFIER,
@ID_775b54c6 UNIQUEIDENTIFIER
SET
  @TemplateID_775b54c6 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_775b54c6 = N'FormName'
SET
  @Description_775b54c6 = N'The form''s name.'
SET
  @Type_775b54c6 = N'Scalar'
SET
  @IsRequired_775b54c6 = 1
SET
  @ID_775b54c6 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E81' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_775b54c6,
  @Name = @Name_775b54c6,
  @Description = @Description_775b54c6,
  @Type = @Type_775b54c6,
  @DefaultValue = @DefaultValue_775b54c6,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_775b54c6,
  @LinkedParameterName = @LinkedParameterName_775b54c6,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_775b54c6,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_775b54c6,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_775b54c6,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_775b54c6,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_775b54c6,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_775b54c6,
  @TemplateContentID_Clear = 1,
  @ID = @ID_775b54c6;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_91aa7178 UNIQUEIDENTIFIER,
@Name_91aa7178 NVARCHAR(255),
@Description_91aa7178 NVARCHAR(MAX),
@Type_91aa7178 NVARCHAR(20),
@DefaultValue_91aa7178 NVARCHAR(MAX),
@IsRequired_91aa7178 BIT,
@LinkedParameterName_91aa7178 NVARCHAR(255),
@LinkedParameterField_91aa7178 NVARCHAR(500),
@ExtraFilter_91aa7178 NVARCHAR(MAX),
@EntityID_91aa7178 UNIQUEIDENTIFIER,
@RecordID_91aa7178 NVARCHAR(2000),
@OrderBy_91aa7178 NVARCHAR(MAX),
@TemplateContentID_91aa7178 UNIQUEIDENTIFIER,
@ID_91aa7178 UNIQUEIDENTIFIER
SET
  @TemplateID_91aa7178 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_91aa7178 = N'BrandAdjectives'
SET
  @Description_91aa7178 = N'Comma-separated adjectives from the outline, e.g. ''warm, welcoming''. Blank when the outline offered none.'
SET
  @Type_91aa7178 = N'Scalar'
SET
  @IsRequired_91aa7178 = 0
SET
  @ID_91aa7178 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E82' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_91aa7178,
  @Name = @Name_91aa7178,
  @Description = @Description_91aa7178,
  @Type = @Type_91aa7178,
  @DefaultValue = @DefaultValue_91aa7178,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_91aa7178,
  @LinkedParameterName = @LinkedParameterName_91aa7178,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_91aa7178,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_91aa7178,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_91aa7178,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_91aa7178,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_91aa7178,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_91aa7178,
  @TemplateContentID_Clear = 1,
  @ID = @ID_91aa7178;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_37b60022 UNIQUEIDENTIFIER,
@Name_37b60022 NVARCHAR(255),
@Description_37b60022 NVARCHAR(MAX),
@Type_37b60022 NVARCHAR(20),
@DefaultValue_37b60022 NVARCHAR(MAX),
@IsRequired_37b60022 BIT,
@LinkedParameterName_37b60022 NVARCHAR(255),
@LinkedParameterField_37b60022 NVARCHAR(500),
@ExtraFilter_37b60022 NVARCHAR(MAX),
@EntityID_37b60022 UNIQUEIDENTIFIER,
@RecordID_37b60022 NVARCHAR(2000),
@OrderBy_37b60022 NVARCHAR(MAX),
@TemplateContentID_37b60022 UNIQUEIDENTIFIER,
@ID_37b60022 UNIQUEIDENTIFIER
SET
  @TemplateID_37b60022 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_37b60022 = N'Tokens'
SET
  @Description_37b60022 = N'The newline-separated --mjf-* token vocabulary, supplied by the code that owns it so the prompt and the validator cannot disagree about what is allowed.'
SET
  @Type_37b60022 = N'Scalar'
SET
  @IsRequired_37b60022 = 1
SET
  @ID_37b60022 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E83' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_37b60022,
  @Name = @Name_37b60022,
  @Description = @Description_37b60022,
  @Type = @Type_37b60022,
  @DefaultValue = @DefaultValue_37b60022,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_37b60022,
  @LinkedParameterName = @LinkedParameterName_37b60022,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_37b60022,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_37b60022,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_37b60022,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_37b60022,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_37b60022,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_37b60022,
  @TemplateContentID_Clear = 1,
  @ID = @ID_37b60022;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_42c2622b UNIQUEIDENTIFIER,
@Name_42c2622b NVARCHAR(255),
@Description_42c2622b NVARCHAR(MAX),
@Type_42c2622b NVARCHAR(20),
@DefaultValue_42c2622b NVARCHAR(MAX),
@IsRequired_42c2622b BIT,
@LinkedParameterName_42c2622b NVARCHAR(255),
@LinkedParameterField_42c2622b NVARCHAR(500),
@ExtraFilter_42c2622b NVARCHAR(MAX),
@EntityID_42c2622b UNIQUEIDENTIFIER,
@RecordID_42c2622b NVARCHAR(2000),
@OrderBy_42c2622b NVARCHAR(MAX),
@TemplateContentID_42c2622b UNIQUEIDENTIFIER,
@ID_42c2622b UNIQUEIDENTIFIER
SET
  @TemplateID_42c2622b = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_42c2622b = N'PreviousAttempt'
SET
  @Description_42c2622b = N'Optional: the model''s prior invalid output, fed back on a retry attempt.'
SET
  @Type_42c2622b = N'Scalar'
SET
  @IsRequired_42c2622b = 0
SET
  @ID_42c2622b = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E84' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_42c2622b,
  @Name = @Name_42c2622b,
  @Description = @Description_42c2622b,
  @Type = @Type_42c2622b,
  @DefaultValue = @DefaultValue_42c2622b,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_42c2622b,
  @LinkedParameterName = @LinkedParameterName_42c2622b,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_42c2622b,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_42c2622b,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_42c2622b,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_42c2622b,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_42c2622b,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_42c2622b,
  @TemplateContentID_Clear = 1,
  @ID = @ID_42c2622b;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_ca16c68f UNIQUEIDENTIFIER,
@Name_ca16c68f NVARCHAR(255),
@Description_ca16c68f NVARCHAR(MAX),
@Type_ca16c68f NVARCHAR(20),
@DefaultValue_ca16c68f NVARCHAR(MAX),
@IsRequired_ca16c68f BIT,
@LinkedParameterName_ca16c68f NVARCHAR(255),
@LinkedParameterField_ca16c68f NVARCHAR(500),
@ExtraFilter_ca16c68f NVARCHAR(MAX),
@EntityID_ca16c68f UNIQUEIDENTIFIER,
@RecordID_ca16c68f NVARCHAR(2000),
@OrderBy_ca16c68f NVARCHAR(MAX),
@TemplateContentID_ca16c68f UNIQUEIDENTIFIER,
@ID_ca16c68f UNIQUEIDENTIFIER
SET
  @TemplateID_ca16c68f = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @Name_ca16c68f = N'ValidationError'
SET
  @Description_ca16c68f = N'Optional: the validation error from the prior attempt, fed back on a retry.'
SET
  @Type_ca16c68f = N'Scalar'
SET
  @IsRequired_ca16c68f = 0
SET
  @ID_ca16c68f = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E85' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_ca16c68f,
  @Name = @Name_ca16c68f,
  @Description = @Description_ca16c68f,
  @Type = @Type_ca16c68f,
  @DefaultValue = @DefaultValue_ca16c68f,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_ca16c68f,
  @LinkedParameterName = @LinkedParameterName_ca16c68f,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_ca16c68f,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_ca16c68f,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_ca16c68f,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_ca16c68f,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_ca16c68f,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_ca16c68f,
  @TemplateContentID_Clear = 1,
  @ID = @ID_ca16c68f;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_ee9cc77c NVARCHAR(255),
@Description_ee9cc77c NVARCHAR(MAX),
@TemplateID_ee9cc77c UNIQUEIDENTIFIER,
@CategoryID_ee9cc77c UNIQUEIDENTIFIER,
@TypeID_ee9cc77c UNIQUEIDENTIFIER,
@Status_ee9cc77c NVARCHAR(50),
@ResponseFormat_ee9cc77c NVARCHAR(20),
@ModelSpecificResponseFormat_ee9cc77c NVARCHAR(MAX),
@AIModelTypeID_ee9cc77c UNIQUEIDENTIFIER,
@MinPowerRank_ee9cc77c INT,
@SelectionStrategy_ee9cc77c NVARCHAR(20),
@PowerPreference_ee9cc77c NVARCHAR(20),
@ParallelizationMode_ee9cc77c NVARCHAR(20),
@ParallelCount_ee9cc77c INT,
@ParallelConfigParam_ee9cc77c NVARCHAR(100),
@OutputType_ee9cc77c NVARCHAR(50),
@OutputExample_ee9cc77c NVARCHAR(MAX),
@ValidationBehavior_ee9cc77c NVARCHAR(50),
@MaxRetries_ee9cc77c INT,
@RetryDelayMS_ee9cc77c INT,
@RetryStrategy_ee9cc77c NVARCHAR(20),
@ResultSelectorPromptID_ee9cc77c UNIQUEIDENTIFIER,
@EnableCaching_ee9cc77c BIT,
@CacheTTLSeconds_ee9cc77c INT,
@CacheMatchType_ee9cc77c NVARCHAR(20),
@CacheSimilarityThreshold_ee9cc77c FLOAT(53),
@CacheMustMatchModel_ee9cc77c BIT,
@CacheMustMatchVendor_ee9cc77c BIT,
@CacheMustMatchAgent_ee9cc77c BIT,
@CacheMustMatchConfig_ee9cc77c BIT,
@PromptRole_ee9cc77c NVARCHAR(20),
@PromptPosition_ee9cc77c NVARCHAR(20),
@Temperature_ee9cc77c DECIMAL(3, 2),
@TopP_ee9cc77c DECIMAL(3, 2),
@TopK_ee9cc77c INT,
@MinP_ee9cc77c DECIMAL(3, 2),
@FrequencyPenalty_ee9cc77c DECIMAL(3, 2),
@PresencePenalty_ee9cc77c DECIMAL(3, 2),
@Seed_ee9cc77c INT,
@StopSequences_ee9cc77c NVARCHAR(1000),
@IncludeLogProbs_ee9cc77c BIT,
@TopLogProbs_ee9cc77c INT,
@FailoverStrategy_ee9cc77c NVARCHAR(50),
@FailoverMaxAttempts_ee9cc77c INT,
@FailoverDelaySeconds_ee9cc77c INT,
@FailoverModelStrategy_ee9cc77c NVARCHAR(50),
@FailoverErrorScope_ee9cc77c NVARCHAR(50),
@EffortLevel_ee9cc77c INT,
@AssistantPrefill_ee9cc77c NVARCHAR(MAX),
@PrefillFallbackMode_ee9cc77c NVARCHAR(20),
@RequireSpecificModels_ee9cc77c BIT,
@ID_ee9cc77c UNIQUEIDENTIFIER
SET
  @Name_ee9cc77c = N'Forms: Form Designer'
SET
  @Description_ee9cc77c = N'AI form-authoring Designer for the MJ Forms Open App. Turns a natural-language brief into a structured FormBlueprint JSON object (validated downstream against the Phase-1 §5.3 question taxonomy). The model/vendor is metadata-driven: SelectionStrategy=Specific pins the related AI Prompt Model below, so installers swap the model here (in metadata) rather than in code.'
SET
  @TemplateID_ee9cc77c = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @CategoryID_ee9cc77c = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_ee9cc77c = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_ee9cc77c = N'Active'
SET
  @ResponseFormat_ee9cc77c = N'JSON'
SET
  @AIModelTypeID_ee9cc77c = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_ee9cc77c = 0
SET
  @SelectionStrategy_ee9cc77c = N'Specific'
SET
  @PowerPreference_ee9cc77c = N'Highest'
SET
  @ParallelizationMode_ee9cc77c = N'None'
SET
  @OutputType_ee9cc77c = N'object'
SET
  @OutputExample_ee9cc77c = N'{"name":"Event RSVP","description?":"Let us know if you can make it.","renderMode?":"Scroll","confirmationMessage?":"Thanks — your RSVP has been recorded.","pages":[{"title?":"Your details","description?":"A few quick questions.","conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}},"questions":[{"key?":"attending","type":"SingleChoice","prompt":"Will you attend?","helpText?":"Pick one.","isRequired?":true,"options?":[{"label":"Yes","value?":"yes","isDefault?":true,"imagePrompt?":"a lit function room","imageURL?":"https://cdn.example.com/yes.png","matrixAxis?":"Row"},{"label":"No","value?":"no"}],"settings?":{"min":0,"max":5},"validationRule?":{"minLength?":2,"maxLength?":200,"min?":0,"max?":5,"pattern?":"^[A-Z]{3}$","patternMessage?":"Use three capital letters."},"conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}}}]}],"screens?":{"welcome?":{"title":"You''re invited","body?":"Two minutes.","buttonLabel?":"RSVP","imagePrompt?":"a long table set for dinner, warm evening light"},"endings?":[{"title":"See you there","body?":"We''ll email the details.","buttonLabel?":"Done","redirectURL?":"https://example.com","isDefault?":true,"imagePrompt?":"confetti on a dark background","conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}}}]},"theme?":{"brandAdjectives?":["warm","welcoming"],"brandURL?":"https://example.com"}}'
SET
  @ValidationBehavior_ee9cc77c = N'Strict'
SET
  @MaxRetries_ee9cc77c = 2
SET
  @RetryDelayMS_ee9cc77c = 0
SET
  @RetryStrategy_ee9cc77c = N'Fixed'
SET
  @EnableCaching_ee9cc77c = 0
SET
  @CacheMatchType_ee9cc77c = N'Exact'
SET
  @CacheMustMatchModel_ee9cc77c = 1
SET
  @CacheMustMatchVendor_ee9cc77c = 1
SET
  @CacheMustMatchAgent_ee9cc77c = 0
SET
  @CacheMustMatchConfig_ee9cc77c = 0
SET
  @PromptRole_ee9cc77c = N'System'
SET
  @PromptPosition_ee9cc77c = N'First'
SET
  @IncludeLogProbs_ee9cc77c = 0
SET
  @FailoverStrategy_ee9cc77c = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_ee9cc77c = 3
SET
  @FailoverDelaySeconds_ee9cc77c = 5
SET
  @FailoverModelStrategy_ee9cc77c = N'PreferSameModel'
SET
  @FailoverErrorScope_ee9cc77c = N'All'
SET
  @PrefillFallbackMode_ee9cc77c = N'Ignore'
SET
  @RequireSpecificModels_ee9cc77c = 0
SET
  @ID_ee9cc77c = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829304' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_ee9cc77c,
  @Description = @Description_ee9cc77c,
  @TemplateID = @TemplateID_ee9cc77c,
  @CategoryID = @CategoryID_ee9cc77c,
  @TypeID = @TypeID_ee9cc77c,
  @Status = @Status_ee9cc77c,
  @ResponseFormat = @ResponseFormat_ee9cc77c,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_ee9cc77c,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_ee9cc77c,
  @MinPowerRank = @MinPowerRank_ee9cc77c,
  @SelectionStrategy = @SelectionStrategy_ee9cc77c,
  @PowerPreference = @PowerPreference_ee9cc77c,
  @ParallelizationMode = @ParallelizationMode_ee9cc77c,
  @ParallelCount = @ParallelCount_ee9cc77c,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_ee9cc77c,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_ee9cc77c,
  @OutputExample = @OutputExample_ee9cc77c,
  @ValidationBehavior = @ValidationBehavior_ee9cc77c,
  @MaxRetries = @MaxRetries_ee9cc77c,
  @RetryDelayMS = @RetryDelayMS_ee9cc77c,
  @RetryStrategy = @RetryStrategy_ee9cc77c,
  @ResultSelectorPromptID = @ResultSelectorPromptID_ee9cc77c,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_ee9cc77c,
  @CacheTTLSeconds = @CacheTTLSeconds_ee9cc77c,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_ee9cc77c,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_ee9cc77c,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_ee9cc77c,
  @CacheMustMatchVendor = @CacheMustMatchVendor_ee9cc77c,
  @CacheMustMatchAgent = @CacheMustMatchAgent_ee9cc77c,
  @CacheMustMatchConfig = @CacheMustMatchConfig_ee9cc77c,
  @PromptRole = @PromptRole_ee9cc77c,
  @PromptPosition = @PromptPosition_ee9cc77c,
  @Temperature = @Temperature_ee9cc77c,
  @Temperature_Clear = 1,
  @TopP = @TopP_ee9cc77c,
  @TopP_Clear = 1,
  @TopK = @TopK_ee9cc77c,
  @TopK_Clear = 1,
  @MinP = @MinP_ee9cc77c,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_ee9cc77c,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_ee9cc77c,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_ee9cc77c,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_ee9cc77c,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_ee9cc77c,
  @TopLogProbs = @TopLogProbs_ee9cc77c,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_ee9cc77c,
  @FailoverMaxAttempts = @FailoverMaxAttempts_ee9cc77c,
  @FailoverDelaySeconds = @FailoverDelaySeconds_ee9cc77c,
  @FailoverModelStrategy = @FailoverModelStrategy_ee9cc77c,
  @FailoverErrorScope = @FailoverErrorScope_ee9cc77c,
  @EffortLevel = @EffortLevel_ee9cc77c,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_ee9cc77c,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_ee9cc77c,
  @RequireSpecificModels = @RequireSpecificModels_ee9cc77c,
  @ID = @ID_ee9cc77c;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_76421b8a NVARCHAR(255),
@Description_76421b8a NVARCHAR(MAX),
@TemplateID_76421b8a UNIQUEIDENTIFIER,
@CategoryID_76421b8a UNIQUEIDENTIFIER,
@TypeID_76421b8a UNIQUEIDENTIFIER,
@Status_76421b8a NVARCHAR(50),
@ResponseFormat_76421b8a NVARCHAR(20),
@ModelSpecificResponseFormat_76421b8a NVARCHAR(MAX),
@AIModelTypeID_76421b8a UNIQUEIDENTIFIER,
@MinPowerRank_76421b8a INT,
@SelectionStrategy_76421b8a NVARCHAR(20),
@PowerPreference_76421b8a NVARCHAR(20),
@ParallelizationMode_76421b8a NVARCHAR(20),
@ParallelCount_76421b8a INT,
@ParallelConfigParam_76421b8a NVARCHAR(100),
@OutputType_76421b8a NVARCHAR(50),
@OutputExample_76421b8a NVARCHAR(MAX),
@ValidationBehavior_76421b8a NVARCHAR(50),
@MaxRetries_76421b8a INT,
@RetryDelayMS_76421b8a INT,
@RetryStrategy_76421b8a NVARCHAR(20),
@ResultSelectorPromptID_76421b8a UNIQUEIDENTIFIER,
@EnableCaching_76421b8a BIT,
@CacheTTLSeconds_76421b8a INT,
@CacheMatchType_76421b8a NVARCHAR(20),
@CacheSimilarityThreshold_76421b8a FLOAT(53),
@CacheMustMatchModel_76421b8a BIT,
@CacheMustMatchVendor_76421b8a BIT,
@CacheMustMatchAgent_76421b8a BIT,
@CacheMustMatchConfig_76421b8a BIT,
@PromptRole_76421b8a NVARCHAR(20),
@PromptPosition_76421b8a NVARCHAR(20),
@Temperature_76421b8a DECIMAL(3, 2),
@TopP_76421b8a DECIMAL(3, 2),
@TopK_76421b8a INT,
@MinP_76421b8a DECIMAL(3, 2),
@FrequencyPenalty_76421b8a DECIMAL(3, 2),
@PresencePenalty_76421b8a DECIMAL(3, 2),
@Seed_76421b8a INT,
@StopSequences_76421b8a NVARCHAR(1000),
@IncludeLogProbs_76421b8a BIT,
@TopLogProbs_76421b8a INT,
@FailoverStrategy_76421b8a NVARCHAR(50),
@FailoverMaxAttempts_76421b8a INT,
@FailoverDelaySeconds_76421b8a INT,
@FailoverModelStrategy_76421b8a NVARCHAR(50),
@FailoverErrorScope_76421b8a NVARCHAR(50),
@EffortLevel_76421b8a INT,
@AssistantPrefill_76421b8a NVARCHAR(MAX),
@PrefillFallbackMode_76421b8a NVARCHAR(20),
@RequireSpecificModels_76421b8a BIT,
@ID_76421b8a UNIQUEIDENTIFIER
SET
  @Name_76421b8a = N'Forms: Form Outline'
SET
  @Description_76421b8a = N'First pass of a staged AI form build. Sketches the SHAPE of a form — pages, question stubs, screens and a theme brief — from a brief or a pasted question list. Kept small and fast because it gates how quickly the author sees a real form; the ''Forms: Page Detail'' prompt fills each page in afterwards. Model selection is metadata-driven (SelectionStrategy=Specific pins the AI Prompt Model row below), so this stage can be pointed at a faster model than the detail stage without a code change.'
SET
  @TemplateID_76421b8a = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F62'
SET
  @CategoryID_76421b8a = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_76421b8a = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_76421b8a = N'Active'
SET
  @ResponseFormat_76421b8a = N'JSON'
SET
  @AIModelTypeID_76421b8a = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_76421b8a = 0
SET
  @SelectionStrategy_76421b8a = N'Specific'
SET
  @PowerPreference_76421b8a = N'Highest'
SET
  @ParallelizationMode_76421b8a = N'None'
SET
  @OutputType_76421b8a = N'object'
SET
  @OutputExample_76421b8a = N'{"name":"Conference RSVP","description?":"Let us know if you can make it.","renderMode?":"Scroll","confirmationMessage?":"Thanks — your RSVP has been recorded.","pages":[{"title?":"Your details","description?":"A few quick questions.","conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}},"questions":[{"key?":"attending","type":"SingleChoice","prompt":"Will you attend?"}]}],"screens?":{"welcome?":{"title":"You''re invited","body?":"Two minutes.","buttonLabel?":"RSVP","imagePrompt?":"a long table set for dinner, warm evening light"},"endings?":[{"title":"See you there","body?":"We''ll email the details.","buttonLabel?":"Done","redirectURL?":"https://example.com","isDefault?":true,"imagePrompt?":"confetti on a dark background","conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}}}]},"theme?":{"brandAdjectives?":["warm","welcoming"]}}'
SET
  @ValidationBehavior_76421b8a = N'Strict'
SET
  @MaxRetries_76421b8a = 2
SET
  @RetryDelayMS_76421b8a = 0
SET
  @RetryStrategy_76421b8a = N'Fixed'
SET
  @EnableCaching_76421b8a = 0
SET
  @CacheMatchType_76421b8a = N'Exact'
SET
  @CacheMustMatchModel_76421b8a = 1
SET
  @CacheMustMatchVendor_76421b8a = 1
SET
  @CacheMustMatchAgent_76421b8a = 0
SET
  @CacheMustMatchConfig_76421b8a = 0
SET
  @PromptRole_76421b8a = N'System'
SET
  @PromptPosition_76421b8a = N'First'
SET
  @IncludeLogProbs_76421b8a = 0
SET
  @FailoverStrategy_76421b8a = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_76421b8a = 3
SET
  @FailoverDelaySeconds_76421b8a = 5
SET
  @FailoverModelStrategy_76421b8a = N'PreferSameModel'
SET
  @FailoverErrorScope_76421b8a = N'All'
SET
  @PrefillFallbackMode_76421b8a = N'Ignore'
SET
  @RequireSpecificModels_76421b8a = 0
SET
  @ID_76421b8a = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829305' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_76421b8a,
  @Description = @Description_76421b8a,
  @TemplateID = @TemplateID_76421b8a,
  @CategoryID = @CategoryID_76421b8a,
  @TypeID = @TypeID_76421b8a,
  @Status = @Status_76421b8a,
  @ResponseFormat = @ResponseFormat_76421b8a,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_76421b8a,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_76421b8a,
  @MinPowerRank = @MinPowerRank_76421b8a,
  @SelectionStrategy = @SelectionStrategy_76421b8a,
  @PowerPreference = @PowerPreference_76421b8a,
  @ParallelizationMode = @ParallelizationMode_76421b8a,
  @ParallelCount = @ParallelCount_76421b8a,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_76421b8a,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_76421b8a,
  @OutputExample = @OutputExample_76421b8a,
  @ValidationBehavior = @ValidationBehavior_76421b8a,
  @MaxRetries = @MaxRetries_76421b8a,
  @RetryDelayMS = @RetryDelayMS_76421b8a,
  @RetryStrategy = @RetryStrategy_76421b8a,
  @ResultSelectorPromptID = @ResultSelectorPromptID_76421b8a,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_76421b8a,
  @CacheTTLSeconds = @CacheTTLSeconds_76421b8a,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_76421b8a,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_76421b8a,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_76421b8a,
  @CacheMustMatchVendor = @CacheMustMatchVendor_76421b8a,
  @CacheMustMatchAgent = @CacheMustMatchAgent_76421b8a,
  @CacheMustMatchConfig = @CacheMustMatchConfig_76421b8a,
  @PromptRole = @PromptRole_76421b8a,
  @PromptPosition = @PromptPosition_76421b8a,
  @Temperature = @Temperature_76421b8a,
  @Temperature_Clear = 1,
  @TopP = @TopP_76421b8a,
  @TopP_Clear = 1,
  @TopK = @TopK_76421b8a,
  @TopK_Clear = 1,
  @MinP = @MinP_76421b8a,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_76421b8a,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_76421b8a,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_76421b8a,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_76421b8a,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_76421b8a,
  @TopLogProbs = @TopLogProbs_76421b8a,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_76421b8a,
  @FailoverMaxAttempts = @FailoverMaxAttempts_76421b8a,
  @FailoverDelaySeconds = @FailoverDelaySeconds_76421b8a,
  @FailoverModelStrategy = @FailoverModelStrategy_76421b8a,
  @FailoverErrorScope = @FailoverErrorScope_76421b8a,
  @EffortLevel = @EffortLevel_76421b8a,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_76421b8a,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_76421b8a,
  @RequireSpecificModels = @RequireSpecificModels_76421b8a,
  @ID = @ID_76421b8a;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_b35d0784 NVARCHAR(255),
@Description_b35d0784 NVARCHAR(MAX),
@TemplateID_b35d0784 UNIQUEIDENTIFIER,
@CategoryID_b35d0784 UNIQUEIDENTIFIER,
@TypeID_b35d0784 UNIQUEIDENTIFIER,
@Status_b35d0784 NVARCHAR(50),
@ResponseFormat_b35d0784 NVARCHAR(20),
@ModelSpecificResponseFormat_b35d0784 NVARCHAR(MAX),
@AIModelTypeID_b35d0784 UNIQUEIDENTIFIER,
@MinPowerRank_b35d0784 INT,
@SelectionStrategy_b35d0784 NVARCHAR(20),
@PowerPreference_b35d0784 NVARCHAR(20),
@ParallelizationMode_b35d0784 NVARCHAR(20),
@ParallelCount_b35d0784 INT,
@ParallelConfigParam_b35d0784 NVARCHAR(100),
@OutputType_b35d0784 NVARCHAR(50),
@OutputExample_b35d0784 NVARCHAR(MAX),
@ValidationBehavior_b35d0784 NVARCHAR(50),
@MaxRetries_b35d0784 INT,
@RetryDelayMS_b35d0784 INT,
@RetryStrategy_b35d0784 NVARCHAR(20),
@ResultSelectorPromptID_b35d0784 UNIQUEIDENTIFIER,
@EnableCaching_b35d0784 BIT,
@CacheTTLSeconds_b35d0784 INT,
@CacheMatchType_b35d0784 NVARCHAR(20),
@CacheSimilarityThreshold_b35d0784 FLOAT(53),
@CacheMustMatchModel_b35d0784 BIT,
@CacheMustMatchVendor_b35d0784 BIT,
@CacheMustMatchAgent_b35d0784 BIT,
@CacheMustMatchConfig_b35d0784 BIT,
@PromptRole_b35d0784 NVARCHAR(20),
@PromptPosition_b35d0784 NVARCHAR(20),
@Temperature_b35d0784 DECIMAL(3, 2),
@TopP_b35d0784 DECIMAL(3, 2),
@TopK_b35d0784 INT,
@MinP_b35d0784 DECIMAL(3, 2),
@FrequencyPenalty_b35d0784 DECIMAL(3, 2),
@PresencePenalty_b35d0784 DECIMAL(3, 2),
@Seed_b35d0784 INT,
@StopSequences_b35d0784 NVARCHAR(1000),
@IncludeLogProbs_b35d0784 BIT,
@TopLogProbs_b35d0784 INT,
@FailoverStrategy_b35d0784 NVARCHAR(50),
@FailoverMaxAttempts_b35d0784 INT,
@FailoverDelaySeconds_b35d0784 INT,
@FailoverModelStrategy_b35d0784 NVARCHAR(50),
@FailoverErrorScope_b35d0784 NVARCHAR(50),
@EffortLevel_b35d0784 INT,
@AssistantPrefill_b35d0784 NVARCHAR(MAX),
@PrefillFallbackMode_b35d0784 NVARCHAR(20),
@RequireSpecificModels_b35d0784 BIT,
@ID_b35d0784 UNIQUEIDENTIFIER
SET
  @Name_b35d0784 = N'Forms: Page Detail'
SET
  @Description_b35d0784 = N'Second pass of a staged AI form build. Given the brief, the whole outline for coherence, and one page''s sketched questions, writes that page''s questions in full — options, help text, settings, validation and show/hide logic. Run once per page with bounded concurrency. Model selection is metadata-driven, so this stage can be pointed at a more careful model than the outline stage without a code change.'
SET
  @TemplateID_b35d0784 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F63'
SET
  @CategoryID_b35d0784 = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_b35d0784 = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_b35d0784 = N'Active'
SET
  @ResponseFormat_b35d0784 = N'JSON'
SET
  @AIModelTypeID_b35d0784 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_b35d0784 = 0
SET
  @SelectionStrategy_b35d0784 = N'Specific'
SET
  @PowerPreference_b35d0784 = N'Highest'
SET
  @ParallelizationMode_b35d0784 = N'None'
SET
  @OutputType_b35d0784 = N'object'
SET
  @OutputExample_b35d0784 = N'{"questions":[{"key?":"attending","type":"SingleChoice","prompt":"Will you attend?","helpText?":"Pick one.","isRequired?":true,"options?":[{"label":"Yes, I''ll be there","value?":"yes","isDefault?":true,"imagePrompt?":"a lit function room","matrixAxis?":"Row"},{"label":"Sorry, I can''t make it","value?":"no"}],"settings?":{"min":0,"max":5},"validationRule?":{"minLength?":2,"maxLength?":200,"min?":0,"max?":5,"pattern?":"^[A-Z]{3}$","patternMessage?":"Use three capital letters."},"conditionalRule?":{"show":{"all":[{"questionKey":"attending","op":"equals","value":"yes"}]}}}]}'
SET
  @ValidationBehavior_b35d0784 = N'Strict'
SET
  @MaxRetries_b35d0784 = 2
SET
  @RetryDelayMS_b35d0784 = 0
SET
  @RetryStrategy_b35d0784 = N'Fixed'
SET
  @EnableCaching_b35d0784 = 0
SET
  @CacheMatchType_b35d0784 = N'Exact'
SET
  @CacheMustMatchModel_b35d0784 = 1
SET
  @CacheMustMatchVendor_b35d0784 = 1
SET
  @CacheMustMatchAgent_b35d0784 = 0
SET
  @CacheMustMatchConfig_b35d0784 = 0
SET
  @PromptRole_b35d0784 = N'System'
SET
  @PromptPosition_b35d0784 = N'First'
SET
  @IncludeLogProbs_b35d0784 = 0
SET
  @FailoverStrategy_b35d0784 = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_b35d0784 = 3
SET
  @FailoverDelaySeconds_b35d0784 = 5
SET
  @FailoverModelStrategy_b35d0784 = N'PreferSameModel'
SET
  @FailoverErrorScope_b35d0784 = N'All'
SET
  @PrefillFallbackMode_b35d0784 = N'Ignore'
SET
  @RequireSpecificModels_b35d0784 = 0
SET
  @ID_b35d0784 = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829306' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_b35d0784,
  @Description = @Description_b35d0784,
  @TemplateID = @TemplateID_b35d0784,
  @CategoryID = @CategoryID_b35d0784,
  @TypeID = @TypeID_b35d0784,
  @Status = @Status_b35d0784,
  @ResponseFormat = @ResponseFormat_b35d0784,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_b35d0784,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_b35d0784,
  @MinPowerRank = @MinPowerRank_b35d0784,
  @SelectionStrategy = @SelectionStrategy_b35d0784,
  @PowerPreference = @PowerPreference_b35d0784,
  @ParallelizationMode = @ParallelizationMode_b35d0784,
  @ParallelCount = @ParallelCount_b35d0784,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_b35d0784,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_b35d0784,
  @OutputExample = @OutputExample_b35d0784,
  @ValidationBehavior = @ValidationBehavior_b35d0784,
  @MaxRetries = @MaxRetries_b35d0784,
  @RetryDelayMS = @RetryDelayMS_b35d0784,
  @RetryStrategy = @RetryStrategy_b35d0784,
  @ResultSelectorPromptID = @ResultSelectorPromptID_b35d0784,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_b35d0784,
  @CacheTTLSeconds = @CacheTTLSeconds_b35d0784,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_b35d0784,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_b35d0784,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_b35d0784,
  @CacheMustMatchVendor = @CacheMustMatchVendor_b35d0784,
  @CacheMustMatchAgent = @CacheMustMatchAgent_b35d0784,
  @CacheMustMatchConfig = @CacheMustMatchConfig_b35d0784,
  @PromptRole = @PromptRole_b35d0784,
  @PromptPosition = @PromptPosition_b35d0784,
  @Temperature = @Temperature_b35d0784,
  @Temperature_Clear = 1,
  @TopP = @TopP_b35d0784,
  @TopP_Clear = 1,
  @TopK = @TopK_b35d0784,
  @TopK_Clear = 1,
  @MinP = @MinP_b35d0784,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_b35d0784,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_b35d0784,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_b35d0784,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_b35d0784,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_b35d0784,
  @TopLogProbs = @TopLogProbs_b35d0784,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_b35d0784,
  @FailoverMaxAttempts = @FailoverMaxAttempts_b35d0784,
  @FailoverDelaySeconds = @FailoverDelaySeconds_b35d0784,
  @FailoverModelStrategy = @FailoverModelStrategy_b35d0784,
  @FailoverErrorScope = @FailoverErrorScope_b35d0784,
  @EffortLevel = @EffortLevel_b35d0784,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_b35d0784,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_b35d0784,
  @RequireSpecificModels = @RequireSpecificModels_b35d0784,
  @ID = @ID_b35d0784;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_f9fd5748 NVARCHAR(255),
@Description_f9fd5748 NVARCHAR(MAX),
@TemplateID_f9fd5748 UNIQUEIDENTIFIER,
@CategoryID_f9fd5748 UNIQUEIDENTIFIER,
@TypeID_f9fd5748 UNIQUEIDENTIFIER,
@Status_f9fd5748 NVARCHAR(50),
@ResponseFormat_f9fd5748 NVARCHAR(20),
@ModelSpecificResponseFormat_f9fd5748 NVARCHAR(MAX),
@AIModelTypeID_f9fd5748 UNIQUEIDENTIFIER,
@MinPowerRank_f9fd5748 INT,
@SelectionStrategy_f9fd5748 NVARCHAR(20),
@PowerPreference_f9fd5748 NVARCHAR(20),
@ParallelizationMode_f9fd5748 NVARCHAR(20),
@ParallelCount_f9fd5748 INT,
@ParallelConfigParam_f9fd5748 NVARCHAR(100),
@OutputType_f9fd5748 NVARCHAR(50),
@OutputExample_f9fd5748 NVARCHAR(MAX),
@ValidationBehavior_f9fd5748 NVARCHAR(50),
@MaxRetries_f9fd5748 INT,
@RetryDelayMS_f9fd5748 INT,
@RetryStrategy_f9fd5748 NVARCHAR(20),
@ResultSelectorPromptID_f9fd5748 UNIQUEIDENTIFIER,
@EnableCaching_f9fd5748 BIT,
@CacheTTLSeconds_f9fd5748 INT,
@CacheMatchType_f9fd5748 NVARCHAR(20),
@CacheSimilarityThreshold_f9fd5748 FLOAT(53),
@CacheMustMatchModel_f9fd5748 BIT,
@CacheMustMatchVendor_f9fd5748 BIT,
@CacheMustMatchAgent_f9fd5748 BIT,
@CacheMustMatchConfig_f9fd5748 BIT,
@PromptRole_f9fd5748 NVARCHAR(20),
@PromptPosition_f9fd5748 NVARCHAR(20),
@Temperature_f9fd5748 DECIMAL(3, 2),
@TopP_f9fd5748 DECIMAL(3, 2),
@TopK_f9fd5748 INT,
@MinP_f9fd5748 DECIMAL(3, 2),
@FrequencyPenalty_f9fd5748 DECIMAL(3, 2),
@PresencePenalty_f9fd5748 DECIMAL(3, 2),
@Seed_f9fd5748 INT,
@StopSequences_f9fd5748 NVARCHAR(1000),
@IncludeLogProbs_f9fd5748 BIT,
@TopLogProbs_f9fd5748 INT,
@FailoverStrategy_f9fd5748 NVARCHAR(50),
@FailoverMaxAttempts_f9fd5748 INT,
@FailoverDelaySeconds_f9fd5748 INT,
@FailoverModelStrategy_f9fd5748 NVARCHAR(50),
@FailoverErrorScope_f9fd5748 NVARCHAR(50),
@EffortLevel_f9fd5748 INT,
@AssistantPrefill_f9fd5748 NVARCHAR(MAX),
@PrefillFallbackMode_f9fd5748 NVARCHAR(20),
@RequireSpecificModels_f9fd5748 BIT,
@ID_f9fd5748 UNIQUEIDENTIFIER
SET
  @Name_f9fd5748 = N'Forms: Theme Designer'
SET
  @Description_f9fd5748 = N'Final pass of a staged AI form build. Turns the brief plus the outline''s brand adjectives into a --mjf-* token map. Deliberately does NOT judge its own accessibility: unknown tokens are stripped and unreadable ink is corrected by arithmetic before persist, because re-prompting a model that produced one unreadable pair is a round trip for a coin flip. Model selection is metadata-driven.'
SET
  @TemplateID_f9fd5748 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F64'
SET
  @CategoryID_f9fd5748 = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_f9fd5748 = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_f9fd5748 = N'Active'
SET
  @ResponseFormat_f9fd5748 = N'JSON'
SET
  @AIModelTypeID_f9fd5748 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_f9fd5748 = 0
SET
  @SelectionStrategy_f9fd5748 = N'Specific'
SET
  @PowerPreference_f9fd5748 = N'Highest'
SET
  @ParallelizationMode_f9fd5748 = N'None'
SET
  @OutputType_f9fd5748 = N'object'
SET
  @OutputExample_f9fd5748 = N'{"cssVariables":{"--mjf-page-bg?":"#fdf8f3","--mjf-card-bg?":"#ffffff","--mjf-page-ink?":"#2b2118","--mjf-accent?":"#a8542a","--mjf-accent-strong?":"#8a4321","--mjf-on-accent?":"#ffffff","--mjf-choice-selected-bg?":"#f6e7db","--mjf-font-body?":"''Nunito'', system-ui, sans-serif","--mjf-font-display?":"''Fraunces'', Georgia, serif"}}'
SET
  @ValidationBehavior_f9fd5748 = N'Strict'
SET
  @MaxRetries_f9fd5748 = 2
SET
  @RetryDelayMS_f9fd5748 = 0
SET
  @RetryStrategy_f9fd5748 = N'Fixed'
SET
  @EnableCaching_f9fd5748 = 0
SET
  @CacheMatchType_f9fd5748 = N'Exact'
SET
  @CacheMustMatchModel_f9fd5748 = 1
SET
  @CacheMustMatchVendor_f9fd5748 = 1
SET
  @CacheMustMatchAgent_f9fd5748 = 0
SET
  @CacheMustMatchConfig_f9fd5748 = 0
SET
  @PromptRole_f9fd5748 = N'System'
SET
  @PromptPosition_f9fd5748 = N'First'
SET
  @IncludeLogProbs_f9fd5748 = 0
SET
  @FailoverStrategy_f9fd5748 = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_f9fd5748 = 3
SET
  @FailoverDelaySeconds_f9fd5748 = 5
SET
  @FailoverModelStrategy_f9fd5748 = N'PreferSameModel'
SET
  @FailoverErrorScope_f9fd5748 = N'All'
SET
  @PrefillFallbackMode_f9fd5748 = N'Ignore'
SET
  @RequireSpecificModels_f9fd5748 = 0
SET
  @ID_f9fd5748 = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829307' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_f9fd5748,
  @Description = @Description_f9fd5748,
  @TemplateID = @TemplateID_f9fd5748,
  @CategoryID = @CategoryID_f9fd5748,
  @TypeID = @TypeID_f9fd5748,
  @Status = @Status_f9fd5748,
  @ResponseFormat = @ResponseFormat_f9fd5748,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_f9fd5748,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_f9fd5748,
  @MinPowerRank = @MinPowerRank_f9fd5748,
  @SelectionStrategy = @SelectionStrategy_f9fd5748,
  @PowerPreference = @PowerPreference_f9fd5748,
  @ParallelizationMode = @ParallelizationMode_f9fd5748,
  @ParallelCount = @ParallelCount_f9fd5748,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_f9fd5748,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_f9fd5748,
  @OutputExample = @OutputExample_f9fd5748,
  @ValidationBehavior = @ValidationBehavior_f9fd5748,
  @MaxRetries = @MaxRetries_f9fd5748,
  @RetryDelayMS = @RetryDelayMS_f9fd5748,
  @RetryStrategy = @RetryStrategy_f9fd5748,
  @ResultSelectorPromptID = @ResultSelectorPromptID_f9fd5748,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_f9fd5748,
  @CacheTTLSeconds = @CacheTTLSeconds_f9fd5748,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_f9fd5748,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_f9fd5748,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_f9fd5748,
  @CacheMustMatchVendor = @CacheMustMatchVendor_f9fd5748,
  @CacheMustMatchAgent = @CacheMustMatchAgent_f9fd5748,
  @CacheMustMatchConfig = @CacheMustMatchConfig_f9fd5748,
  @PromptRole = @PromptRole_f9fd5748,
  @PromptPosition = @PromptPosition_f9fd5748,
  @Temperature = @Temperature_f9fd5748,
  @Temperature_Clear = 1,
  @TopP = @TopP_f9fd5748,
  @TopP_Clear = 1,
  @TopK = @TopK_f9fd5748,
  @TopK_Clear = 1,
  @MinP = @MinP_f9fd5748,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_f9fd5748,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_f9fd5748,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_f9fd5748,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_f9fd5748,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_f9fd5748,
  @TopLogProbs = @TopLogProbs_f9fd5748,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_f9fd5748,
  @FailoverMaxAttempts = @FailoverMaxAttempts_f9fd5748,
  @FailoverDelaySeconds = @FailoverDelaySeconds_f9fd5748,
  @FailoverModelStrategy = @FailoverModelStrategy_f9fd5748,
  @FailoverErrorScope = @FailoverErrorScope_f9fd5748,
  @EffortLevel = @EffortLevel_f9fd5748,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_f9fd5748,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_f9fd5748,
  @RequireSpecificModels = @RequireSpecificModels_f9fd5748,
  @ID = @ID_f9fd5748;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_ee305e07 UNIQUEIDENTIFIER,
@EntityID_ee305e07 UNIQUEIDENTIFIER,
@Name_ee305e07 NVARCHAR(100),
@Description_ee305e07 NVARCHAR(MAX),
@CategoryID_ee305e07 UNIQUEIDENTIFIER,
@IsShared_ee305e07 BIT,
@IsDefault_ee305e07 BIT,
@GridState_ee305e07 NVARCHAR(MAX),
@FilterState_ee305e07 NVARCHAR(MAX),
@CustomFilterState_ee305e07 BIT,
@SmartFilterEnabled_ee305e07 BIT,
@SmartFilterPrompt_ee305e07 NVARCHAR(MAX),
@SmartFilterWhereClause_ee305e07 NVARCHAR(MAX),
@SmartFilterExplanation_ee305e07 NVARCHAR(MAX),
@WhereClause_ee305e07 NVARCHAR(MAX),
@CustomWhereClause_ee305e07 BIT,
@SortState_ee305e07 NVARCHAR(MAX),
@Thumbnail_ee305e07 NVARCHAR(MAX),
@CardState_ee305e07 NVARCHAR(MAX),
@DisplayState_ee305e07 NVARCHAR(MAX),
@ViewTypeID_ee305e07 UNIQUEIDENTIFIER,
@ID_ee305e07 UNIQUEIDENTIFIER
SET
  @UserID_ee305e07 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_ee305e07 = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_ee305e07 = N'All Forms'
SET
  @Description_ee305e07 = N''
SET
  @IsShared_ee305e07 = 1
SET
  @IsDefault_ee305e07 = 0
SET
  @GridState_ee305e07 = N'{}'
SET
  @FilterState_ee305e07 = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_ee305e07 = 0
SET
  @SmartFilterEnabled_ee305e07 = 0
SET
  @WhereClause_ee305e07 = N''
SET
  @CustomWhereClause_ee305e07 = 0
SET
  @ID_ee305e07 = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_ee305e07,
  @EntityID = @EntityID_ee305e07,
  @Name = @Name_ee305e07,
  @Description = @Description_ee305e07,
  @CategoryID = @CategoryID_ee305e07,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_ee305e07,
  @IsDefault = @IsDefault_ee305e07,
  @GridState = @GridState_ee305e07,
  @FilterState = @FilterState_ee305e07,
  @CustomFilterState = @CustomFilterState_ee305e07,
  @SmartFilterEnabled = @SmartFilterEnabled_ee305e07,
  @SmartFilterPrompt = @SmartFilterPrompt_ee305e07,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_ee305e07,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_ee305e07,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_ee305e07,
  @CustomWhereClause = @CustomWhereClause_ee305e07,
  @SortState = @SortState_ee305e07,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_ee305e07,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_ee305e07,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_ee305e07,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_ee305e07,
  @ViewTypeID_Clear = 1,
  @ID = @ID_ee305e07;

GO


-- End of SQL Logging Session
-- Session ID: 5d684731-bd70-4c6b-8b81-08916283b185
-- Completed: 2026-08-20T20:59:35.253Z
-- Duration: 5870ms
-- Total Statements: 27
