-- MJ Forms v0.12.x — the consolidated release metadata seed.
--
-- ONE seed per release (#105). This file folds in and REPLACES two per-PR deltas that reached no
-- release tag and therefore no host: V202608182130 (Designer taxonomy) and V202608241800 (OnSubmit
-- ActionParams). The release retires both — their deletion lands in the same release as this file,
-- not in this commit. They were never append-only history — a seed becomes history when a release
-- tag carries it, and neither was in v0.10.0.
--
-- GENERATED AGAINST THE SHIPPED CHAIN AT HEAD *MINUS* THOSE TWO FILES, which is the only database
-- that produces a complete delta. On a database that ran them, the four ActionParam records already
-- match metadata/, `mj sync push` emits nothing for them, and deleting the delta strands four ids
-- that no migration names. See migrations/README.md — three requirements, not one. The four
-- spCreateActionParam calls below are guarded on (ActionID, Name), not just ID, for two reasons that
-- survive the delete: any database that already applied V202608241800 (clean-room databases, PR
-- databases, anything migrated off next since 2026-08-24) still holds those four records, and an
-- unguarded create would halt its chain with a PK violation no later migration could repair; and a
-- host where CodeGen minted an OnSubmitMode/Automations param on those actions first would otherwise
-- get a duplicate by name — the #64 defect class.
--
-- WHAT A HOST GETS. spCreate* for records added since v0.10.0, including the four OnSubmit
-- ActionParams. spUpdate* for records edited since, including the AI Designer prompt, which until
-- now still proposed `Signature` — a question type V202608301200 installs a CHECK constraint to
-- reject. Authoring a form therefore burned Designer retries against MAX_DESIGNER_ATTEMPTS on every
-- brief. That half is invisible to check:release-seed, which compares ids and not content (#97, #111).
--
-- THE TWO FORM RESPONDENT READ GRANTS ARE DELIBERATELY UNTOUCHED. This seed emits no
-- spUpdateEntityPermission at all, and that absence is the fix rather than an omission.
-- metadata/entity-permissions/.entity-permissions.json now declares CanRead: true plus the matching
-- ReadRLSFilterID @lookup on 'MJ_BizApps_Forms: Form Responses' and 'Form Response Answers' — the
-- state V202609091600 installs for resume-own-response (#138) — so the generation database and
-- metadata/ agree and there is nothing to emit. The first cut of this file revoked read on both
-- rows, because that JSON still carried the pre-#138 declaration and `mj sync push` dutifully
-- wrote the difference: the seed silently reverted the grant on every host that applied the chain,
-- leaving rows whose ReadRLSFilterID was populated and whose CanRead was not — correct-looking and
-- broken, and invisible to every gate. metadata/ is what has to stay in step with V202609091600;
-- regenerate this file against stale JSON and the revert comes straight back.
--
-- GENERATOR ARTIFACT — THE ORDER OF THE TEMPLATE PARAMS IS LOAD-BEARING. The 8
-- spUpdateTemplateParam calls below address only 5 distinct records: ids 1C2D3E4F…, 2D3E4F5A… and
-- 3E4F5A6B… each appear twice, and NOT with the same values. Saving the Designer's TemplateContent
-- makes MJ re-extract that template's parameters from the prompt text and write AI-authored
-- Descriptions over them (MJTemplateContentEntityServer.syncTemplateParameters); the push then
-- writes the Descriptions metadata/templates/.forms-form-designer-template.json actually declares.
-- The declared write comes SECOND and wins, so the end state is the declared one. Two consequences:
-- do not "de-duplicate" the six calls down to three by keeping the first of each pair, and do not
-- expect a regeneration to be byte-identical here — the AI-authored half is not reproducible, and
-- it did in fact come out differently across two pushes of identical metadata.

-- SQL Logging Session
-- Session ID: 1ef16a78-e3ad-4da2-9bcc-cc313f0ed185
-- Started: 2026-09-12T03:02:21.000Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Preflight: this file resolves Forms roles by name rather than by hardcoded id (#39), because a
-- host may have adopted a pre-existing role under a different id than the one this repo's own
-- database happened to hold when this seed was generated. spUpdateRole and spUpdateEntityPermission
-- key on @ID/@RoleID and raise nothing when the id resolves to zero rows — a missing or duplicated
-- role name would make every role and permission update below a silent no-op. This deliberately
-- duplicates V202608131600's Form Respondent assertion: that file only guarantees the role exists at
-- the point it is first created, and a seed that later resolves roles by name must be self-sufficient
-- about it rather than depend on an assertion two files away.
--
-- 51120 guards a lookup THIS generation does not contain: the Form Respondent permission rows are
-- absent from this seed by design (see the header). It is kept because the file is regenerated every
-- release, and those rows re-enter the generated output the moment metadata/ and the generation
-- database disagree about them again — at which point the assertion must already be here rather than
-- be re-derived by whoever regenerates it.
IF (SELECT COUNT(*) FROM [${mjSchema}].[Role] WHERE Name = N'Form Respondent') <> 1
    THROW 51120, 'MJ Forms V202609112116: expected exactly ONE role named ''Form Respondent''. This seed resolves Forms roles BY NAME (#39), so zero or many rows would make any permission update silent no-ops.', 1;
IF (SELECT COUNT(*) FROM [${mjSchema}].[Role] WHERE Name = N'Forms Automation Runner') <> 1
    THROW 51121, 'MJ Forms V202609112116: expected exactly ONE role named ''Forms Automation Runner''. This seed resolves that role BY NAME, so zero or many rows would make its role update a silent no-op.', 1;
GO

-- Save MJ: Roles (core SP call only)
DECLARE @Name_f6300007c90d NVARCHAR(50),
@Description_f6300007c90d NVARCHAR(MAX),
@DirectoryID_f6300007c90d NVARCHAR(250),
@SQLName_f6300007c90d NVARCHAR(250),
@ID_f6300007c90d UNIQUEIDENTIFIER
SET
  @Name_f6300007c90d = N'Forms Automation Runner'
SET
  @Description_f6300007c90d = N'The role on-submit automations and entity bindings execute under. Deliberately separate from the anonymous ''Form Respondent'' role: a respondent may only create a response, while an automation must read that response back and write business records downstream. Grants read on the response entities AND on the form definition it dispatches against (Forms, Form Questions) -- without those two the runtime cannot load the form or type its answers, and every automation fails on a permission error -- update on Form Responses only (so ''Forms: Upsert Respondent Person'' can stamp RespondentPersonID back onto the response), plus write on the Forms-owned automation/binding bookkeeping tables, and READ on the upload provenance ledger (Form Uploads) -- bind-time verification refuses a file answer it cannot attribute, and without that read the lookup throws and every file-answer binding fails closed (#49). Never create on the ledger: a runner that can mint provenance rows can vouch for arbitrary files (DG-12a). Grants NOTHING on any binding target entity — those are added per deployment, and the set of them is the hard ceiling on what a form author can reach through a binding. Assign only to the seeded automation service user; never to a person.'
SET
  @ID_f6300007c90d = (SELECT ID FROM [${mjSchema}].[Role] WHERE Name = N'Forms Automation Runner') EXEC [${mjSchema}].spUpdateRole @Name = @Name_f6300007c90d,
  @Description = @Description_f6300007c90d,
  @DirectoryID = @DirectoryID_f6300007c90d,
  @DirectoryID_Clear = 1,
  @SQLName = @SQLName_f6300007c90d,
  @SQLName_Clear = 1,
  @ID = @ID_f6300007c90d;

GO

-- Save MJ: Template Contents (core SP call only)
DECLARE @TemplateID_7f6922bfd11f UNIQUEIDENTIFIER,
@TypeID_7f6922bfd11f UNIQUEIDENTIFIER,
@TemplateText_7f6922bfd11f NVARCHAR(MAX),
@Priority_7f6922bfd11f INT,
@IsActive_7f6922bfd11f BIT,
@ID_7f6922bfd11f UNIQUEIDENTIFIER
SET
  @TemplateID_7f6922bfd11f = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @TypeID_7f6922bfd11f = 'E7AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @TemplateText_7f6922bfd11f = N'You are a form-design assistant for MJ Forms. Given a natural-language brief, design a clear, friendly, mobile-first form and return it as a single JSON object — no prose, no markdown fences, JSON only.

The JSON MUST match this shape exactly:
{
  "name": string,                       // short form title
  "description"?: string,               // one-sentence intro shown to respondents
  "renderMode"?: "Scroll" | "OneQuestion",
  "confirmationMessage"?: string,       // shown after successful submit
  "pages": [                            // at least one page
    {
      "title"?: string,
      "description"?: string,
      "questions": [                    // at least one question per page
        {
          "type": <QuestionType>,       // see allowed types below
          "prompt": string,             // the question label
          "helpText"?: string,
          "isRequired"?: boolean,
          "options"?: [ { "label": string, "value"?: string, "isDefault"?: boolean } ],
          "settings"?: object           // per-type config, e.g. { "max": 5 } for Rating
        }
      ]
    }
  ]
}

Allowed "type" values:
ShortText, LongText, Email, Phone, Website, Number,
SingleChoice, MultiChoice, Dropdown, PictureChoice,
Rating, NPS, OpinionScale, Ranking, Matrix,
YesNo, Checkbox, Legal,
Date, Time,
Address, ContactInfo,
FileUpload, Doodle,
Statement.

Rules:
- "options" are REQUIRED for SingleChoice, MultiChoice, Dropdown, PictureChoice, Ranking and Matrix; provide at least two. Do NOT add options to any other type.
- Matrix options carry a "matrixAxis" of "Row" or "Column"; supply at least two of each.
- Use Email for email addresses, Phone for phone numbers, Website for URLs, Number for numeric inputs (e.g. a "+1 count" or quantity).
- Prefer ContactInfo over separate first-name / last-name / email / phone questions, and Address over separate street / city / postcode questions. Both collect the whole block in one field.
- Rating settings may include { "max": number } (stars, default 5). NPS is a fixed 0-10 scale. OpinionScale settings may include { "min": number, "max": number, "labelMin": string, "labelMax": string }.
- Checkbox is a single box to tick (consent, opt-in); its settings may include { "placeholder": string } for the text beside the box. Legal shows terms then Accept / Decline; put the terms in settings as { "terms": string }.
- Doodle is a freehand drawing pad; it is not a signature and carries no legal weight. Its settings may include { "penColor": string, "penWidth": string, "penControls": string } — leave them out unless the brief asks for a particular pen.
- Statement is display-only (a section header / instructional text); it is never required and has no options.
- Do NOT emit a welcome or thank-you "question". Those are SCREENS, configured separately from the questions, and a Statement standing in for one appears in the middle of the form instead of around it.
- Keep prompts concise. Mark only genuinely-required fields as required.
- Return valid JSON parseable by JSON.parse. Output the JSON object and nothing else.

Design a form for this request:

"""{{ Brief }}"""
{% if ValidationError %}
Your previous response was invalid:
{{ PreviousAttempt }}

Validation error: {{ ValidationError }}
Fix it and return ONLY the corrected JSON blueprint.
{% else %}
Return ONLY the JSON blueprint.
{% endif %}
'
SET
  @Priority_7f6922bfd11f = 100
SET
  @IsActive_7f6922bfd11f = 1
SET
  @ID_7f6922bfd11f = '8F1B6C2A-3D4E-4F50-9A61-7B2C3D4E5F60' EXEC [${mjSchema}].spUpdateTemplateContent @TemplateID = @TemplateID_7f6922bfd11f,
  @TypeID = @TypeID_7f6922bfd11f,
  @TemplateText = @TemplateText_7f6922bfd11f,
  @Priority = @Priority_7f6922bfd11f,
  @IsActive = @IsActive_7f6922bfd11f,
  @ID = @ID_7f6922bfd11f;

GO

-- HAND-PORTED FROM THE RETIRED V202608182130, WHICH WROTE TWO RECORDS AND NOT ONE. Besides the
-- TemplateContent text above, that delta corrected the Template's own Description, which still
-- advertised the Phase-1 taxonomy. `mj sync push` could not re-emit this one: the generation
-- database is the chain MINUS that delta, so it held the original text, and
-- metadata/templates/.forms-form-designer-template.json declared the same original text -- two
-- equal stale sides produce no diff, and a push emits nothing for a record it sees no difference
-- on. Retiring the delta therefore removed the ONLY writer of the corrected string from the chain
-- (V202608081700's spCreateTemplate is the only other one, and it writes the superseded text), so
-- every fresh install ended with a Description naming the Phase-1 taxonomy on a Template whose
-- prompt body enumerates the full 25-type one, Doodle included.
--
-- The declaration is corrected in the same change, which is the rule this file's README addition
-- states: metadata/ is the authority for every record it declares, so a migration that writes such
-- a record must update metadata/ too or the NEXT seed reverts it. With both sides now saying
-- "full", a regeneration sees no difference here and emits nothing -- the same settled state the
-- EntityPermission rows reach, and the reason this block should not reappear in a future seed.
IF EXISTS (SELECT 1 FROM [${mjSchema}].[Template] WHERE ID = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61')
BEGIN
    UPDATE [${mjSchema}].[Template]
    SET Description = N'System + user prompt for the Forms AI authoring Designer. Turns a natural-language brief (the {{ Brief }} parameter) into a structured FormBlueprint JSON object validated against the full question taxonomy. Used by the ''Forms: Form Designer'' AI Prompt.'
    WHERE ID = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61';
END

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@Name_9f7b66ce5ee0 NVARCHAR(255),
@Description_9f7b66ce5ee0 NVARCHAR(MAX),
@Type_9f7b66ce5ee0 NVARCHAR(20),
@DefaultValue_9f7b66ce5ee0 NVARCHAR(MAX),
@IsRequired_9f7b66ce5ee0 BIT,
@LinkedParameterName_9f7b66ce5ee0 NVARCHAR(255),
@LinkedParameterField_9f7b66ce5ee0 NVARCHAR(500),
@ExtraFilter_9f7b66ce5ee0 NVARCHAR(MAX),
@EntityID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@RecordID_9f7b66ce5ee0 NVARCHAR(2000),
@OrderBy_9f7b66ce5ee0 NVARCHAR(MAX),
@TemplateContentID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@ID_9f7b66ce5ee0 UNIQUEIDENTIFIER
SET
  @TemplateID_9f7b66ce5ee0 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_9f7b66ce5ee0 = N'Brief'
SET
  @Description_9f7b66ce5ee0 = N'The natural-language brief describing the form to be designed'
SET
  @Type_9f7b66ce5ee0 = N'Scalar'
SET
  @IsRequired_9f7b66ce5ee0 = 1
SET
  @ID_9f7b66ce5ee0 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E5F' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_9f7b66ce5ee0,
  @Name = @Name_9f7b66ce5ee0,
  @Description = @Description_9f7b66ce5ee0,
  @Type = @Type_9f7b66ce5ee0,
  @DefaultValue = @DefaultValue_9f7b66ce5ee0,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_9f7b66ce5ee0,
  @LinkedParameterName = @LinkedParameterName_9f7b66ce5ee0,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_9f7b66ce5ee0,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_9f7b66ce5ee0,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_9f7b66ce5ee0,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_9f7b66ce5ee0,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_9f7b66ce5ee0,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_9f7b66ce5ee0,
  @TemplateContentID_Clear = 1,
  @ID = @ID_9f7b66ce5ee0;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_e0380d77ac7c UNIQUEIDENTIFIER,
@Name_e0380d77ac7c NVARCHAR(255),
@Description_e0380d77ac7c NVARCHAR(MAX),
@Type_e0380d77ac7c NVARCHAR(20),
@DefaultValue_e0380d77ac7c NVARCHAR(MAX),
@IsRequired_e0380d77ac7c BIT,
@LinkedParameterName_e0380d77ac7c NVARCHAR(255),
@LinkedParameterField_e0380d77ac7c NVARCHAR(500),
@ExtraFilter_e0380d77ac7c NVARCHAR(MAX),
@EntityID_e0380d77ac7c UNIQUEIDENTIFIER,
@RecordID_e0380d77ac7c NVARCHAR(2000),
@OrderBy_e0380d77ac7c NVARCHAR(MAX),
@TemplateContentID_e0380d77ac7c UNIQUEIDENTIFIER,
@ID_e0380d77ac7c UNIQUEIDENTIFIER
SET
  @TemplateID_e0380d77ac7c = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_e0380d77ac7c = N'PreviousAttempt'
SET
  @Description_e0380d77ac7c = N'The content of the previous invalid JSON response'
SET
  @Type_e0380d77ac7c = N'Scalar'
SET
  @IsRequired_e0380d77ac7c = 0
SET
  @ID_e0380d77ac7c = '2D3E4F5A-6B7C-4D8E-9F0A-1B2C3D4E5F60' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_e0380d77ac7c,
  @Name = @Name_e0380d77ac7c,
  @Description = @Description_e0380d77ac7c,
  @Type = @Type_e0380d77ac7c,
  @DefaultValue = @DefaultValue_e0380d77ac7c,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_e0380d77ac7c,
  @LinkedParameterName = @LinkedParameterName_e0380d77ac7c,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_e0380d77ac7c,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_e0380d77ac7c,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_e0380d77ac7c,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_e0380d77ac7c,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_e0380d77ac7c,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_e0380d77ac7c,
  @TemplateContentID_Clear = 1,
  @ID = @ID_e0380d77ac7c;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_903ad94c3518 UNIQUEIDENTIFIER,
@Name_903ad94c3518 NVARCHAR(255),
@Description_903ad94c3518 NVARCHAR(MAX),
@Type_903ad94c3518 NVARCHAR(20),
@DefaultValue_903ad94c3518 NVARCHAR(MAX),
@IsRequired_903ad94c3518 BIT,
@LinkedParameterName_903ad94c3518 NVARCHAR(255),
@LinkedParameterField_903ad94c3518 NVARCHAR(500),
@ExtraFilter_903ad94c3518 NVARCHAR(MAX),
@EntityID_903ad94c3518 UNIQUEIDENTIFIER,
@RecordID_903ad94c3518 NVARCHAR(2000),
@OrderBy_903ad94c3518 NVARCHAR(MAX),
@TemplateContentID_903ad94c3518 UNIQUEIDENTIFIER,
@ID_903ad94c3518 UNIQUEIDENTIFIER
SET
  @TemplateID_903ad94c3518 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_903ad94c3518 = N'ValidationError'
SET
  @Description_903ad94c3518 = N'Error message indicating a failed previous attempt'
SET
  @Type_903ad94c3518 = N'Scalar'
SET
  @IsRequired_903ad94c3518 = 0
SET
  @ID_903ad94c3518 = '3E4F5A6B-7C8D-4E9F-0A1B-2C3D4E5F6071' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_903ad94c3518,
  @Name = @Name_903ad94c3518,
  @Description = @Description_903ad94c3518,
  @Type = @Type_903ad94c3518,
  @DefaultValue = @DefaultValue_903ad94c3518,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_903ad94c3518,
  @LinkedParameterName = @LinkedParameterName_903ad94c3518,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_903ad94c3518,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_903ad94c3518,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_903ad94c3518,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_903ad94c3518,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_903ad94c3518,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_903ad94c3518,
  @TemplateContentID_Clear = 1,
  @ID = @ID_903ad94c3518;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@Name_9f7b66ce5ee0 NVARCHAR(255),
@Description_9f7b66ce5ee0 NVARCHAR(MAX),
@Type_9f7b66ce5ee0 NVARCHAR(20),
@DefaultValue_9f7b66ce5ee0 NVARCHAR(MAX),
@IsRequired_9f7b66ce5ee0 BIT,
@LinkedParameterName_9f7b66ce5ee0 NVARCHAR(255),
@LinkedParameterField_9f7b66ce5ee0 NVARCHAR(500),
@ExtraFilter_9f7b66ce5ee0 NVARCHAR(MAX),
@EntityID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@RecordID_9f7b66ce5ee0 NVARCHAR(2000),
@OrderBy_9f7b66ce5ee0 NVARCHAR(MAX),
@TemplateContentID_9f7b66ce5ee0 UNIQUEIDENTIFIER,
@ID_9f7b66ce5ee0 UNIQUEIDENTIFIER
SET
  @TemplateID_9f7b66ce5ee0 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_9f7b66ce5ee0 = N'Brief'
SET
  @Description_9f7b66ce5ee0 = N'The natural-language description of the form to design.'
SET
  @Type_9f7b66ce5ee0 = N'Scalar'
SET
  @IsRequired_9f7b66ce5ee0 = 1
SET
  @ID_9f7b66ce5ee0 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E5F' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_9f7b66ce5ee0,
  @Name = @Name_9f7b66ce5ee0,
  @Description = @Description_9f7b66ce5ee0,
  @Type = @Type_9f7b66ce5ee0,
  @DefaultValue = @DefaultValue_9f7b66ce5ee0,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_9f7b66ce5ee0,
  @LinkedParameterName = @LinkedParameterName_9f7b66ce5ee0,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_9f7b66ce5ee0,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_9f7b66ce5ee0,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_9f7b66ce5ee0,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_9f7b66ce5ee0,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_9f7b66ce5ee0,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_9f7b66ce5ee0,
  @TemplateContentID_Clear = 1,
  @ID = @ID_9f7b66ce5ee0;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_e0380d77ac7c UNIQUEIDENTIFIER,
@Name_e0380d77ac7c NVARCHAR(255),
@Description_e0380d77ac7c NVARCHAR(MAX),
@Type_e0380d77ac7c NVARCHAR(20),
@DefaultValue_e0380d77ac7c NVARCHAR(MAX),
@IsRequired_e0380d77ac7c BIT,
@LinkedParameterName_e0380d77ac7c NVARCHAR(255),
@LinkedParameterField_e0380d77ac7c NVARCHAR(500),
@ExtraFilter_e0380d77ac7c NVARCHAR(MAX),
@EntityID_e0380d77ac7c UNIQUEIDENTIFIER,
@RecordID_e0380d77ac7c NVARCHAR(2000),
@OrderBy_e0380d77ac7c NVARCHAR(MAX),
@TemplateContentID_e0380d77ac7c UNIQUEIDENTIFIER,
@ID_e0380d77ac7c UNIQUEIDENTIFIER
SET
  @TemplateID_e0380d77ac7c = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_e0380d77ac7c = N'PreviousAttempt'
SET
  @Description_e0380d77ac7c = N'Optional: the model''s prior invalid output, fed back on a retry attempt.'
SET
  @Type_e0380d77ac7c = N'Scalar'
SET
  @IsRequired_e0380d77ac7c = 0
SET
  @ID_e0380d77ac7c = '2D3E4F5A-6B7C-4D8E-9F0A-1B2C3D4E5F60' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_e0380d77ac7c,
  @Name = @Name_e0380d77ac7c,
  @Description = @Description_e0380d77ac7c,
  @Type = @Type_e0380d77ac7c,
  @DefaultValue = @DefaultValue_e0380d77ac7c,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_e0380d77ac7c,
  @LinkedParameterName = @LinkedParameterName_e0380d77ac7c,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_e0380d77ac7c,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_e0380d77ac7c,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_e0380d77ac7c,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_e0380d77ac7c,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_e0380d77ac7c,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_e0380d77ac7c,
  @TemplateContentID_Clear = 1,
  @ID = @ID_e0380d77ac7c;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_903ad94c3518 UNIQUEIDENTIFIER,
@Name_903ad94c3518 NVARCHAR(255),
@Description_903ad94c3518 NVARCHAR(MAX),
@Type_903ad94c3518 NVARCHAR(20),
@DefaultValue_903ad94c3518 NVARCHAR(MAX),
@IsRequired_903ad94c3518 BIT,
@LinkedParameterName_903ad94c3518 NVARCHAR(255),
@LinkedParameterField_903ad94c3518 NVARCHAR(500),
@ExtraFilter_903ad94c3518 NVARCHAR(MAX),
@EntityID_903ad94c3518 UNIQUEIDENTIFIER,
@RecordID_903ad94c3518 NVARCHAR(2000),
@OrderBy_903ad94c3518 NVARCHAR(MAX),
@TemplateContentID_903ad94c3518 UNIQUEIDENTIFIER,
@ID_903ad94c3518 UNIQUEIDENTIFIER
SET
  @TemplateID_903ad94c3518 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F61'
SET
  @Name_903ad94c3518 = N'ValidationError'
SET
  @Description_903ad94c3518 = N'Optional: the blueprint validation error from the prior attempt, fed back on a retry.'
SET
  @Type_903ad94c3518 = N'Scalar'
SET
  @IsRequired_903ad94c3518 = 0
SET
  @ID_903ad94c3518 = '3E4F5A6B-7C8D-4E9F-0A1B-2C3D4E5F6071' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_903ad94c3518,
  @Name = @Name_903ad94c3518,
  @Description = @Description_903ad94c3518,
  @Type = @Type_903ad94c3518,
  @DefaultValue = @DefaultValue_903ad94c3518,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_903ad94c3518,
  @LinkedParameterName = @LinkedParameterName_903ad94c3518,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_903ad94c3518,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_903ad94c3518,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_903ad94c3518,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_903ad94c3518,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_903ad94c3518,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_903ad94c3518,
  @TemplateContentID_Clear = 1,
  @ID = @ID_903ad94c3518;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_ec4887a9a0ad UNIQUEIDENTIFIER,
@Name_ec4887a9a0ad NVARCHAR(255),
@Description_ec4887a9a0ad NVARCHAR(MAX),
@Type_ec4887a9a0ad NVARCHAR(20),
@DefaultValue_ec4887a9a0ad NVARCHAR(MAX),
@IsRequired_ec4887a9a0ad BIT,
@LinkedParameterName_ec4887a9a0ad NVARCHAR(255),
@LinkedParameterField_ec4887a9a0ad NVARCHAR(500),
@ExtraFilter_ec4887a9a0ad NVARCHAR(MAX),
@EntityID_ec4887a9a0ad UNIQUEIDENTIFIER,
@RecordID_ec4887a9a0ad NVARCHAR(2000),
@OrderBy_ec4887a9a0ad NVARCHAR(MAX),
@TemplateContentID_ec4887a9a0ad UNIQUEIDENTIFIER,
@ID_ec4887a9a0ad UNIQUEIDENTIFIER
SET
  @TemplateID_ec4887a9a0ad = 'F6A7B8C9-D0E1-4F2A-3B4C-5D6E7F809102'
SET
  @Name_ec4887a9a0ad = N'Answers'
SET
  @Description_ec4887a9a0ad = N'The free-text answers to analyze; an array of { questionPrompt, text } in the order they should be scored.'
SET
  @Type_ec4887a9a0ad = N'Scalar'
SET
  @IsRequired_ec4887a9a0ad = 1
SET
  @ID_ec4887a9a0ad = 'D4E5F6A7-B8C9-4D0E-1F2A-3B4C5D6E7F80' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_ec4887a9a0ad,
  @Name = @Name_ec4887a9a0ad,
  @Description = @Description_ec4887a9a0ad,
  @Type = @Type_ec4887a9a0ad,
  @DefaultValue = @DefaultValue_ec4887a9a0ad,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_ec4887a9a0ad,
  @LinkedParameterName = @LinkedParameterName_ec4887a9a0ad,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_ec4887a9a0ad,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_ec4887a9a0ad,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_ec4887a9a0ad,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_ec4887a9a0ad,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_ec4887a9a0ad,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_ec4887a9a0ad,
  @TemplateContentID_Clear = 1,
  @ID = @ID_ec4887a9a0ad;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_968e6b29cc06 UNIQUEIDENTIFIER,
@Name_968e6b29cc06 NVARCHAR(255),
@Description_968e6b29cc06 NVARCHAR(MAX),
@Type_968e6b29cc06 NVARCHAR(20),
@DefaultValue_968e6b29cc06 NVARCHAR(MAX),
@IsRequired_968e6b29cc06 BIT,
@LinkedParameterName_968e6b29cc06 NVARCHAR(255),
@LinkedParameterField_968e6b29cc06 NVARCHAR(500),
@ExtraFilter_968e6b29cc06 NVARCHAR(MAX),
@EntityID_968e6b29cc06 UNIQUEIDENTIFIER,
@RecordID_968e6b29cc06 NVARCHAR(2000),
@OrderBy_968e6b29cc06 NVARCHAR(MAX),
@TemplateContentID_968e6b29cc06 UNIQUEIDENTIFIER,
@ID_968e6b29cc06 UNIQUEIDENTIFIER
SET
  @TemplateID_968e6b29cc06 = 'F6A7B8C9-D0E1-4F2A-3B4C-5D6E7F809102'
SET
  @Name_968e6b29cc06 = N'FormContext'
SET
  @Description_968e6b29cc06 = N'Optional: the name/purpose of the form, to help the model judge relevance.'
SET
  @Type_968e6b29cc06 = N'Scalar'
SET
  @IsRequired_968e6b29cc06 = 0
SET
  @ID_968e6b29cc06 = 'E5F6A7B8-C9D0-4E1F-2A3B-4C5D6E7F8091' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_968e6b29cc06,
  @Name = @Name_968e6b29cc06,
  @Description = @Description_968e6b29cc06,
  @Type = @Type_968e6b29cc06,
  @DefaultValue = @DefaultValue_968e6b29cc06,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_968e6b29cc06,
  @LinkedParameterName = @LinkedParameterName_968e6b29cc06,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_968e6b29cc06,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_968e6b29cc06,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_968e6b29cc06,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_968e6b29cc06,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_968e6b29cc06,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_968e6b29cc06,
  @TemplateContentID_Clear = 1,
  @ID = @ID_968e6b29cc06;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_c9c04ad15183 UNIQUEIDENTIFIER,
@EntityID_c9c04ad15183 UNIQUEIDENTIFIER,
@Name_c9c04ad15183 NVARCHAR(100),
@Description_c9c04ad15183 NVARCHAR(MAX),
@CategoryID_c9c04ad15183 UNIQUEIDENTIFIER,
@IsShared_c9c04ad15183 BIT,
@IsDefault_c9c04ad15183 BIT,
@GridState_c9c04ad15183 NVARCHAR(MAX),
@FilterState_c9c04ad15183 NVARCHAR(MAX),
@CustomFilterState_c9c04ad15183 BIT,
@SmartFilterEnabled_c9c04ad15183 BIT,
@SmartFilterPrompt_c9c04ad15183 NVARCHAR(MAX),
@SmartFilterWhereClause_c9c04ad15183 NVARCHAR(MAX),
@SmartFilterExplanation_c9c04ad15183 NVARCHAR(MAX),
@WhereClause_c9c04ad15183 NVARCHAR(MAX),
@CustomWhereClause_c9c04ad15183 BIT,
@SortState_c9c04ad15183 NVARCHAR(MAX),
@Thumbnail_c9c04ad15183 NVARCHAR(MAX),
@CardState_c9c04ad15183 NVARCHAR(MAX),
@DisplayState_c9c04ad15183 NVARCHAR(MAX),
@ViewTypeID_c9c04ad15183 UNIQUEIDENTIFIER,
@ID_c9c04ad15183 UNIQUEIDENTIFIER
SET
  @UserID_c9c04ad15183 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_c9c04ad15183 = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_c9c04ad15183 = N'All Forms'
SET
  @Description_c9c04ad15183 = N''
SET
  @IsShared_c9c04ad15183 = 1
SET
  @IsDefault_c9c04ad15183 = 0
SET
  @GridState_c9c04ad15183 = N'{}'
SET
  @FilterState_c9c04ad15183 = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_c9c04ad15183 = 0
SET
  @SmartFilterEnabled_c9c04ad15183 = 0
SET
  @WhereClause_c9c04ad15183 = N''
SET
  @CustomWhereClause_c9c04ad15183 = 0
SET
  @ID_c9c04ad15183 = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_c9c04ad15183,
  @EntityID = @EntityID_c9c04ad15183,
  @Name = @Name_c9c04ad15183,
  @Description = @Description_c9c04ad15183,
  @CategoryID = @CategoryID_c9c04ad15183,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_c9c04ad15183,
  @IsDefault = @IsDefault_c9c04ad15183,
  @GridState = @GridState_c9c04ad15183,
  @FilterState = @FilterState_c9c04ad15183,
  @CustomFilterState = @CustomFilterState_c9c04ad15183,
  @SmartFilterEnabled = @SmartFilterEnabled_c9c04ad15183,
  @SmartFilterPrompt = @SmartFilterPrompt_c9c04ad15183,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_c9c04ad15183,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_c9c04ad15183,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_c9c04ad15183,
  @CustomWhereClause = @CustomWhereClause_c9c04ad15183,
  @SortState = @SortState_c9c04ad15183,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_c9c04ad15183,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_c9c04ad15183,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_c9c04ad15183,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_c9c04ad15183,
  @ViewTypeID_Clear = 1,
  @ID = @ID_c9c04ad15183;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_0ab19b01568e NVARCHAR(255),
@Description_0ab19b01568e NVARCHAR(MAX),
@AutoUpdateDescription_0ab19b01568e BIT,
@IsPrimaryKey_0ab19b01568e BIT,
@IsUnique_0ab19b01568e BIT,
@Category_0ab19b01568e NVARCHAR(255),
@ValueListType_0ab19b01568e NVARCHAR(20),
@ExtendedType_0ab19b01568e NVARCHAR(50),
@CodeType_0ab19b01568e NVARCHAR(50),
@DefaultInView_0ab19b01568e BIT,
@ViewCellTemplate_0ab19b01568e NVARCHAR(MAX),
@DefaultColumnWidth_0ab19b01568e INT,
@AllowUpdateAPI_0ab19b01568e BIT,
@AllowUpdateInView_0ab19b01568e BIT,
@IncludeInUserSearchAPI_0ab19b01568e BIT,
@FullTextSearchEnabled_0ab19b01568e BIT,
@UserSearchParamFormatAPI_0ab19b01568e NVARCHAR(500),
@IncludeInGeneratedForm_0ab19b01568e BIT,
@GeneratedFormSection_0ab19b01568e NVARCHAR(10),
@IsNameField_0ab19b01568e BIT,
@RelatedEntityID_0ab19b01568e UNIQUEIDENTIFIER,
@RelatedEntityFieldName_0ab19b01568e NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_0ab19b01568e BIT,
@RelatedEntityNameFieldMap_0ab19b01568e NVARCHAR(255),
@RelatedEntityDisplayType_0ab19b01568e NVARCHAR(20),
@EntityIDFieldName_0ab19b01568e NVARCHAR(100),
@ScopeDefault_0ab19b01568e NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_0ab19b01568e BIT,
@ValuesToPackWithSchema_0ab19b01568e NVARCHAR(10),
@Status_0ab19b01568e NVARCHAR(25),
@AutoUpdateIsNameField_0ab19b01568e BIT,
@AutoUpdateDefaultInView_0ab19b01568e BIT,
@AutoUpdateCategory_0ab19b01568e BIT,
@AutoUpdateDisplayName_0ab19b01568e BIT,
@AutoUpdateIncludeInUserSearchAPI_0ab19b01568e BIT,
@Encrypt_0ab19b01568e BIT,
@EncryptionKeyID_0ab19b01568e UNIQUEIDENTIFIER,
@AllowDecryptInAPI_0ab19b01568e BIT,
@SendEncryptedValue_0ab19b01568e BIT,
@IsSoftPrimaryKey_0ab19b01568e BIT,
@IsSoftForeignKey_0ab19b01568e BIT,
@RelatedEntityJoinFields_0ab19b01568e NVARCHAR(MAX),
@JSONType_0ab19b01568e NVARCHAR(255),
@JSONTypeIsArray_0ab19b01568e BIT,
@JSONTypeDefinition_0ab19b01568e NVARCHAR(MAX),
@UserSearchPredicateAPI_0ab19b01568e NVARCHAR(20),
@AutoUpdateUserSearchPredicate_0ab19b01568e BIT,
@AutoUpdateFullTextSearch_0ab19b01568e BIT,
@AutoUpdateExtendedType_0ab19b01568e BIT,
@IsComputed_0ab19b01568e BIT,
@EmbeddedRecord_0ab19b01568e NVARCHAR(MAX),
@Configuration_0ab19b01568e NVARCHAR(MAX),
@ID_0ab19b01568e UNIQUEIDENTIFIER
SET
  @DisplayName_0ab19b01568e = N'Parent'
SET
  @AutoUpdateDescription_0ab19b01568e = 1
SET
  @IsPrimaryKey_0ab19b01568e = 0
SET
  @IsUnique_0ab19b01568e = 0
SET
  @Category_0ab19b01568e = N'Hierarchy and Sorting'
SET
  @ValueListType_0ab19b01568e = N'None'
SET
  @DefaultInView_0ab19b01568e = 0
SET
  @DefaultColumnWidth_0ab19b01568e = 150
SET
  @AllowUpdateAPI_0ab19b01568e = 1
SET
  @AllowUpdateInView_0ab19b01568e = 1
SET
  @IncludeInUserSearchAPI_0ab19b01568e = 0
SET
  @FullTextSearchEnabled_0ab19b01568e = 0
SET
  @IncludeInGeneratedForm_0ab19b01568e = 1
SET
  @GeneratedFormSection_0ab19b01568e = N'Category'
SET
  @IsNameField_0ab19b01568e = 0
SET
  @RelatedEntityID_0ab19b01568e = '43ECBEA3-6CFC-480C-823F-96B5DB201FE7'
SET
  @RelatedEntityFieldName_0ab19b01568e = N'ID'
SET
  @IncludeRelatedEntityNameFieldInBaseView_0ab19b01568e = 1
SET
  @RelatedEntityNameFieldMap_0ab19b01568e = N'Parent'
SET
  @RelatedEntityDisplayType_0ab19b01568e = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_0ab19b01568e = 1
SET
  @ValuesToPackWithSchema_0ab19b01568e = N'Auto'
SET
  @Status_0ab19b01568e = N'Active'
SET
  @AutoUpdateIsNameField_0ab19b01568e = 1
SET
  @AutoUpdateDefaultInView_0ab19b01568e = 1
SET
  @AutoUpdateCategory_0ab19b01568e = 1
SET
  @AutoUpdateDisplayName_0ab19b01568e = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_0ab19b01568e = 1
SET
  @Encrypt_0ab19b01568e = 0
SET
  @AllowDecryptInAPI_0ab19b01568e = 0
SET
  @SendEncryptedValue_0ab19b01568e = 0
SET
  @IsSoftPrimaryKey_0ab19b01568e = 0
SET
  @IsSoftForeignKey_0ab19b01568e = 0
SET
  @JSONTypeIsArray_0ab19b01568e = 0
SET
  @UserSearchPredicateAPI_0ab19b01568e = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_0ab19b01568e = 1
SET
  @AutoUpdateFullTextSearch_0ab19b01568e = 1
SET
  @AutoUpdateExtendedType_0ab19b01568e = 1
SET
  @IsComputed_0ab19b01568e = 0
SET
  @Configuration_0ab19b01568e = N'{
  "Hierarchy": {
    "IsHierarchy": true
  }
}'
SET
  @ID_0ab19b01568e = 'BFEC1DE7-95E3-4C68-841E-80402093EADE' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_0ab19b01568e,
  @Description = @Description_0ab19b01568e,
  @Description_Clear = 1,
  @AutoUpdateDescription = @AutoUpdateDescription_0ab19b01568e,
  @IsPrimaryKey = @IsPrimaryKey_0ab19b01568e,
  @IsUnique = @IsUnique_0ab19b01568e,
  @Category = @Category_0ab19b01568e,
  @ValueListType = @ValueListType_0ab19b01568e,
  @ExtendedType = @ExtendedType_0ab19b01568e,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_0ab19b01568e,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_0ab19b01568e,
  @ViewCellTemplate = @ViewCellTemplate_0ab19b01568e,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_0ab19b01568e,
  @AllowUpdateAPI = @AllowUpdateAPI_0ab19b01568e,
  @AllowUpdateInView = @AllowUpdateInView_0ab19b01568e,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_0ab19b01568e,
  @FullTextSearchEnabled = @FullTextSearchEnabled_0ab19b01568e,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_0ab19b01568e,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_0ab19b01568e,
  @GeneratedFormSection = @GeneratedFormSection_0ab19b01568e,
  @IsNameField = @IsNameField_0ab19b01568e,
  @RelatedEntityID = @RelatedEntityID_0ab19b01568e,
  @RelatedEntityFieldName = @RelatedEntityFieldName_0ab19b01568e,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_0ab19b01568e,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_0ab19b01568e,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_0ab19b01568e,
  @EntityIDFieldName = @EntityIDFieldName_0ab19b01568e,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_0ab19b01568e,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_0ab19b01568e,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_0ab19b01568e,
  @Status = @Status_0ab19b01568e,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_0ab19b01568e,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_0ab19b01568e,
  @AutoUpdateCategory = @AutoUpdateCategory_0ab19b01568e,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_0ab19b01568e,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_0ab19b01568e,
  @Encrypt = @Encrypt_0ab19b01568e,
  @EncryptionKeyID = @EncryptionKeyID_0ab19b01568e,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_0ab19b01568e,
  @SendEncryptedValue = @SendEncryptedValue_0ab19b01568e,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_0ab19b01568e,
  @IsSoftForeignKey = @IsSoftForeignKey_0ab19b01568e,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_0ab19b01568e,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_0ab19b01568e,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_0ab19b01568e,
  @JSONTypeDefinition = @JSONTypeDefinition_0ab19b01568e,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_0ab19b01568e,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_0ab19b01568e,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_0ab19b01568e,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_0ab19b01568e,
  @IsComputed = @IsComputed_0ab19b01568e,
  @EmbeddedRecord = @EmbeddedRecord_0ab19b01568e,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_0ab19b01568e,
  @ID = @ID_0ab19b01568e;

GO

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_8bee9e00b9b4 NVARCHAR(255),
@Description_8bee9e00b9b4 NVARCHAR(MAX),
@AutoUpdateDescription_8bee9e00b9b4 BIT,
@IsPrimaryKey_8bee9e00b9b4 BIT,
@IsUnique_8bee9e00b9b4 BIT,
@Category_8bee9e00b9b4 NVARCHAR(255),
@ValueListType_8bee9e00b9b4 NVARCHAR(20),
@ExtendedType_8bee9e00b9b4 NVARCHAR(50),
@CodeType_8bee9e00b9b4 NVARCHAR(50),
@DefaultInView_8bee9e00b9b4 BIT,
@ViewCellTemplate_8bee9e00b9b4 NVARCHAR(MAX),
@DefaultColumnWidth_8bee9e00b9b4 INT,
@AllowUpdateAPI_8bee9e00b9b4 BIT,
@AllowUpdateInView_8bee9e00b9b4 BIT,
@IncludeInUserSearchAPI_8bee9e00b9b4 BIT,
@FullTextSearchEnabled_8bee9e00b9b4 BIT,
@UserSearchParamFormatAPI_8bee9e00b9b4 NVARCHAR(500),
@IncludeInGeneratedForm_8bee9e00b9b4 BIT,
@GeneratedFormSection_8bee9e00b9b4 NVARCHAR(10),
@IsNameField_8bee9e00b9b4 BIT,
@RelatedEntityID_8bee9e00b9b4 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_8bee9e00b9b4 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_8bee9e00b9b4 BIT,
@RelatedEntityNameFieldMap_8bee9e00b9b4 NVARCHAR(255),
@RelatedEntityDisplayType_8bee9e00b9b4 NVARCHAR(20),
@EntityIDFieldName_8bee9e00b9b4 NVARCHAR(100),
@ScopeDefault_8bee9e00b9b4 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_8bee9e00b9b4 BIT,
@ValuesToPackWithSchema_8bee9e00b9b4 NVARCHAR(10),
@Status_8bee9e00b9b4 NVARCHAR(25),
@AutoUpdateIsNameField_8bee9e00b9b4 BIT,
@AutoUpdateDefaultInView_8bee9e00b9b4 BIT,
@AutoUpdateCategory_8bee9e00b9b4 BIT,
@AutoUpdateDisplayName_8bee9e00b9b4 BIT,
@AutoUpdateIncludeInUserSearchAPI_8bee9e00b9b4 BIT,
@Encrypt_8bee9e00b9b4 BIT,
@EncryptionKeyID_8bee9e00b9b4 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_8bee9e00b9b4 BIT,
@SendEncryptedValue_8bee9e00b9b4 BIT,
@IsSoftPrimaryKey_8bee9e00b9b4 BIT,
@IsSoftForeignKey_8bee9e00b9b4 BIT,
@RelatedEntityJoinFields_8bee9e00b9b4 NVARCHAR(MAX),
@JSONType_8bee9e00b9b4 NVARCHAR(255),
@JSONTypeIsArray_8bee9e00b9b4 BIT,
@JSONTypeDefinition_8bee9e00b9b4 NVARCHAR(MAX),
@UserSearchPredicateAPI_8bee9e00b9b4 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_8bee9e00b9b4 BIT,
@AutoUpdateFullTextSearch_8bee9e00b9b4 BIT,
@AutoUpdateExtendedType_8bee9e00b9b4 BIT,
@IsComputed_8bee9e00b9b4 BIT,
@EmbeddedRecord_8bee9e00b9b4 NVARCHAR(MAX),
@Configuration_8bee9e00b9b4 NVARCHAR(MAX),
@ID_8bee9e00b9b4 UNIQUEIDENTIFIER
SET
  @DisplayName_8bee9e00b9b4 = N'Template Source Form'
SET
  @Description_8bee9e00b9b4 = N'On a template row (IsTemplate = 1), the Form this template was saved from — what lets the builder show "Saved" instead of offering to save the same form twice. Never set on forms CREATED from a template: those are independent deep copies that diverge immediately, and a link would wrongly imply edits propagate. Null means the template has no living source'
SET
  @AutoUpdateDescription_8bee9e00b9b4 = 1
SET
  @IsPrimaryKey_8bee9e00b9b4 = 0
SET
  @IsUnique_8bee9e00b9b4 = 0
SET
  @Category_8bee9e00b9b4 = N'Form Information'
SET
  @ValueListType_8bee9e00b9b4 = N'None'
SET
  @DefaultInView_8bee9e00b9b4 = 0
SET
  @DefaultColumnWidth_8bee9e00b9b4 = 150
SET
  @AllowUpdateAPI_8bee9e00b9b4 = 1
SET
  @AllowUpdateInView_8bee9e00b9b4 = 1
SET
  @IncludeInUserSearchAPI_8bee9e00b9b4 = 0
SET
  @FullTextSearchEnabled_8bee9e00b9b4 = 0
SET
  @IncludeInGeneratedForm_8bee9e00b9b4 = 1
SET
  @GeneratedFormSection_8bee9e00b9b4 = N'Category'
SET
  @IsNameField_8bee9e00b9b4 = 0
SET
  @RelatedEntityID_8bee9e00b9b4 = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @RelatedEntityFieldName_8bee9e00b9b4 = N'ID'
SET
  @IncludeRelatedEntityNameFieldInBaseView_8bee9e00b9b4 = 1
SET
  @RelatedEntityNameFieldMap_8bee9e00b9b4 = N'TemplateSourceForm'
SET
  @RelatedEntityDisplayType_8bee9e00b9b4 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_8bee9e00b9b4 = 1
SET
  @ValuesToPackWithSchema_8bee9e00b9b4 = N'Auto'
SET
  @Status_8bee9e00b9b4 = N'Active'
SET
  @AutoUpdateIsNameField_8bee9e00b9b4 = 1
SET
  @AutoUpdateDefaultInView_8bee9e00b9b4 = 1
SET
  @AutoUpdateCategory_8bee9e00b9b4 = 1
SET
  @AutoUpdateDisplayName_8bee9e00b9b4 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_8bee9e00b9b4 = 1
SET
  @Encrypt_8bee9e00b9b4 = 0
SET
  @AllowDecryptInAPI_8bee9e00b9b4 = 0
SET
  @SendEncryptedValue_8bee9e00b9b4 = 0
SET
  @IsSoftPrimaryKey_8bee9e00b9b4 = 0
SET
  @IsSoftForeignKey_8bee9e00b9b4 = 0
SET
  @JSONTypeIsArray_8bee9e00b9b4 = 0
SET
  @UserSearchPredicateAPI_8bee9e00b9b4 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_8bee9e00b9b4 = 1
SET
  @AutoUpdateFullTextSearch_8bee9e00b9b4 = 1
SET
  @AutoUpdateExtendedType_8bee9e00b9b4 = 1
SET
  @IsComputed_8bee9e00b9b4 = 0
SET
  @Configuration_8bee9e00b9b4 = N'{
  "Hierarchy": {
    "IsHierarchy": false
  }
}'
SET
  @ID_8bee9e00b9b4 = '26476755-BAE0-4A03-B6C3-79857C530D6F' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_8bee9e00b9b4,
  @Description = @Description_8bee9e00b9b4,
  @AutoUpdateDescription = @AutoUpdateDescription_8bee9e00b9b4,
  @IsPrimaryKey = @IsPrimaryKey_8bee9e00b9b4,
  @IsUnique = @IsUnique_8bee9e00b9b4,
  @Category = @Category_8bee9e00b9b4,
  @ValueListType = @ValueListType_8bee9e00b9b4,
  @ExtendedType = @ExtendedType_8bee9e00b9b4,
  @ExtendedType_Clear = 1,
  @CodeType = @CodeType_8bee9e00b9b4,
  @CodeType_Clear = 1,
  @DefaultInView = @DefaultInView_8bee9e00b9b4,
  @ViewCellTemplate = @ViewCellTemplate_8bee9e00b9b4,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_8bee9e00b9b4,
  @AllowUpdateAPI = @AllowUpdateAPI_8bee9e00b9b4,
  @AllowUpdateInView = @AllowUpdateInView_8bee9e00b9b4,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_8bee9e00b9b4,
  @FullTextSearchEnabled = @FullTextSearchEnabled_8bee9e00b9b4,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_8bee9e00b9b4,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_8bee9e00b9b4,
  @GeneratedFormSection = @GeneratedFormSection_8bee9e00b9b4,
  @IsNameField = @IsNameField_8bee9e00b9b4,
  @RelatedEntityID = @RelatedEntityID_8bee9e00b9b4,
  @RelatedEntityFieldName = @RelatedEntityFieldName_8bee9e00b9b4,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_8bee9e00b9b4,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_8bee9e00b9b4,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_8bee9e00b9b4,
  @EntityIDFieldName = @EntityIDFieldName_8bee9e00b9b4,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_8bee9e00b9b4,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_8bee9e00b9b4,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_8bee9e00b9b4,
  @Status = @Status_8bee9e00b9b4,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_8bee9e00b9b4,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_8bee9e00b9b4,
  @AutoUpdateCategory = @AutoUpdateCategory_8bee9e00b9b4,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_8bee9e00b9b4,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_8bee9e00b9b4,
  @Encrypt = @Encrypt_8bee9e00b9b4,
  @EncryptionKeyID = @EncryptionKeyID_8bee9e00b9b4,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_8bee9e00b9b4,
  @SendEncryptedValue = @SendEncryptedValue_8bee9e00b9b4,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_8bee9e00b9b4,
  @IsSoftForeignKey = @IsSoftForeignKey_8bee9e00b9b4,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_8bee9e00b9b4,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_8bee9e00b9b4,
  @JSONType_Clear = 1,
  @JSONTypeIsArray = @JSONTypeIsArray_8bee9e00b9b4,
  @JSONTypeDefinition = @JSONTypeDefinition_8bee9e00b9b4,
  @JSONTypeDefinition_Clear = 1,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_8bee9e00b9b4,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_8bee9e00b9b4,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_8bee9e00b9b4,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_8bee9e00b9b4,
  @IsComputed = @IsComputed_8bee9e00b9b4,
  @EmbeddedRecord = @EmbeddedRecord_8bee9e00b9b4,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_8bee9e00b9b4,
  @ID = @ID_8bee9e00b9b4;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_ebe73b0506b1 UNIQUEIDENTIFIER,
@ActionID_ebe73b0506b1 UNIQUEIDENTIFIER,
@Name_ebe73b0506b1 NVARCHAR(255),
@DefaultValue_ebe73b0506b1 NVARCHAR(MAX),
@Type_ebe73b0506b1 NCHAR(10),
@ValueType_ebe73b0506b1 NVARCHAR(30),
@IsArray_ebe73b0506b1 BIT,
@Description_ebe73b0506b1 NVARCHAR(MAX),
@IsRequired_ebe73b0506b1 BIT,
@MediaModality_ebe73b0506b1 NVARCHAR(20),
@LogValue_ebe73b0506b1 BIT
SET
  @ID_ebe73b0506b1 = '7F0B0002-A1B2-4C3D-8E4F-000000000005'
SET
  @ActionID_ebe73b0506b1 = '7F0A0002-A1B2-4C3D-8E4F-000000000002'
SET
  @Name_ebe73b0506b1 = N'OnSubmitMode'
SET
  @Type_ebe73b0506b1 = N'Input'
SET
  @ValueType_ebe73b0506b1 = N'Scalar'
SET
  @IsArray_ebe73b0506b1 = 0
SET
  @Description_ebe73b0506b1 = N'Whether this form''s own automations are what run on submit (''Legacy'' or ''Configured''). ''Configured'' with no Automations is the supported way to run NOTHING - how a caller that owns its own subject identity declines Forms: Upsert Respondent Person. Omit to keep the historical behaviour.'
SET
  @IsRequired_ebe73b0506b1 = 0
SET
  @LogValue_ebe73b0506b1 = 1
IF EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
           WHERE ID = @ID_ebe73b0506b1 AND NOT (ActionID = @ActionID_ebe73b0506b1 AND Name = @Name_ebe73b0506b1))
BEGIN
    RAISERROR(N'V202609112116: ActionParam id 7F0B0002-A1B2-4C3D-8E4F-000000000005 is already held by a different record, so "OnSubmitMode" cannot be created with it. Pick a free id in the 7F0B space and update migrations/ and metadata/actions/.actions.json together.', 16, 1);
END
ELSE IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
                    WHERE ActionID = @ActionID_ebe73b0506b1 AND Name = @Name_ebe73b0506b1)
BEGIN
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_ebe73b0506b1,
  @ActionID = @ActionID_ebe73b0506b1,
  @Name = @Name_ebe73b0506b1,
  @DefaultValue = @DefaultValue_ebe73b0506b1,
  @DefaultValue_Clear = 1,
  @Type = @Type_ebe73b0506b1,
  @ValueType = @ValueType_ebe73b0506b1,
  @IsArray = @IsArray_ebe73b0506b1,
  @Description = @Description_ebe73b0506b1,
  @IsRequired = @IsRequired_ebe73b0506b1,
  @MediaModality = @MediaModality_ebe73b0506b1,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_ebe73b0506b1;
END

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_84e118df637b UNIQUEIDENTIFIER,
@ActionID_84e118df637b UNIQUEIDENTIFIER,
@Name_84e118df637b NVARCHAR(255),
@DefaultValue_84e118df637b NVARCHAR(MAX),
@Type_84e118df637b NCHAR(10),
@ValueType_84e118df637b NVARCHAR(30),
@IsArray_84e118df637b BIT,
@Description_84e118df637b NVARCHAR(MAX),
@IsRequired_84e118df637b BIT,
@MediaModality_84e118df637b NVARCHAR(20),
@LogValue_84e118df637b BIT
SET
  @ID_84e118df637b = '7F0B0001-A1B2-4C3D-8E4F-000000000005'
SET
  @ActionID_84e118df637b = '7F0A0001-A1B2-4C3D-8E4F-000000000001'
SET
  @Name_84e118df637b = N'OnSubmitMode'
SET
  @Type_84e118df637b = N'Input'
SET
  @ValueType_84e118df637b = N'Scalar'
SET
  @IsArray_84e118df637b = 0
SET
  @Description_84e118df637b = N'Whether this form''s own automations are what run on submit (''Legacy'' or ''Configured''). ''Configured'' with no Automations is the supported way to run NOTHING - how a caller that owns its own subject identity declines Forms: Upsert Respondent Person. Omit to keep the historical behaviour.'
SET
  @IsRequired_84e118df637b = 0
SET
  @LogValue_84e118df637b = 1
IF EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
           WHERE ID = @ID_84e118df637b AND NOT (ActionID = @ActionID_84e118df637b AND Name = @Name_84e118df637b))
BEGIN
    RAISERROR(N'V202609112116: ActionParam id 7F0B0001-A1B2-4C3D-8E4F-000000000005 is already held by a different record, so "OnSubmitMode" cannot be created with it. Pick a free id in the 7F0B space and update migrations/ and metadata/actions/.actions.json together.', 16, 1);
END
ELSE IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
                    WHERE ActionID = @ActionID_84e118df637b AND Name = @Name_84e118df637b)
BEGIN
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_84e118df637b,
  @ActionID = @ActionID_84e118df637b,
  @Name = @Name_84e118df637b,
  @DefaultValue = @DefaultValue_84e118df637b,
  @DefaultValue_Clear = 1,
  @Type = @Type_84e118df637b,
  @ValueType = @ValueType_84e118df637b,
  @IsArray = @IsArray_84e118df637b,
  @Description = @Description_84e118df637b,
  @IsRequired = @IsRequired_84e118df637b,
  @MediaModality = @MediaModality_84e118df637b,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_84e118df637b;
END

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_25b473027c71 UNIQUEIDENTIFIER,
@ActionID_25b473027c71 UNIQUEIDENTIFIER,
@Name_25b473027c71 NVARCHAR(255),
@DefaultValue_25b473027c71 NVARCHAR(MAX),
@Type_25b473027c71 NCHAR(10),
@ValueType_25b473027c71 NVARCHAR(30),
@IsArray_25b473027c71 BIT,
@Description_25b473027c71 NVARCHAR(MAX),
@IsRequired_25b473027c71 BIT,
@MediaModality_25b473027c71 NVARCHAR(20),
@LogValue_25b473027c71 BIT
SET
  @ID_25b473027c71 = '7F0B0001-A1B2-4C3D-8E4F-000000000006'
SET
  @ActionID_25b473027c71 = '7F0A0001-A1B2-4C3D-8E4F-000000000001'
SET
  @Name_25b473027c71 = N'Automations'
SET
  @Type_25b473027c71 = N'Input'
SET
  @ValueType_25b473027c71 = N'Simple Object'
SET
  @IsArray_25b473027c71 = 1
SET
  @Description_25b473027c71 = N'The on-submit steps this form runs, in order, each naming an MJ Action (for example [{"actionName":"Forms: Send Confirmation Email"}]). Supplying this implies OnSubmitMode=''Configured'', and supplying it alongside ''Legacy'' is an error rather than a silently ignored list. An Action name this deployment does not have is an error, not a skipped step.'
SET
  @IsRequired_25b473027c71 = 0
SET
  @LogValue_25b473027c71 = 1
IF EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
           WHERE ID = @ID_25b473027c71 AND NOT (ActionID = @ActionID_25b473027c71 AND Name = @Name_25b473027c71))
BEGIN
    RAISERROR(N'V202609112116: ActionParam id 7F0B0001-A1B2-4C3D-8E4F-000000000006 is already held by a different record, so "Automations" cannot be created with it. Pick a free id in the 7F0B space and update migrations/ and metadata/actions/.actions.json together.', 16, 1);
END
ELSE IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
                    WHERE ActionID = @ActionID_25b473027c71 AND Name = @Name_25b473027c71)
BEGIN
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_25b473027c71,
  @ActionID = @ActionID_25b473027c71,
  @Name = @Name_25b473027c71,
  @DefaultValue = @DefaultValue_25b473027c71,
  @DefaultValue_Clear = 1,
  @Type = @Type_25b473027c71,
  @ValueType = @ValueType_25b473027c71,
  @IsArray = @IsArray_25b473027c71,
  @Description = @Description_25b473027c71,
  @IsRequired = @IsRequired_25b473027c71,
  @MediaModality = @MediaModality_25b473027c71,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_25b473027c71;
END

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_0778d8fdad57 UNIQUEIDENTIFIER,
@ActionID_0778d8fdad57 UNIQUEIDENTIFIER,
@Name_0778d8fdad57 NVARCHAR(255),
@DefaultValue_0778d8fdad57 NVARCHAR(MAX),
@Type_0778d8fdad57 NCHAR(10),
@ValueType_0778d8fdad57 NVARCHAR(30),
@IsArray_0778d8fdad57 BIT,
@Description_0778d8fdad57 NVARCHAR(MAX),
@IsRequired_0778d8fdad57 BIT,
@MediaModality_0778d8fdad57 NVARCHAR(20),
@LogValue_0778d8fdad57 BIT
SET
  @ID_0778d8fdad57 = '7F0B0002-A1B2-4C3D-8E4F-000000000006'
SET
  @ActionID_0778d8fdad57 = '7F0A0002-A1B2-4C3D-8E4F-000000000002'
SET
  @Name_0778d8fdad57 = N'Automations'
SET
  @Type_0778d8fdad57 = N'Input'
SET
  @ValueType_0778d8fdad57 = N'Simple Object'
SET
  @IsArray_0778d8fdad57 = 1
SET
  @Description_0778d8fdad57 = N'The on-submit steps this form runs, in order, each naming an MJ Action (for example [{"actionName":"Forms: Send Confirmation Email"}]). Supplying this implies OnSubmitMode=''Configured'', and supplying it alongside ''Legacy'' is an error rather than a silently ignored list. An Action name this deployment does not have is an error, not a skipped step.'
SET
  @IsRequired_0778d8fdad57 = 0
SET
  @LogValue_0778d8fdad57 = 1
IF EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
           WHERE ID = @ID_0778d8fdad57 AND NOT (ActionID = @ActionID_0778d8fdad57 AND Name = @Name_0778d8fdad57))
BEGIN
    RAISERROR(N'V202609112116: ActionParam id 7F0B0002-A1B2-4C3D-8E4F-000000000006 is already held by a different record, so "Automations" cannot be created with it. Pick a free id in the 7F0B space and update migrations/ and metadata/actions/.actions.json together.', 16, 1);
END
ELSE IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[ActionParam]
                    WHERE ActionID = @ActionID_0778d8fdad57 AND Name = @Name_0778d8fdad57)
BEGIN
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_0778d8fdad57,
  @ActionID = @ActionID_0778d8fdad57,
  @Name = @Name_0778d8fdad57,
  @DefaultValue = @DefaultValue_0778d8fdad57,
  @DefaultValue_Clear = 1,
  @Type = @Type_0778d8fdad57,
  @ValueType = @ValueType_0778d8fdad57,
  @IsArray = @IsArray_0778d8fdad57,
  @Description = @Description_0778d8fdad57,
  @IsRequired = @IsRequired_0778d8fdad57,
  @MediaModality = @MediaModality_0778d8fdad57,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_0778d8fdad57;
END

GO


-- End of SQL Logging Session
-- Session ID: 1ef16a78-e3ad-4da2-9bcc-cc313f0ed185
-- Completed: 2026-09-12T03:02:33.987Z
-- Duration: 12987ms
-- Total Statements: 17
