-- ---------------------------------------------------------------------------------------------
-- Metadata seed delta: the authoring chat.
--
-- WHAT THIS CARRIES
--   * 'Forms: Chat' — the action behind the "Chat to create" box, with its four params (Message,
--     FormID, ConversationID, SessionID). Resolved BY NAME from the client, so the name is a
--     contract and not an implementation detail.
--   * 'Forms: Chat Assistant' — the prompt, its template, its five template params and a pinned
--     model row. It replies AND declares an action (none / create / restyle / unsupported) which
--     deterministic code then performs; the model never touches the database, the same split the
--     rest of the authoring pipeline uses.
--
-- WHY ITS VALIDATION IS LENIENT WHERE THE AUTHORING PROMPTS' IS STRICT. `ValidationBehavior` is
-- 'None' and MaxRetries is 1. An authoring prompt that returns a malformed blueprint has produced
-- nothing usable and should retry; a chat reply that misses an optional field is still an answer,
-- and `parseFormChatResponse` degrades it to plain text. Retrying there would make the author wait
-- three times over for a message they could already read.
--
-- NO NEW TABLES. Turns persist in MJ's own `MJ: Conversations` / `MJ: Conversation Details`, which
-- already model a per-user thread of User / AI / Error messages. `ExternalID` scopes a thread to a
-- form, so the conversation an author leaves on one form is there when they return to it and does
-- not follow them elsewhere. A Forms-owned chat table would have needed a migration, a CodeGen run
-- and its own history semantics to arrive at the same shape.
--
-- Generated the same way as its predecessors: pushed against MJ_Install_Rehearsal, restored from a
-- pre-feature backup and brought to head through the SHIPPED CHAIN, 0 Form rows throughout. Every
-- `${flyway:defaultSchema}` became `${mjSchema}` — all calls here are CORE procedures. No
-- Forms-schema SP calls and no Form Respondent permission records, so #41's watershed is untouched.
-- ---------------------------------------------------------------------------------------------

-- SQL Logging Session
-- Session ID: 3bfc8da7-6b5e-41fb-9421-d37aba39e808
-- Started: 2026-08-20T23:01:03.930Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Templates (core SP call only)
DECLARE @ID_8deb547f UNIQUEIDENTIFIER,
@Name_8deb547f NVARCHAR(255),
@Description_8deb547f NVARCHAR(MAX),
@CategoryID_8deb547f UNIQUEIDENTIFIER,
@UserPrompt_8deb547f NVARCHAR(MAX),
@UserID_8deb547f UNIQUEIDENTIFIER,
@ActiveAt_8deb547f DATETIMEOFFSET,
@DisabledAt_8deb547f DATETIMEOFFSET,
@IsActive_8deb547f BIT
SET
  @ID_8deb547f = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_8deb547f = N'MJ_BizApps_Forms: Chat Assistant'
SET
  @Description_8deb547f = N'The authoring chat. Given the conversation so far, the form on screen and the author''s new message, replies and declares what should be done about it: nothing, create a form, restyle the open one, or say plainly that the change is not supported yet.'
SET
  @UserID_8deb547f = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @IsActive_8deb547f = 1
EXEC [${mjSchema}].spCreateTemplate @ID = @ID_8deb547f,
  @Name = @Name_8deb547f,
  @Description = @Description_8deb547f,
  @CategoryID = @CategoryID_8deb547f,
  @CategoryID_Clear = 1,
  @UserPrompt = @UserPrompt_8deb547f,
  @UserPrompt_Clear = 1,
  @UserID = @UserID_8deb547f,
  @ActiveAt = @ActiveAt_8deb547f,
  @ActiveAt_Clear = 1,
  @DisabledAt = @DisabledAt_8deb547f,
  @DisabledAt_Clear = 1,
  @IsActive = @IsActive_8deb547f;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_35c69e9b UNIQUEIDENTIFIER,
@TemplateID_35c69e9b UNIQUEIDENTIFIER,
@Name_35c69e9b NVARCHAR(255),
@Description_35c69e9b NVARCHAR(MAX),
@Type_35c69e9b NVARCHAR(20),
@DefaultValue_35c69e9b NVARCHAR(MAX),
@IsRequired_35c69e9b BIT,
@LinkedParameterName_35c69e9b NVARCHAR(255),
@LinkedParameterField_35c69e9b NVARCHAR(500),
@ExtraFilter_35c69e9b NVARCHAR(MAX),
@EntityID_35c69e9b UNIQUEIDENTIFIER,
@RecordID_35c69e9b NVARCHAR(2000),
@OrderBy_35c69e9b NVARCHAR(MAX),
@TemplateContentID_35c69e9b UNIQUEIDENTIFIER
SET
  @ID_35c69e9b = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90'
SET
  @TemplateID_35c69e9b = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_35c69e9b = N'Message'
SET
  @Description_35c69e9b = N'What the author just typed.'
SET
  @Type_35c69e9b = N'Scalar'
SET
  @IsRequired_35c69e9b = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_35c69e9b,
  @TemplateID = @TemplateID_35c69e9b,
  @Name = @Name_35c69e9b,
  @Description = @Description_35c69e9b,
  @Type = @Type_35c69e9b,
  @DefaultValue = @DefaultValue_35c69e9b,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_35c69e9b,
  @LinkedParameterName = @LinkedParameterName_35c69e9b,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_35c69e9b,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_35c69e9b,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_35c69e9b,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_35c69e9b,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_35c69e9b,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_35c69e9b,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_a5ad7c84 UNIQUEIDENTIFIER,
@TemplateID_a5ad7c84 UNIQUEIDENTIFIER,
@Name_a5ad7c84 NVARCHAR(255),
@Description_a5ad7c84 NVARCHAR(MAX),
@Type_a5ad7c84 NVARCHAR(20),
@DefaultValue_a5ad7c84 NVARCHAR(MAX),
@IsRequired_a5ad7c84 BIT,
@LinkedParameterName_a5ad7c84 NVARCHAR(255),
@LinkedParameterField_a5ad7c84 NVARCHAR(500),
@ExtraFilter_a5ad7c84 NVARCHAR(MAX),
@EntityID_a5ad7c84 UNIQUEIDENTIFIER,
@RecordID_a5ad7c84 NVARCHAR(2000),
@OrderBy_a5ad7c84 NVARCHAR(MAX),
@TemplateContentID_a5ad7c84 UNIQUEIDENTIFIER
SET
  @ID_a5ad7c84 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91'
SET
  @TemplateID_a5ad7c84 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_a5ad7c84 = N'History'
SET
  @Description_a5ad7c84 = N'The prior turns as a plain transcript, oldest first and capped, so the prompt does not grow without bound.'
SET
  @Type_a5ad7c84 = N'Scalar'
SET
  @IsRequired_a5ad7c84 = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_a5ad7c84,
  @TemplateID = @TemplateID_a5ad7c84,
  @Name = @Name_a5ad7c84,
  @Description = @Description_a5ad7c84,
  @Type = @Type_a5ad7c84,
  @DefaultValue = @DefaultValue_a5ad7c84,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_a5ad7c84,
  @LinkedParameterName = @LinkedParameterName_a5ad7c84,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_a5ad7c84,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_a5ad7c84,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_a5ad7c84,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_a5ad7c84,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_a5ad7c84,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_a5ad7c84,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_627eb0ca UNIQUEIDENTIFIER,
@TemplateID_627eb0ca UNIQUEIDENTIFIER,
@Name_627eb0ca NVARCHAR(255),
@Description_627eb0ca NVARCHAR(MAX),
@Type_627eb0ca NVARCHAR(20),
@DefaultValue_627eb0ca NVARCHAR(MAX),
@IsRequired_627eb0ca BIT,
@LinkedParameterName_627eb0ca NVARCHAR(255),
@LinkedParameterField_627eb0ca NVARCHAR(500),
@ExtraFilter_627eb0ca NVARCHAR(MAX),
@EntityID_627eb0ca UNIQUEIDENTIFIER,
@RecordID_627eb0ca NVARCHAR(2000),
@OrderBy_627eb0ca NVARCHAR(MAX),
@TemplateContentID_627eb0ca UNIQUEIDENTIFIER
SET
  @ID_627eb0ca = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92'
SET
  @TemplateID_627eb0ca = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_627eb0ca = N'FormContext'
SET
  @Description_627eb0ca = N'A compact description of the form on screen: its name, its questions and its current tokens.'
SET
  @Type_627eb0ca = N'Scalar'
SET
  @IsRequired_627eb0ca = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_627eb0ca,
  @TemplateID = @TemplateID_627eb0ca,
  @Name = @Name_627eb0ca,
  @Description = @Description_627eb0ca,
  @Type = @Type_627eb0ca,
  @DefaultValue = @DefaultValue_627eb0ca,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_627eb0ca,
  @LinkedParameterName = @LinkedParameterName_627eb0ca,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_627eb0ca,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_627eb0ca,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_627eb0ca,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_627eb0ca,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_627eb0ca,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_627eb0ca,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_62fe3536 UNIQUEIDENTIFIER,
@TemplateID_62fe3536 UNIQUEIDENTIFIER,
@Name_62fe3536 NVARCHAR(255),
@Description_62fe3536 NVARCHAR(MAX),
@Type_62fe3536 NVARCHAR(20),
@DefaultValue_62fe3536 NVARCHAR(MAX),
@IsRequired_62fe3536 BIT,
@LinkedParameterName_62fe3536 NVARCHAR(255),
@LinkedParameterField_62fe3536 NVARCHAR(500),
@ExtraFilter_62fe3536 NVARCHAR(MAX),
@EntityID_62fe3536 UNIQUEIDENTIFIER,
@RecordID_62fe3536 NVARCHAR(2000),
@OrderBy_62fe3536 NVARCHAR(MAX),
@TemplateContentID_62fe3536 UNIQUEIDENTIFIER
SET
  @ID_62fe3536 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93'
SET
  @TemplateID_62fe3536 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_62fe3536 = N'HasOpenForm'
SET
  @Description_62fe3536 = N'''yes'' when a form is open, so the prompt can drop the restyle affordance when there is nothing to restyle.'
SET
  @Type_62fe3536 = N'Scalar'
SET
  @IsRequired_62fe3536 = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_62fe3536,
  @TemplateID = @TemplateID_62fe3536,
  @Name = @Name_62fe3536,
  @Description = @Description_62fe3536,
  @Type = @Type_62fe3536,
  @DefaultValue = @DefaultValue_62fe3536,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_62fe3536,
  @LinkedParameterName = @LinkedParameterName_62fe3536,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_62fe3536,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_62fe3536,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_62fe3536,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_62fe3536,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_62fe3536,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_62fe3536,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_3387cdcc UNIQUEIDENTIFIER,
@TemplateID_3387cdcc UNIQUEIDENTIFIER,
@Name_3387cdcc NVARCHAR(255),
@Description_3387cdcc NVARCHAR(MAX),
@Type_3387cdcc NVARCHAR(20),
@DefaultValue_3387cdcc NVARCHAR(MAX),
@IsRequired_3387cdcc BIT,
@LinkedParameterName_3387cdcc NVARCHAR(255),
@LinkedParameterField_3387cdcc NVARCHAR(500),
@ExtraFilter_3387cdcc NVARCHAR(MAX),
@EntityID_3387cdcc UNIQUEIDENTIFIER,
@RecordID_3387cdcc NVARCHAR(2000),
@OrderBy_3387cdcc NVARCHAR(MAX),
@TemplateContentID_3387cdcc UNIQUEIDENTIFIER
SET
  @ID_3387cdcc = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94'
SET
  @TemplateID_3387cdcc = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_3387cdcc = N'Tokens'
SET
  @Description_3387cdcc = N'The --mjf-* vocabulary, supplied by the code that owns it so the prompt and the validator cannot disagree.'
SET
  @Type_3387cdcc = N'Scalar'
SET
  @IsRequired_3387cdcc = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_3387cdcc,
  @TemplateID = @TemplateID_3387cdcc,
  @Name = @Name_3387cdcc,
  @Description = @Description_3387cdcc,
  @Type = @Type_3387cdcc,
  @DefaultValue = @DefaultValue_3387cdcc,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_3387cdcc,
  @LinkedParameterName = @LinkedParameterName_3387cdcc,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_3387cdcc,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_3387cdcc,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_3387cdcc,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_3387cdcc,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_3387cdcc,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_3387cdcc,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Contents (core SP call only)
DECLARE @ID_8242688c UNIQUEIDENTIFIER,
@TemplateID_8242688c UNIQUEIDENTIFIER,
@TypeID_8242688c UNIQUEIDENTIFIER,
@TemplateText_8242688c NVARCHAR(MAX),
@Priority_8242688c INT,
@IsActive_8242688c BIT
SET
  @ID_8242688c = '8F1B6C2A-3D4E-4F50-9A61-7B2C3D4E5F64'
SET
  @TemplateID_8242688c = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @TypeID_8242688c = 'E7AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @TemplateText_8242688c = N'You help someone build a form in MJ Forms. Reply to them, and say what you want done about it. Return a single JSON object — no prose outside it, no markdown fences.

{
  "reply": string,        // what the author reads. Markdown. Always required.
  "action": "none" | "create" | "restyle" | "unsupported",
  "brief"?: string,       // action=create only
  "cssVariables"?: {}     // action=restyle only
}

CHOOSING THE ACTION
- `none` — they asked a question, wanted advice, or were chatting. Nothing changes. This is the most common one; use it freely.
- `create` — they asked for a NEW form. Put everything you know about what they want into "brief", written as a full description rather than an echo of their words: it is handed to a form designer that will not see this conversation.
- `restyle` — they asked to change how the form ON SCREEN looks, and there is one. Put the tokens in "cssVariables".
- `unsupported` — they asked for a real change you cannot make yet. Say so plainly in "reply" and name what you can do instead. Do NOT pretend it worked, and do NOT use `none` for this — a change that silently does not happen is the worst answer available.

WHAT YOU CANNOT DO YET
You cannot add, remove, reword or reorder questions on an existing form, and you cannot change pages. Asked for any of those, use `unsupported` and tell them they can edit it directly in the builder. You CAN create a whole new form, and you CAN restyle one.

RESTYLING
Only these tokens exist. Anything else is discarded, so inventing one loses that part of the design:
{{ Tokens }}

- Colours as `#rrggbb`. Fonts as a full CSS stack ending in a generic family.
- `--mjf-page-bg` is the page, `--mjf-accent` is the buttons, `--mjf-on-accent` is the text ON the buttons, `--mjf-page-ink` is the body text, `--mjf-choice-selected-bg` is a selected answer.
- Set text and its background so the pair is genuinely readable — dark on light, light on dark. Pairs are checked afterwards and a failing one is corrected bluntly, so a pair you get right yourself looks better than one that has to be fixed.
- Send only the tokens you are changing. Everything you omit keeps its current value.
- Sizing, alignment and corner radius are NOT yours to set. If they ask, use `unsupported` and point them at the Design tab.

WRITING THE REPLY
- Talk like a colleague who knows forms. Short. No preamble, no "Certainly!", no restating the question.
- Markdown is rendered: use **bold** for colour values and bullet lists for options. Do not use headings.
- When you act, say what you did in one line. When you cannot, say why in one line.
- Answering a design question well IS the job — you do not have to change something every turn.

{% if HasOpenForm == ''yes'' %}
THE FORM ON SCREEN
{{ FormContext }}
{% else %}
There is no form open — they are on the forms list. You can create one; there is nothing to restyle.
{% endif %}

THE CONVERSATION SO FAR
{{ History }}

THE AUTHOR JUST SAID
"""{{ Message }}"""

Return only the JSON object.
'
SET
  @Priority_8242688c = 100
SET
  @IsActive_8242688c = 1
EXEC [${mjSchema}].spCreateTemplateContent @ID = @ID_8242688c,
  @TemplateID = @TemplateID_8242688c,
  @TypeID = @TypeID_8242688c,
  @TemplateText = @TemplateText_8242688c,
  @Priority = @Priority_8242688c,
  @IsActive = @IsActive_8242688c;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_3d7c1f22 UNIQUEIDENTIFIER,
@Name_3d7c1f22 NVARCHAR(255),
@Description_3d7c1f22 NVARCHAR(MAX),
@Type_3d7c1f22 NVARCHAR(20),
@DefaultValue_3d7c1f22 NVARCHAR(MAX),
@IsRequired_3d7c1f22 BIT,
@LinkedParameterName_3d7c1f22 NVARCHAR(255),
@LinkedParameterField_3d7c1f22 NVARCHAR(500),
@ExtraFilter_3d7c1f22 NVARCHAR(MAX),
@EntityID_3d7c1f22 UNIQUEIDENTIFIER,
@RecordID_3d7c1f22 NVARCHAR(2000),
@OrderBy_3d7c1f22 NVARCHAR(MAX),
@TemplateContentID_3d7c1f22 UNIQUEIDENTIFIER,
@ID_3d7c1f22 UNIQUEIDENTIFIER
SET
  @TemplateID_3d7c1f22 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_3d7c1f22 = N'Message'
SET
  @Description_3d7c1f22 = N'The most recent text input provided by the user'
SET
  @Type_3d7c1f22 = N'Scalar'
SET
  @IsRequired_3d7c1f22 = 1
SET
  @ID_3d7c1f22 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_3d7c1f22,
  @Name = @Name_3d7c1f22,
  @Description = @Description_3d7c1f22,
  @Type = @Type_3d7c1f22,
  @DefaultValue = @DefaultValue_3d7c1f22,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_3d7c1f22,
  @LinkedParameterName = @LinkedParameterName_3d7c1f22,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_3d7c1f22,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_3d7c1f22,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_3d7c1f22,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_3d7c1f22,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_3d7c1f22,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_3d7c1f22,
  @TemplateContentID_Clear = 1,
  @ID = @ID_3d7c1f22;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_46e3158f UNIQUEIDENTIFIER,
@Name_46e3158f NVARCHAR(255),
@Description_46e3158f NVARCHAR(MAX),
@Type_46e3158f NVARCHAR(20),
@DefaultValue_46e3158f NVARCHAR(MAX),
@IsRequired_46e3158f BIT,
@LinkedParameterName_46e3158f NVARCHAR(255),
@LinkedParameterField_46e3158f NVARCHAR(500),
@ExtraFilter_46e3158f NVARCHAR(MAX),
@EntityID_46e3158f UNIQUEIDENTIFIER,
@RecordID_46e3158f NVARCHAR(2000),
@OrderBy_46e3158f NVARCHAR(MAX),
@TemplateContentID_46e3158f UNIQUEIDENTIFIER,
@ID_46e3158f UNIQUEIDENTIFIER
SET
  @TemplateID_46e3158f = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_46e3158f = N'History'
SET
  @Description_46e3158f = N'The transcript of the conversation between the user and the assistant'
SET
  @Type_46e3158f = N'Scalar'
SET
  @IsRequired_46e3158f = 1
SET
  @ID_46e3158f = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_46e3158f,
  @Name = @Name_46e3158f,
  @Description = @Description_46e3158f,
  @Type = @Type_46e3158f,
  @DefaultValue = @DefaultValue_46e3158f,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_46e3158f,
  @LinkedParameterName = @LinkedParameterName_46e3158f,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_46e3158f,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_46e3158f,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_46e3158f,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_46e3158f,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_46e3158f,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_46e3158f,
  @TemplateContentID_Clear = 1,
  @ID = @ID_46e3158f;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_a56d2514 UNIQUEIDENTIFIER,
@Name_a56d2514 NVARCHAR(255),
@Description_a56d2514 NVARCHAR(MAX),
@Type_a56d2514 NVARCHAR(20),
@DefaultValue_a56d2514 NVARCHAR(MAX),
@IsRequired_a56d2514 BIT,
@LinkedParameterName_a56d2514 NVARCHAR(255),
@LinkedParameterField_a56d2514 NVARCHAR(500),
@ExtraFilter_a56d2514 NVARCHAR(MAX),
@EntityID_a56d2514 UNIQUEIDENTIFIER,
@RecordID_a56d2514 NVARCHAR(2000),
@OrderBy_a56d2514 NVARCHAR(MAX),
@TemplateContentID_a56d2514 UNIQUEIDENTIFIER,
@ID_a56d2514 UNIQUEIDENTIFIER
SET
  @TemplateID_a56d2514 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_a56d2514 = N'FormContext'
SET
  @Description_a56d2514 = N'Contextual data representing the form currently on screen'
SET
  @Type_a56d2514 = N'Scalar'
SET
  @IsRequired_a56d2514 = 0
SET
  @ID_a56d2514 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_a56d2514,
  @Name = @Name_a56d2514,
  @Description = @Description_a56d2514,
  @Type = @Type_a56d2514,
  @DefaultValue = @DefaultValue_a56d2514,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_a56d2514,
  @LinkedParameterName = @LinkedParameterName_a56d2514,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_a56d2514,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_a56d2514,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_a56d2514,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_a56d2514,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_a56d2514,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_a56d2514,
  @TemplateContentID_Clear = 1,
  @ID = @ID_a56d2514;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_76464757 UNIQUEIDENTIFIER,
@Name_76464757 NVARCHAR(255),
@Description_76464757 NVARCHAR(MAX),
@Type_76464757 NVARCHAR(20),
@DefaultValue_76464757 NVARCHAR(MAX),
@IsRequired_76464757 BIT,
@LinkedParameterName_76464757 NVARCHAR(255),
@LinkedParameterField_76464757 NVARCHAR(500),
@ExtraFilter_76464757 NVARCHAR(MAX),
@EntityID_76464757 UNIQUEIDENTIFIER,
@RecordID_76464757 NVARCHAR(2000),
@OrderBy_76464757 NVARCHAR(MAX),
@TemplateContentID_76464757 UNIQUEIDENTIFIER,
@ID_76464757 UNIQUEIDENTIFIER
SET
  @TemplateID_76464757 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_76464757 = N'HasOpenForm'
SET
  @Description_76464757 = N'Indicates if a form is currently active or open for the user'
SET
  @Type_76464757 = N'Scalar'
SET
  @IsRequired_76464757 = 0
SET
  @ID_76464757 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_76464757,
  @Name = @Name_76464757,
  @Description = @Description_76464757,
  @Type = @Type_76464757,
  @DefaultValue = @DefaultValue_76464757,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_76464757,
  @LinkedParameterName = @LinkedParameterName_76464757,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_76464757,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_76464757,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_76464757,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_76464757,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_76464757,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_76464757,
  @TemplateContentID_Clear = 1,
  @ID = @ID_76464757;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_532dd2f5 UNIQUEIDENTIFIER,
@Name_532dd2f5 NVARCHAR(255),
@Description_532dd2f5 NVARCHAR(MAX),
@Type_532dd2f5 NVARCHAR(20),
@DefaultValue_532dd2f5 NVARCHAR(MAX),
@IsRequired_532dd2f5 BIT,
@LinkedParameterName_532dd2f5 NVARCHAR(255),
@LinkedParameterField_532dd2f5 NVARCHAR(500),
@ExtraFilter_532dd2f5 NVARCHAR(MAX),
@EntityID_532dd2f5 UNIQUEIDENTIFIER,
@RecordID_532dd2f5 NVARCHAR(2000),
@OrderBy_532dd2f5 NVARCHAR(MAX),
@TemplateContentID_532dd2f5 UNIQUEIDENTIFIER,
@ID_532dd2f5 UNIQUEIDENTIFIER
SET
  @TemplateID_532dd2f5 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_532dd2f5 = N'Tokens'
SET
  @Description_532dd2f5 = N'Template scalar parameter ''Tokens'''
SET
  @Type_532dd2f5 = N'Scalar'
SET
  @IsRequired_532dd2f5 = 1
SET
  @ID_532dd2f5 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_532dd2f5,
  @Name = @Name_532dd2f5,
  @Description = @Description_532dd2f5,
  @Type = @Type_532dd2f5,
  @DefaultValue = @DefaultValue_532dd2f5,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_532dd2f5,
  @LinkedParameterName = @LinkedParameterName_532dd2f5,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_532dd2f5,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_532dd2f5,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_532dd2f5,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_532dd2f5,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_532dd2f5,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_532dd2f5,
  @TemplateContentID_Clear = 1,
  @ID = @ID_532dd2f5;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @ID_07326df9 UNIQUEIDENTIFIER,
@Name_07326df9 NVARCHAR(255),
@Description_07326df9 NVARCHAR(MAX),
@TemplateID_07326df9 UNIQUEIDENTIFIER,
@CategoryID_07326df9 UNIQUEIDENTIFIER,
@TypeID_07326df9 UNIQUEIDENTIFIER,
@Status_07326df9 NVARCHAR(50),
@ResponseFormat_07326df9 NVARCHAR(20),
@ModelSpecificResponseFormat_07326df9 NVARCHAR(MAX),
@AIModelTypeID_07326df9 UNIQUEIDENTIFIER,
@MinPowerRank_07326df9 INT,
@SelectionStrategy_07326df9 NVARCHAR(20),
@PowerPreference_07326df9 NVARCHAR(20),
@ParallelizationMode_07326df9 NVARCHAR(20),
@ParallelCount_07326df9 INT,
@ParallelConfigParam_07326df9 NVARCHAR(100),
@OutputType_07326df9 NVARCHAR(50),
@OutputExample_07326df9 NVARCHAR(MAX),
@ValidationBehavior_07326df9 NVARCHAR(50),
@MaxRetries_07326df9 INT,
@RetryDelayMS_07326df9 INT,
@RetryStrategy_07326df9 NVARCHAR(20),
@ResultSelectorPromptID_07326df9 UNIQUEIDENTIFIER,
@EnableCaching_07326df9 BIT,
@CacheTTLSeconds_07326df9 INT,
@CacheMatchType_07326df9 NVARCHAR(20),
@CacheSimilarityThreshold_07326df9 FLOAT(53),
@CacheMustMatchModel_07326df9 BIT,
@CacheMustMatchVendor_07326df9 BIT,
@CacheMustMatchAgent_07326df9 BIT,
@CacheMustMatchConfig_07326df9 BIT,
@PromptRole_07326df9 NVARCHAR(20),
@PromptPosition_07326df9 NVARCHAR(20),
@Temperature_07326df9 DECIMAL(3, 2),
@TopP_07326df9 DECIMAL(3, 2),
@TopK_07326df9 INT,
@MinP_07326df9 DECIMAL(3, 2),
@FrequencyPenalty_07326df9 DECIMAL(3, 2),
@PresencePenalty_07326df9 DECIMAL(3, 2),
@Seed_07326df9 INT,
@StopSequences_07326df9 NVARCHAR(1000),
@IncludeLogProbs_07326df9 BIT,
@TopLogProbs_07326df9 INT,
@FailoverStrategy_07326df9 NVARCHAR(50),
@FailoverMaxAttempts_07326df9 INT,
@FailoverDelaySeconds_07326df9 INT,
@FailoverModelStrategy_07326df9 NVARCHAR(50),
@FailoverErrorScope_07326df9 NVARCHAR(50),
@EffortLevel_07326df9 INT,
@AssistantPrefill_07326df9 NVARCHAR(MAX),
@PrefillFallbackMode_07326df9 NVARCHAR(20),
@RequireSpecificModels_07326df9 BIT
SET
  @ID_07326df9 = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829308'
SET
  @Name_07326df9 = N'Forms: Chat Assistant'
SET
  @Description_07326df9 = N'The conversational surface of AI authoring. Replies to the author AND declares an action — none, create, restyle, or unsupported — which deterministic code then performs. The model never touches the database, the same split the rest of the authoring pipeline uses. Model selection is metadata-driven and this prompt is the most likely to want a different tier from the structural stages, since it is conversational rather than generative.'
SET
  @TemplateID_07326df9 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @CategoryID_07326df9 = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_07326df9 = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_07326df9 = N'Active'
SET
  @ResponseFormat_07326df9 = N'JSON'
SET
  @AIModelTypeID_07326df9 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_07326df9 = 0
SET
  @SelectionStrategy_07326df9 = N'Specific'
SET
  @PowerPreference_07326df9 = N'Highest'
SET
  @ParallelizationMode_07326df9 = N'None'
SET
  @OutputType_07326df9 = N'object'
SET
  @OutputExample_07326df9 = N'{"reply":"For a **#152A63** background, a white button with **#152A63** text gives the strongest contrast. I''ve applied it.","action":"restyle","brief?":"A five-question event RSVP with dietary needs and a guest count.","cssVariables?":{"--mjf-accent":"#ffffff","--mjf-on-accent":"#152a63"}}'
SET
  @ValidationBehavior_07326df9 = N'None'
SET
  @MaxRetries_07326df9 = 1
SET
  @RetryDelayMS_07326df9 = 0
SET
  @RetryStrategy_07326df9 = N'Fixed'
SET
  @EnableCaching_07326df9 = 0
SET
  @CacheMatchType_07326df9 = N'Exact'
SET
  @CacheMustMatchModel_07326df9 = 1
SET
  @CacheMustMatchVendor_07326df9 = 1
SET
  @CacheMustMatchAgent_07326df9 = 0
SET
  @CacheMustMatchConfig_07326df9 = 0
SET
  @PromptRole_07326df9 = N'System'
SET
  @PromptPosition_07326df9 = N'First'
SET
  @IncludeLogProbs_07326df9 = 0
SET
  @FailoverStrategy_07326df9 = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_07326df9 = 3
SET
  @FailoverDelaySeconds_07326df9 = 5
SET
  @FailoverModelStrategy_07326df9 = N'PreferSameModel'
SET
  @FailoverErrorScope_07326df9 = N'All'
SET
  @PrefillFallbackMode_07326df9 = N'Ignore'
SET
  @RequireSpecificModels_07326df9 = 0
EXEC [${mjSchema}].spCreateAIPrompt @ID = @ID_07326df9,
  @Name = @Name_07326df9,
  @Description = @Description_07326df9,
  @TemplateID = @TemplateID_07326df9,
  @CategoryID = @CategoryID_07326df9,
  @TypeID = @TypeID_07326df9,
  @Status = @Status_07326df9,
  @ResponseFormat = @ResponseFormat_07326df9,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_07326df9,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_07326df9,
  @MinPowerRank = @MinPowerRank_07326df9,
  @SelectionStrategy = @SelectionStrategy_07326df9,
  @PowerPreference = @PowerPreference_07326df9,
  @ParallelizationMode = @ParallelizationMode_07326df9,
  @ParallelCount = @ParallelCount_07326df9,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_07326df9,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_07326df9,
  @OutputExample = @OutputExample_07326df9,
  @ValidationBehavior = @ValidationBehavior_07326df9,
  @MaxRetries = @MaxRetries_07326df9,
  @RetryDelayMS = @RetryDelayMS_07326df9,
  @RetryStrategy = @RetryStrategy_07326df9,
  @ResultSelectorPromptID = @ResultSelectorPromptID_07326df9,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_07326df9,
  @CacheTTLSeconds = @CacheTTLSeconds_07326df9,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_07326df9,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_07326df9,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_07326df9,
  @CacheMustMatchVendor = @CacheMustMatchVendor_07326df9,
  @CacheMustMatchAgent = @CacheMustMatchAgent_07326df9,
  @CacheMustMatchConfig = @CacheMustMatchConfig_07326df9,
  @PromptRole = @PromptRole_07326df9,
  @PromptPosition = @PromptPosition_07326df9,
  @Temperature = @Temperature_07326df9,
  @Temperature_Clear = 1,
  @TopP = @TopP_07326df9,
  @TopP_Clear = 1,
  @TopK = @TopK_07326df9,
  @TopK_Clear = 1,
  @MinP = @MinP_07326df9,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_07326df9,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_07326df9,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_07326df9,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_07326df9,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_07326df9,
  @TopLogProbs = @TopLogProbs_07326df9,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_07326df9,
  @FailoverMaxAttempts = @FailoverMaxAttempts_07326df9,
  @FailoverDelaySeconds = @FailoverDelaySeconds_07326df9,
  @FailoverModelStrategy = @FailoverModelStrategy_07326df9,
  @FailoverErrorScope = @FailoverErrorScope_07326df9,
  @EffortLevel = @EffortLevel_07326df9,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_07326df9,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_07326df9,
  @RequireSpecificModels = @RequireSpecificModels_07326df9;

GO

-- Save MJ: AI Prompt Models (core SP call only)
DECLARE @ID_aff8a16b UNIQUEIDENTIFIER,
@PromptID_aff8a16b UNIQUEIDENTIFIER,
@ModelID_aff8a16b UNIQUEIDENTIFIER,
@VendorID_aff8a16b UNIQUEIDENTIFIER,
@ConfigurationID_aff8a16b UNIQUEIDENTIFIER,
@Priority_aff8a16b INT,
@ExecutionGroup_aff8a16b INT,
@ModelParameters_aff8a16b NVARCHAR(MAX),
@Status_aff8a16b NVARCHAR(20),
@ParallelizationMode_aff8a16b NVARCHAR(20),
@ParallelCount_aff8a16b INT,
@ParallelConfigParam_aff8a16b NVARCHAR(100),
@EffortLevel_aff8a16b INT
SET
  @ID_aff8a16b = '5A6B7C8D-9E0F-4A1B-2C3D-4E5F60718297'
SET
  @PromptID_aff8a16b = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829308'
SET
  @ModelID_aff8a16b = 'BD266132-109B-4701-86F8-52F90C8A9E3E'
SET
  @VendorID_aff8a16b = 'E4A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @Priority_aff8a16b = 100
SET
  @ExecutionGroup_aff8a16b = 0
SET
  @Status_aff8a16b = N'Active'
SET
  @ParallelizationMode_aff8a16b = N'None'
SET
  @ParallelCount_aff8a16b = 1
EXEC [${mjSchema}].spCreateAIPromptModel @ID = @ID_aff8a16b,
  @PromptID = @PromptID_aff8a16b,
  @ModelID = @ModelID_aff8a16b,
  @VendorID = @VendorID_aff8a16b,
  @ConfigurationID = @ConfigurationID_aff8a16b,
  @ConfigurationID_Clear = 1,
  @Priority = @Priority_aff8a16b,
  @ExecutionGroup = @ExecutionGroup_aff8a16b,
  @ModelParameters = @ModelParameters_aff8a16b,
  @ModelParameters_Clear = 1,
  @Status = @Status_aff8a16b,
  @ParallelizationMode = @ParallelizationMode_aff8a16b,
  @ParallelCount = @ParallelCount_aff8a16b,
  @ParallelConfigParam = @ParallelConfigParam_aff8a16b,
  @ParallelConfigParam_Clear = 1,
  @EffortLevel = @EffortLevel_aff8a16b,
  @EffortLevel_Clear = 1;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_7b1ab639 UNIQUEIDENTIFIER,
@EntityID_7b1ab639 UNIQUEIDENTIFIER,
@Name_7b1ab639 NVARCHAR(100),
@Description_7b1ab639 NVARCHAR(MAX),
@CategoryID_7b1ab639 UNIQUEIDENTIFIER,
@IsShared_7b1ab639 BIT,
@IsDefault_7b1ab639 BIT,
@GridState_7b1ab639 NVARCHAR(MAX),
@FilterState_7b1ab639 NVARCHAR(MAX),
@CustomFilterState_7b1ab639 BIT,
@SmartFilterEnabled_7b1ab639 BIT,
@SmartFilterPrompt_7b1ab639 NVARCHAR(MAX),
@SmartFilterWhereClause_7b1ab639 NVARCHAR(MAX),
@SmartFilterExplanation_7b1ab639 NVARCHAR(MAX),
@WhereClause_7b1ab639 NVARCHAR(MAX),
@CustomWhereClause_7b1ab639 BIT,
@SortState_7b1ab639 NVARCHAR(MAX),
@Thumbnail_7b1ab639 NVARCHAR(MAX),
@CardState_7b1ab639 NVARCHAR(MAX),
@DisplayState_7b1ab639 NVARCHAR(MAX),
@ViewTypeID_7b1ab639 UNIQUEIDENTIFIER,
@ID_7b1ab639 UNIQUEIDENTIFIER
SET
  @UserID_7b1ab639 = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_7b1ab639 = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_7b1ab639 = N'All Forms'
SET
  @Description_7b1ab639 = N''
SET
  @IsShared_7b1ab639 = 1
SET
  @IsDefault_7b1ab639 = 0
SET
  @GridState_7b1ab639 = N'{}'
SET
  @FilterState_7b1ab639 = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_7b1ab639 = 0
SET
  @SmartFilterEnabled_7b1ab639 = 0
SET
  @WhereClause_7b1ab639 = N''
SET
  @CustomWhereClause_7b1ab639 = 0
SET
  @ID_7b1ab639 = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_7b1ab639,
  @EntityID = @EntityID_7b1ab639,
  @Name = @Name_7b1ab639,
  @Description = @Description_7b1ab639,
  @CategoryID = @CategoryID_7b1ab639,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_7b1ab639,
  @IsDefault = @IsDefault_7b1ab639,
  @GridState = @GridState_7b1ab639,
  @FilterState = @FilterState_7b1ab639,
  @CustomFilterState = @CustomFilterState_7b1ab639,
  @SmartFilterEnabled = @SmartFilterEnabled_7b1ab639,
  @SmartFilterPrompt = @SmartFilterPrompt_7b1ab639,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_7b1ab639,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_7b1ab639,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_7b1ab639,
  @CustomWhereClause = @CustomWhereClause_7b1ab639,
  @SortState = @SortState_7b1ab639,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_7b1ab639,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_7b1ab639,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_7b1ab639,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_7b1ab639,
  @ViewTypeID_Clear = 1,
  @ID = @ID_7b1ab639;

GO

-- Save MJ: Actions (core SP call only)
DECLARE @ID_a822bd3a UNIQUEIDENTIFIER,
@CategoryID_a822bd3a UNIQUEIDENTIFIER,
@Name_a822bd3a NVARCHAR(425),
@Description_a822bd3a NVARCHAR(MAX),
@Type_a822bd3a NVARCHAR(20),
@UserPrompt_a822bd3a NVARCHAR(MAX),
@UserComments_a822bd3a NVARCHAR(MAX),
@Code_a822bd3a NVARCHAR(MAX),
@CodeComments_a822bd3a NVARCHAR(MAX),
@CodeApprovalStatus_a822bd3a NVARCHAR(20),
@CodeApprovalComments_a822bd3a NVARCHAR(MAX),
@CodeApprovedByUserID_a822bd3a UNIQUEIDENTIFIER,
@CodeApprovedAt_a822bd3a DATETIMEOFFSET,
@CodeLocked_a822bd3a BIT,
@ForceCodeGeneration_a822bd3a BIT,
@RetentionPeriod_a822bd3a INT,
@Status_a822bd3a NVARCHAR(20),
@DriverClass_a822bd3a NVARCHAR(255),
@ParentID_a822bd3a UNIQUEIDENTIFIER,
@IconClass_a822bd3a NVARCHAR(100),
@DefaultCompactPromptID_a822bd3a UNIQUEIDENTIFIER,
@Config_a822bd3a NVARCHAR(MAX),
@RuntimeActionConfiguration_a822bd3a NVARCHAR(MAX),
@MaxExecutionTimeMS_a822bd3a INT,
@CreatedByAgentID_a822bd3a UNIQUEIDENTIFIER
SET
  @ID_a822bd3a = '7F0A0007-A1B2-4C3D-8E4F-000000000007'
SET
  @CategoryID_a822bd3a = '7F0C0001-A1B2-4C3D-8E4F-000000000001'
SET
  @Name_a822bd3a = N'Forms: Chat'
SET
  @Description_a822bd3a = N'The authoring chat. Takes one message plus the thread it belongs to, replies, and performs whatever the assistant declared: create a form, restyle the open one, or nothing. Turns persist in MJ: Conversations so an author returning to a form finds the conversation they left.'
SET
  @Type_a822bd3a = N'Custom'
SET
  @CodeApprovalStatus_a822bd3a = N'Pending'
SET
  @CodeLocked_a822bd3a = 0
SET
  @ForceCodeGeneration_a822bd3a = 0
SET
  @Status_a822bd3a = N'Active'
SET
  @DriverClass_a822bd3a = N'Forms: Chat'
SET
  @IconClass_a822bd3a = N'fa-solid fa-comments' EXEC [${mjSchema}].spCreateAction @ID = @ID_a822bd3a,
  @CategoryID = @CategoryID_a822bd3a,
  @Name = @Name_a822bd3a,
  @Description = @Description_a822bd3a,
  @Type = @Type_a822bd3a,
  @UserPrompt = @UserPrompt_a822bd3a,
  @UserPrompt_Clear = 1,
  @UserComments = @UserComments_a822bd3a,
  @UserComments_Clear = 1,
  @Code = @Code_a822bd3a,
  @Code_Clear = 1,
  @CodeComments = @CodeComments_a822bd3a,
  @CodeComments_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_a822bd3a,
  @CodeApprovalComments = @CodeApprovalComments_a822bd3a,
  @CodeApprovalComments_Clear = 1,
  @CodeApprovedByUserID = @CodeApprovedByUserID_a822bd3a,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_a822bd3a,
  @CodeApprovedAt_Clear = 1,
  @CodeLocked = @CodeLocked_a822bd3a,
  @ForceCodeGeneration = @ForceCodeGeneration_a822bd3a,
  @RetentionPeriod = @RetentionPeriod_a822bd3a,
  @RetentionPeriod_Clear = 1,
  @Status = @Status_a822bd3a,
  @DriverClass = @DriverClass_a822bd3a,
  @ParentID = @ParentID_a822bd3a,
  @ParentID_Clear = 1,
  @IconClass = @IconClass_a822bd3a,
  @DefaultCompactPromptID = @DefaultCompactPromptID_a822bd3a,
  @DefaultCompactPromptID_Clear = 1,
  @Config = @Config_a822bd3a,
  @Config_Clear = 1,
  @RuntimeActionConfiguration = @RuntimeActionConfiguration_a822bd3a,
  @RuntimeActionConfiguration_Clear = 1,
  @MaxExecutionTimeMS = @MaxExecutionTimeMS_a822bd3a,
  @MaxExecutionTimeMS_Clear = 1,
  @CreatedByAgentID = @CreatedByAgentID_a822bd3a,
  @CreatedByAgentID_Clear = 1;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_e3ee9658 UNIQUEIDENTIFIER,
@ActionID_e3ee9658 UNIQUEIDENTIFIER,
@Name_e3ee9658 NVARCHAR(255),
@DefaultValue_e3ee9658 NVARCHAR(MAX),
@Type_e3ee9658 NCHAR(10),
@ValueType_e3ee9658 NVARCHAR(30),
@IsArray_e3ee9658 BIT,
@Description_e3ee9658 NVARCHAR(MAX),
@IsRequired_e3ee9658 BIT,
@MediaModality_e3ee9658 NVARCHAR(20),
@LogValue_e3ee9658 BIT
SET
  @ID_e3ee9658 = '7F0B0007-A1B2-4C3D-8E4F-000000000001'
SET
  @ActionID_e3ee9658 = '7F0A0007-A1B2-4C3D-8E4F-000000000007'
SET
  @Name_e3ee9658 = N'Message'
SET
  @Type_e3ee9658 = N'Input'
SET
  @ValueType_e3ee9658 = N'Scalar'
SET
  @IsArray_e3ee9658 = 0
SET
  @Description_e3ee9658 = N'What the author typed.'
SET
  @IsRequired_e3ee9658 = 1
SET
  @LogValue_e3ee9658 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_e3ee9658,
  @ActionID = @ActionID_e3ee9658,
  @Name = @Name_e3ee9658,
  @DefaultValue = @DefaultValue_e3ee9658,
  @DefaultValue_Clear = 1,
  @Type = @Type_e3ee9658,
  @ValueType = @ValueType_e3ee9658,
  @IsArray = @IsArray_e3ee9658,
  @Description = @Description_e3ee9658,
  @IsRequired = @IsRequired_e3ee9658,
  @MediaModality = @MediaModality_e3ee9658,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_e3ee9658;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_c99c8670 UNIQUEIDENTIFIER,
@ActionID_c99c8670 UNIQUEIDENTIFIER,
@Name_c99c8670 NVARCHAR(255),
@DefaultValue_c99c8670 NVARCHAR(MAX),
@Type_c99c8670 NCHAR(10),
@ValueType_c99c8670 NVARCHAR(30),
@IsArray_c99c8670 BIT,
@Description_c99c8670 NVARCHAR(MAX),
@IsRequired_c99c8670 BIT,
@MediaModality_c99c8670 NVARCHAR(20),
@LogValue_c99c8670 BIT
SET
  @ID_c99c8670 = '7F0B0007-A1B2-4C3D-8E4F-000000000002'
SET
  @ActionID_c99c8670 = '7F0A0007-A1B2-4C3D-8E4F-000000000007'
SET
  @Name_c99c8670 = N'FormID'
SET
  @Type_c99c8670 = N'Input'
SET
  @ValueType_c99c8670 = N'Scalar'
SET
  @IsArray_c99c8670 = 0
SET
  @Description_c99c8670 = N'The form on screen. Scopes the thread and gives the assistant something to answer about.'
SET
  @IsRequired_c99c8670 = 0
SET
  @LogValue_c99c8670 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_c99c8670,
  @ActionID = @ActionID_c99c8670,
  @Name = @Name_c99c8670,
  @DefaultValue = @DefaultValue_c99c8670,
  @DefaultValue_Clear = 1,
  @Type = @Type_c99c8670,
  @ValueType = @ValueType_c99c8670,
  @IsArray = @IsArray_c99c8670,
  @Description = @Description_c99c8670,
  @IsRequired = @IsRequired_c99c8670,
  @MediaModality = @MediaModality_c99c8670,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_c99c8670;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_535421dc UNIQUEIDENTIFIER,
@ActionID_535421dc UNIQUEIDENTIFIER,
@Name_535421dc NVARCHAR(255),
@DefaultValue_535421dc NVARCHAR(MAX),
@Type_535421dc NCHAR(10),
@ValueType_535421dc NVARCHAR(30),
@IsArray_535421dc BIT,
@Description_535421dc NVARCHAR(MAX),
@IsRequired_535421dc BIT,
@MediaModality_535421dc NVARCHAR(20),
@LogValue_535421dc BIT
SET
  @ID_535421dc = '7F0B0007-A1B2-4C3D-8E4F-000000000003'
SET
  @ActionID_535421dc = '7F0A0007-A1B2-4C3D-8E4F-000000000007'
SET
  @Name_535421dc = N'ConversationID'
SET
  @Type_535421dc = N'Input'
SET
  @ValueType_535421dc = N'Scalar'
SET
  @IsArray_535421dc = 0
SET
  @Description_535421dc = N'Continue a specific thread. Omit and the thread for this user and form is found or started.'
SET
  @IsRequired_535421dc = 0
SET
  @LogValue_535421dc = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_535421dc,
  @ActionID = @ActionID_535421dc,
  @Name = @Name_535421dc,
  @DefaultValue = @DefaultValue_535421dc,
  @DefaultValue_Clear = 1,
  @Type = @Type_535421dc,
  @ValueType = @ValueType_535421dc,
  @IsArray = @IsArray_535421dc,
  @Description = @Description_535421dc,
  @IsRequired = @IsRequired_535421dc,
  @MediaModality = @MediaModality_535421dc,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_535421dc;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_f9c16d35 UNIQUEIDENTIFIER,
@ActionID_f9c16d35 UNIQUEIDENTIFIER,
@Name_f9c16d35 NVARCHAR(255),
@DefaultValue_f9c16d35 NVARCHAR(MAX),
@Type_f9c16d35 NCHAR(10),
@ValueType_f9c16d35 NVARCHAR(30),
@IsArray_f9c16d35 BIT,
@Description_f9c16d35 NVARCHAR(MAX),
@IsRequired_f9c16d35 BIT,
@MediaModality_f9c16d35 NVARCHAR(20),
@LogValue_f9c16d35 BIT
SET
  @ID_f9c16d35 = '7F0B0007-A1B2-4C3D-8E4F-000000000004'
SET
  @ActionID_f9c16d35 = '7F0A0007-A1B2-4C3D-8E4F-000000000007'
SET
  @Name_f9c16d35 = N'SessionID'
SET
  @Type_f9c16d35 = N'Input'
SET
  @ValueType_f9c16d35 = N'Scalar'
SET
  @IsArray_f9c16d35 = 0
SET
  @Description_f9c16d35 = N'Push-channel session, so a turn that generates a form streams its progress.'
SET
  @IsRequired_f9c16d35 = 0
SET
  @LogValue_f9c16d35 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_f9c16d35,
  @ActionID = @ActionID_f9c16d35,
  @Name = @Name_f9c16d35,
  @DefaultValue = @DefaultValue_f9c16d35,
  @DefaultValue_Clear = 1,
  @Type = @Type_f9c16d35,
  @ValueType = @ValueType_f9c16d35,
  @IsArray = @IsArray_f9c16d35,
  @Description = @Description_f9c16d35,
  @IsRequired = @IsRequired_f9c16d35,
  @MediaModality = @MediaModality_f9c16d35,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_f9c16d35;

GO


-- End of SQL Logging Session
-- Session ID: 3bfc8da7-6b5e-41fb-9421-d37aba39e808
-- Completed: 2026-08-20T23:01:11.531Z
-- Duration: 7601ms
-- Total Statements: 20
