-- ---------------------------------------------------------------------------------------------
-- Metadata seed delta: the assistant can change a form, not only make one.
--
-- WHAT THIS CARRIES
--   * 'MJ_BizApps_Forms: Chat Assistant' template text — two new actions, `edit` and `open`, the
--     nine operations `edit` carries, and the rules about what may not be changed.
--   * A sixth template param, 'FormList', so the assistant can be told which forms the author has
--     and name one to open.
--   * 'Forms: Chat Assistant' OutputExample — `operations` and `openFormId`, both `?`-suffixed,
--     because MJ treats every unsuffixed example key as REQUIRED and would burn every retry.
--
-- WHY THE MODEL NEVER SEES AN ID. The form is written into the prompt with short handles — `p1`,
-- `q3`, `o2`, `s1`, and `f1` for another of their forms — and operations name those. An invented
-- handle resolves to nothing; an invented GUID might name a real row in somebody else's form. It
-- is also what keeps the context affordable: forty questions of GUIDs is ~1,500 tokens on every
-- turn, and forty handles is forty.
--
-- WHAT THE PROMPT IS TOLD IT MAY NOT DO, and why it is told rather than merely stopped: a question
-- with answers cannot be deleted or retyped, and the answer count sits beside every question in
-- the context. An assistant that says "32 people have answered that one" is a better reply than a
-- refused operation and an apology. The server refuses either way.
--
-- NO NEW TABLES and no schema change. Structural editing is entirely a prompt-and-code feature
-- over rows that already exist.
--
-- Generated as its predecessors were: pushed against MJ_Install_Rehearsal, 0 Form rows throughout.
-- Every `${flyway:defaultSchema}` became `${mjSchema}` — all five procedures here are CORE. No
-- Forms-schema SP calls and no Form Respondent permission records, so #41's watershed is untouched.
-- ---------------------------------------------------------------------------------------------

-- SQL Logging Session
-- Session ID: a033de3d-2c56-47dd-bdd3-6d10af58e4b9
-- Started: 2026-08-21T02:50:36.516Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_47f7a8ac UNIQUEIDENTIFIER,
@Name_47f7a8ac NVARCHAR(255),
@Description_47f7a8ac NVARCHAR(MAX),
@Type_47f7a8ac NVARCHAR(20),
@DefaultValue_47f7a8ac NVARCHAR(MAX),
@IsRequired_47f7a8ac BIT,
@LinkedParameterName_47f7a8ac NVARCHAR(255),
@LinkedParameterField_47f7a8ac NVARCHAR(500),
@ExtraFilter_47f7a8ac NVARCHAR(MAX),
@EntityID_47f7a8ac UNIQUEIDENTIFIER,
@RecordID_47f7a8ac NVARCHAR(2000),
@OrderBy_47f7a8ac NVARCHAR(MAX),
@TemplateContentID_47f7a8ac UNIQUEIDENTIFIER,
@ID_47f7a8ac UNIQUEIDENTIFIER
SET
  @TemplateID_47f7a8ac = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_47f7a8ac = N'Message'
SET
  @Description_47f7a8ac = N'What the author just typed.'
SET
  @Type_47f7a8ac = N'Scalar'
SET
  @IsRequired_47f7a8ac = 1
SET
  @ID_47f7a8ac = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_47f7a8ac,
  @Name = @Name_47f7a8ac,
  @Description = @Description_47f7a8ac,
  @Type = @Type_47f7a8ac,
  @DefaultValue = @DefaultValue_47f7a8ac,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_47f7a8ac,
  @LinkedParameterName = @LinkedParameterName_47f7a8ac,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_47f7a8ac,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_47f7a8ac,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_47f7a8ac,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_47f7a8ac,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_47f7a8ac,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_47f7a8ac,
  @TemplateContentID_Clear = 1,
  @ID = @ID_47f7a8ac;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_d13b71b0 UNIQUEIDENTIFIER,
@Name_d13b71b0 NVARCHAR(255),
@Description_d13b71b0 NVARCHAR(MAX),
@Type_d13b71b0 NVARCHAR(20),
@DefaultValue_d13b71b0 NVARCHAR(MAX),
@IsRequired_d13b71b0 BIT,
@LinkedParameterName_d13b71b0 NVARCHAR(255),
@LinkedParameterField_d13b71b0 NVARCHAR(500),
@ExtraFilter_d13b71b0 NVARCHAR(MAX),
@EntityID_d13b71b0 UNIQUEIDENTIFIER,
@RecordID_d13b71b0 NVARCHAR(2000),
@OrderBy_d13b71b0 NVARCHAR(MAX),
@TemplateContentID_d13b71b0 UNIQUEIDENTIFIER,
@ID_d13b71b0 UNIQUEIDENTIFIER
SET
  @TemplateID_d13b71b0 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_d13b71b0 = N'FormContext'
SET
  @Description_d13b71b0 = N'A compact description of the form on screen: its name, its questions and its current tokens.'
SET
  @Type_d13b71b0 = N'Scalar'
SET
  @IsRequired_d13b71b0 = 1
SET
  @ID_d13b71b0 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_d13b71b0,
  @Name = @Name_d13b71b0,
  @Description = @Description_d13b71b0,
  @Type = @Type_d13b71b0,
  @DefaultValue = @DefaultValue_d13b71b0,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_d13b71b0,
  @LinkedParameterName = @LinkedParameterName_d13b71b0,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_d13b71b0,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_d13b71b0,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_d13b71b0,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_d13b71b0,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_d13b71b0,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_d13b71b0,
  @TemplateContentID_Clear = 1,
  @ID = @ID_d13b71b0;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_333a3d3f UNIQUEIDENTIFIER,
@Name_333a3d3f NVARCHAR(255),
@Description_333a3d3f NVARCHAR(MAX),
@Type_333a3d3f NVARCHAR(20),
@DefaultValue_333a3d3f NVARCHAR(MAX),
@IsRequired_333a3d3f BIT,
@LinkedParameterName_333a3d3f NVARCHAR(255),
@LinkedParameterField_333a3d3f NVARCHAR(500),
@ExtraFilter_333a3d3f NVARCHAR(MAX),
@EntityID_333a3d3f UNIQUEIDENTIFIER,
@RecordID_333a3d3f NVARCHAR(2000),
@OrderBy_333a3d3f NVARCHAR(MAX),
@TemplateContentID_333a3d3f UNIQUEIDENTIFIER,
@ID_333a3d3f UNIQUEIDENTIFIER
SET
  @TemplateID_333a3d3f = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_333a3d3f = N'HasOpenForm'
SET
  @Description_333a3d3f = N'''yes'' when a form is open, so the prompt can drop the restyle affordance when there is nothing to restyle.'
SET
  @Type_333a3d3f = N'Scalar'
SET
  @IsRequired_333a3d3f = 1
SET
  @ID_333a3d3f = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_333a3d3f,
  @Name = @Name_333a3d3f,
  @Description = @Description_333a3d3f,
  @Type = @Type_333a3d3f,
  @DefaultValue = @DefaultValue_333a3d3f,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_333a3d3f,
  @LinkedParameterName = @LinkedParameterName_333a3d3f,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_333a3d3f,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_333a3d3f,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_333a3d3f,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_333a3d3f,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_333a3d3f,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_333a3d3f,
  @TemplateContentID_Clear = 1,
  @ID = @ID_333a3d3f;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_b405f419 UNIQUEIDENTIFIER,
@Name_b405f419 NVARCHAR(255),
@Description_b405f419 NVARCHAR(MAX),
@Type_b405f419 NVARCHAR(20),
@DefaultValue_b405f419 NVARCHAR(MAX),
@IsRequired_b405f419 BIT,
@LinkedParameterName_b405f419 NVARCHAR(255),
@LinkedParameterField_b405f419 NVARCHAR(500),
@ExtraFilter_b405f419 NVARCHAR(MAX),
@EntityID_b405f419 UNIQUEIDENTIFIER,
@RecordID_b405f419 NVARCHAR(2000),
@OrderBy_b405f419 NVARCHAR(MAX),
@TemplateContentID_b405f419 UNIQUEIDENTIFIER,
@ID_b405f419 UNIQUEIDENTIFIER
SET
  @TemplateID_b405f419 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_b405f419 = N'Tokens'
SET
  @Description_b405f419 = N'The --mjf-* vocabulary, supplied by the code that owns it so the prompt and the validator cannot disagree.'
SET
  @Type_b405f419 = N'Scalar'
SET
  @IsRequired_b405f419 = 1
SET
  @ID_b405f419 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_b405f419,
  @Name = @Name_b405f419,
  @Description = @Description_b405f419,
  @Type = @Type_b405f419,
  @DefaultValue = @DefaultValue_b405f419,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_b405f419,
  @LinkedParameterName = @LinkedParameterName_b405f419,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_b405f419,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_b405f419,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_b405f419,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_b405f419,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_b405f419,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_b405f419,
  @TemplateContentID_Clear = 1,
  @ID = @ID_b405f419;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_186e305e UNIQUEIDENTIFIER,
@Name_186e305e NVARCHAR(255),
@Description_186e305e NVARCHAR(MAX),
@Type_186e305e NVARCHAR(20),
@DefaultValue_186e305e NVARCHAR(MAX),
@IsRequired_186e305e BIT,
@LinkedParameterName_186e305e NVARCHAR(255),
@LinkedParameterField_186e305e NVARCHAR(500),
@ExtraFilter_186e305e NVARCHAR(MAX),
@EntityID_186e305e UNIQUEIDENTIFIER,
@RecordID_186e305e NVARCHAR(2000),
@OrderBy_186e305e NVARCHAR(MAX),
@TemplateContentID_186e305e UNIQUEIDENTIFIER,
@ID_186e305e UNIQUEIDENTIFIER
SET
  @TemplateID_186e305e = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_186e305e = N'History'
SET
  @Description_186e305e = N'The prior turns as a plain transcript, oldest first and capped, so the prompt does not grow without bound.'
SET
  @Type_186e305e = N'Scalar'
SET
  @IsRequired_186e305e = 1
SET
  @ID_186e305e = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_186e305e,
  @Name = @Name_186e305e,
  @Description = @Description_186e305e,
  @Type = @Type_186e305e,
  @DefaultValue = @DefaultValue_186e305e,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_186e305e,
  @LinkedParameterName = @LinkedParameterName_186e305e,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_186e305e,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_186e305e,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_186e305e,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_186e305e,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_186e305e,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_186e305e,
  @TemplateContentID_Clear = 1,
  @ID = @ID_186e305e;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @ID_1a78c535 UNIQUEIDENTIFIER,
@TemplateID_1a78c535 UNIQUEIDENTIFIER,
@Name_1a78c535 NVARCHAR(255),
@Description_1a78c535 NVARCHAR(MAX),
@Type_1a78c535 NVARCHAR(20),
@DefaultValue_1a78c535 NVARCHAR(MAX),
@IsRequired_1a78c535 BIT,
@LinkedParameterName_1a78c535 NVARCHAR(255),
@LinkedParameterField_1a78c535 NVARCHAR(500),
@ExtraFilter_1a78c535 NVARCHAR(MAX),
@EntityID_1a78c535 UNIQUEIDENTIFIER,
@RecordID_1a78c535 NVARCHAR(2000),
@OrderBy_1a78c535 NVARCHAR(MAX),
@TemplateContentID_1a78c535 UNIQUEIDENTIFIER
SET
  @ID_1a78c535 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E95'
SET
  @TemplateID_1a78c535 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_1a78c535 = N'FormList'
SET
  @Description_1a78c535 = N'The author''s own forms, by handle, so the assistant can name one to open. Read-only — opening navigates, it never writes.'
SET
  @Type_1a78c535 = N'Scalar'
SET
  @IsRequired_1a78c535 = 1
EXEC [${mjSchema}].spCreateTemplateParam @ID = @ID_1a78c535,
  @TemplateID = @TemplateID_1a78c535,
  @Name = @Name_1a78c535,
  @Description = @Description_1a78c535,
  @Type = @Type_1a78c535,
  @DefaultValue = @DefaultValue_1a78c535,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_1a78c535,
  @LinkedParameterName = @LinkedParameterName_1a78c535,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_1a78c535,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_1a78c535,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_1a78c535,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_1a78c535,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_1a78c535,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_1a78c535,
  @TemplateContentID_Clear = 1;

GO

-- Save MJ: Template Contents (core SP call only)
DECLARE @TemplateID_6d2b5b58 UNIQUEIDENTIFIER,
@TypeID_6d2b5b58 UNIQUEIDENTIFIER,
@TemplateText_6d2b5b58 NVARCHAR(MAX),
@Priority_6d2b5b58 INT,
@IsActive_6d2b5b58 BIT,
@ID_6d2b5b58 UNIQUEIDENTIFIER
SET
  @TemplateID_6d2b5b58 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @TypeID_6d2b5b58 = 'E7AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @TemplateText_6d2b5b58 = N'You help someone build a form in MJ Forms. Reply to them, and say what you want done about it. Return a single JSON object — no prose outside it, no markdown fences.

{
  "reply": string,        // what the author reads. Markdown. Always required.
  "action": "none" | "create" | "restyle" | "image" | "edit" | "open" | "unsupported",
  "brief"?: string,       // action=create only
  "cssVariables"?: {},    // action=restyle only
  "imagePrompt"?: string, // action=image only
  "imageTarget"?: "welcome" | "ending",  // action=image only; defaults to welcome
  "operations"?: [],      // action=edit only — see CHANGING THE FORM
  "openFormId"?: string   // action=open only — a handle from THEIR FORMS
}

CHOOSING THE ACTION
- `none` — they asked a question, wanted advice, or were chatting. Nothing changes. This is the most common one; use it freely.
- `create` — they asked for a NEW form. Put everything you know about what they want into "brief", written as a full description rather than an echo of their words: it is handed to a form designer that will not see this conversation.
- `restyle` — they asked to change how the form ON SCREEN looks, and there is one. Put the tokens in "cssVariables".
- `image` — they asked for a picture on the form''s start or finish screen. Describe the picture in "imagePrompt".
- `edit` — they asked to change the form ITSELF: its questions, its pages, its screens'' wording, or its sizing. Put the changes in "operations".
- `open` — they asked to go to a different form of theirs. Name its handle in "openFormId".
- `unsupported` — they asked for a real change you cannot make yet. Say so plainly in "reply" and name what you can do instead. Do NOT pretend it worked, and do NOT use `none` for this — a change that silently does not happen is the worst answer available.

CHANGING THE FORM

THE FORM ON SCREEN is written out below with a HANDLE on everything — `p1` for a page, `q3` for a
question, `o2` for a choice, `s1` for a screen. Name those handles in "operations". Never invent
one, and never write a long id: a handle you were not shown resolves to nothing and the change is
refused.

    {"op": "addQuestion",   "handle": "p1", "type": "Rating", "prompt": "…",
                            "isRequired": false, "options": ["A","B"], "after": "q3"}
    {"op": "updateQuestion","handle": "q3", "prompt": "…", "helpText": "…",
                            "isRequired": true, "type": "Email"}
    {"op": "moveQuestion",  "handle": "q3", "after": "q1", "toPage": "p2"}
    {"op": "deleteQuestion","handle": "q3"}
    {"op": "addPage",       "title": "Availability", "description": "…"}
    {"op": "updatePage",    "handle": "p1", "title": "…", "description": "…"}
    {"op": "deletePage",    "handle": "p2"}
    {"op": "updateScreen",  "handle": "s1", "title": "…", "body": "…", "buttonLabel": "Start"}
    {"op": "setLayout",     "tokens": {"--mjf-question-size": "0.9375rem"}}

`handle` names the PAGE for `addQuestion` and the QUESTION for the rest. `after` is always a
question. Omit `after` on `addQuestion` and it goes at the end of the page; omit it on
`moveQuestion` and it goes to the top.

Send several operations in one turn when they asked for several things. They are applied in order.

WHAT YOU MUST NOT CHANGE
- A question that already has answers cannot be DELETED, and cannot have its TYPE changed. The
  count is written beside every question below. Say so in your own words before proposing it —
  "32 people have answered that one, so removing it removes their answers" is a better reply than
  a refused operation. Rewording an answered question is fine.
- A page holding an answered question cannot be deleted either.
- `setLayout` takes ONLY the five tokens under LAYOUT below. A colour sent there is refused —
  colours go through `restyle`, which checks them for contrast.

SIZES AND ALIGNMENT stay as they are unless the author asks for them by name. "Make it feel
lighter" is a restyle; "make the questions smaller" is a `setLayout`.

WHAT YOU STILL CANNOT DO
You cannot publish a form or create a share link — that is theirs to do, from the Publish button at
the top right. You cannot set conditional show/hide rules yet. Asked for either, use `unsupported`,
say so plainly, and name where they can do it.

You CAN create a whole new form, restyle one, put a picture on its start or finish screen, change
its questions and pages, and take them to another of their forms. Never say you cannot make images
or cannot edit questions — you can.

THEIR FORMS
{{ FormList }}

Use `open` when they name a form that is not the one on screen. Opening takes them there; it does
not change anything. To edit a different form, open it first and then change it on the next turn.

PICTURES
- "imagePrompt" describes the picture itself — "a sunlit conference hall with rows of empty chairs", "a bowl of ramen on a worn wooden table". Describe it; do not write an instruction like "generate an image of…".
- "imageTarget" is "welcome" unless they clearly meant the finish screen. Welcome is the default: it is the screen someone sees before deciding whether to start.
- One picture per turn. It takes a few seconds, so say what you are making in one line and do not promise more.
- Keep the description close to what they asked for. A picture that fights the form''s colours is worse than a plain one.

RESTYLING
Only these tokens exist. Anything else is discarded, so inventing one loses that part of the design:
{{ Tokens }}

- Colours as `#rrggbb`. Fonts as a full CSS stack ending in a generic family.
- `--mjf-page-bg` is the page, `--mjf-accent` is the buttons, `--mjf-on-accent` is the text ON the buttons, `--mjf-page-ink` is the body text, `--mjf-choice-selected-bg` is a selected answer.
- Set text and its background so the pair is genuinely readable — dark on light, light on dark. Pairs are checked afterwards and a failing one is corrected bluntly, so a pair you get right yourself looks better than one that has to be fixed.
- Send only the tokens you are changing. Everything you omit keeps its current value.
- Sizing, alignment and corner radius are NOT yours to set. If they ask, use `unsupported` and point them at the Design tab.

WRITING THE REPLY
- Talk like a colleague who knows forms. Short. No preamble, no "Certainly!", no restating the question.
- Markdown is rendered: use **bold** for colour values and bullet lists for options. Do not use headings.
- Answering a design question well IS the job — you do not have to change something every turn.

- SAY WHAT YOU DID, NOT WHAT YOU ARE ABOUT TO DO. By the time the author reads your reply the change
  has already happened. "I''m generating an image for your welcome screen now" tells them nothing they
  can check; "Added a photo of a sunlit conference hall to the start screen" does. Past tense, and
  name the thing.
- NAME THE VALUES. A restyle reply that does not contain the colours you set is a reply the author
  has to go and verify. "Page is now **#121827** with **#f5f5f5** text and **#1b7fa8** buttons" is
  one line and answers the question they would otherwise ask next.
- CHANGE WHAT THEY ASKED FOR AND NOT MORE. Asked for a background, change the background. If you
  think the buttons need to move with it, say so and offer — do not do it and mention it afterwards.
  An author who has to say "I asked for the background" has been ignored.
- WHEN YOU CANNOT DO IT, SAY WHERE THEY CAN. Not "you can do that in the builder" — name the control:
  the **Design tab** for colours, sizes, fonts and corner radius; the **+ button** in the left panel
  for a new question; the question''s own panel on the right for its wording, type, options and
  whether it is required. One sentence, and it should be enough to act on without asking again.

{% if HasOpenForm == ''yes'' %}
THE FORM ON SCREEN
{{ FormContext }}
{% else %}
There is no form open — they are on the forms list. You can create one; there is nothing to restyle.
{% endif %}

THE CONVERSATION SO FAR
{{ History }}

THE AUTHOR JUST SAID
"""{{ Message }}"""

Return only the JSON object.
'
SET
  @Priority_6d2b5b58 = 100
SET
  @IsActive_6d2b5b58 = 1
SET
  @ID_6d2b5b58 = '8F1B6C2A-3D4E-4F50-9A61-7B2C3D4E5F64' EXEC [${mjSchema}].spUpdateTemplateContent @TemplateID = @TemplateID_6d2b5b58,
  @TypeID = @TypeID_6d2b5b58,
  @TemplateText = @TemplateText_6d2b5b58,
  @Priority = @Priority_6d2b5b58,
  @IsActive = @IsActive_6d2b5b58,
  @ID = @ID_6d2b5b58;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_26bbfc20 UNIQUEIDENTIFIER,
@Name_26bbfc20 NVARCHAR(255),
@Description_26bbfc20 NVARCHAR(MAX),
@Type_26bbfc20 NVARCHAR(20),
@DefaultValue_26bbfc20 NVARCHAR(MAX),
@IsRequired_26bbfc20 BIT,
@LinkedParameterName_26bbfc20 NVARCHAR(255),
@LinkedParameterField_26bbfc20 NVARCHAR(500),
@ExtraFilter_26bbfc20 NVARCHAR(MAX),
@EntityID_26bbfc20 UNIQUEIDENTIFIER,
@RecordID_26bbfc20 NVARCHAR(2000),
@OrderBy_26bbfc20 NVARCHAR(MAX),
@TemplateContentID_26bbfc20 UNIQUEIDENTIFIER,
@ID_26bbfc20 UNIQUEIDENTIFIER
SET
  @TemplateID_26bbfc20 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_26bbfc20 = N'Message'
SET
  @Description_26bbfc20 = N'The latest message sent by the user'
SET
  @Type_26bbfc20 = N'Scalar'
SET
  @IsRequired_26bbfc20 = 1
SET
  @ID_26bbfc20 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_26bbfc20,
  @Name = @Name_26bbfc20,
  @Description = @Description_26bbfc20,
  @Type = @Type_26bbfc20,
  @DefaultValue = @DefaultValue_26bbfc20,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_26bbfc20,
  @LinkedParameterName = @LinkedParameterName_26bbfc20,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_26bbfc20,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_26bbfc20,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_26bbfc20,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_26bbfc20,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_26bbfc20,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_26bbfc20,
  @TemplateContentID_Clear = 1,
  @ID = @ID_26bbfc20;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_243de211 UNIQUEIDENTIFIER,
@Name_243de211 NVARCHAR(255),
@Description_243de211 NVARCHAR(MAX),
@Type_243de211 NVARCHAR(20),
@DefaultValue_243de211 NVARCHAR(MAX),
@IsRequired_243de211 BIT,
@LinkedParameterName_243de211 NVARCHAR(255),
@LinkedParameterField_243de211 NVARCHAR(500),
@ExtraFilter_243de211 NVARCHAR(MAX),
@EntityID_243de211 UNIQUEIDENTIFIER,
@RecordID_243de211 NVARCHAR(2000),
@OrderBy_243de211 NVARCHAR(MAX),
@TemplateContentID_243de211 UNIQUEIDENTIFIER,
@ID_243de211 UNIQUEIDENTIFIER
SET
  @TemplateID_243de211 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_243de211 = N'History'
SET
  @Description_243de211 = N'The conversation history between the user and the assistant'
SET
  @Type_243de211 = N'Scalar'
SET
  @IsRequired_243de211 = 1
SET
  @ID_243de211 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_243de211,
  @Name = @Name_243de211,
  @Description = @Description_243de211,
  @Type = @Type_243de211,
  @DefaultValue = @DefaultValue_243de211,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_243de211,
  @LinkedParameterName = @LinkedParameterName_243de211,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_243de211,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_243de211,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_243de211,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_243de211,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_243de211,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_243de211,
  @TemplateContentID_Clear = 1,
  @ID = @ID_243de211;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_8039f30c UNIQUEIDENTIFIER,
@Name_8039f30c NVARCHAR(255),
@Description_8039f30c NVARCHAR(MAX),
@Type_8039f30c NVARCHAR(20),
@DefaultValue_8039f30c NVARCHAR(MAX),
@IsRequired_8039f30c BIT,
@LinkedParameterName_8039f30c NVARCHAR(255),
@LinkedParameterField_8039f30c NVARCHAR(500),
@ExtraFilter_8039f30c NVARCHAR(MAX),
@EntityID_8039f30c UNIQUEIDENTIFIER,
@RecordID_8039f30c NVARCHAR(2000),
@OrderBy_8039f30c NVARCHAR(MAX),
@TemplateContentID_8039f30c UNIQUEIDENTIFIER,
@ID_8039f30c UNIQUEIDENTIFIER
SET
  @TemplateID_8039f30c = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_8039f30c = N'FormContext'
SET
  @Description_8039f30c = N'Data representing the structure of the currently open form'
SET
  @Type_8039f30c = N'Scalar'
SET
  @IsRequired_8039f30c = 0
SET
  @ID_8039f30c = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_8039f30c,
  @Name = @Name_8039f30c,
  @Description = @Description_8039f30c,
  @Type = @Type_8039f30c,
  @DefaultValue = @DefaultValue_8039f30c,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_8039f30c,
  @LinkedParameterName = @LinkedParameterName_8039f30c,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_8039f30c,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_8039f30c,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_8039f30c,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_8039f30c,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_8039f30c,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_8039f30c,
  @TemplateContentID_Clear = 1,
  @ID = @ID_8039f30c;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_1f000f46 UNIQUEIDENTIFIER,
@Name_1f000f46 NVARCHAR(255),
@Description_1f000f46 NVARCHAR(MAX),
@Type_1f000f46 NVARCHAR(20),
@DefaultValue_1f000f46 NVARCHAR(MAX),
@IsRequired_1f000f46 BIT,
@LinkedParameterName_1f000f46 NVARCHAR(255),
@LinkedParameterField_1f000f46 NVARCHAR(500),
@ExtraFilter_1f000f46 NVARCHAR(MAX),
@EntityID_1f000f46 UNIQUEIDENTIFIER,
@RecordID_1f000f46 NVARCHAR(2000),
@OrderBy_1f000f46 NVARCHAR(MAX),
@TemplateContentID_1f000f46 UNIQUEIDENTIFIER,
@ID_1f000f46 UNIQUEIDENTIFIER
SET
  @TemplateID_1f000f46 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_1f000f46 = N'HasOpenForm'
SET
  @Description_1f000f46 = N'Flag indicating if a specific form is currently open/selected'
SET
  @Type_1f000f46 = N'Scalar'
SET
  @IsRequired_1f000f46 = 0
SET
  @ID_1f000f46 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_1f000f46,
  @Name = @Name_1f000f46,
  @Description = @Description_1f000f46,
  @Type = @Type_1f000f46,
  @DefaultValue = @DefaultValue_1f000f46,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_1f000f46,
  @LinkedParameterName = @LinkedParameterName_1f000f46,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_1f000f46,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_1f000f46,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_1f000f46,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_1f000f46,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_1f000f46,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_1f000f46,
  @TemplateContentID_Clear = 1,
  @ID = @ID_1f000f46;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_453eb833 UNIQUEIDENTIFIER,
@Name_453eb833 NVARCHAR(255),
@Description_453eb833 NVARCHAR(MAX),
@Type_453eb833 NVARCHAR(20),
@DefaultValue_453eb833 NVARCHAR(MAX),
@IsRequired_453eb833 BIT,
@LinkedParameterName_453eb833 NVARCHAR(255),
@LinkedParameterField_453eb833 NVARCHAR(500),
@ExtraFilter_453eb833 NVARCHAR(MAX),
@EntityID_453eb833 UNIQUEIDENTIFIER,
@RecordID_453eb833 NVARCHAR(2000),
@OrderBy_453eb833 NVARCHAR(MAX),
@TemplateContentID_453eb833 UNIQUEIDENTIFIER,
@ID_453eb833 UNIQUEIDENTIFIER
SET
  @TemplateID_453eb833 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_453eb833 = N'Tokens'
SET
  @Description_453eb833 = N'A list of valid CSS tokens for restyling'
SET
  @Type_453eb833 = N'Scalar'
SET
  @IsRequired_453eb833 = 1
SET
  @ID_453eb833 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_453eb833,
  @Name = @Name_453eb833,
  @Description = @Description_453eb833,
  @Type = @Type_453eb833,
  @DefaultValue = @DefaultValue_453eb833,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_453eb833,
  @LinkedParameterName = @LinkedParameterName_453eb833,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_453eb833,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_453eb833,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_453eb833,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_453eb833,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_453eb833,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_453eb833,
  @TemplateContentID_Clear = 1,
  @ID = @ID_453eb833;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_d9fd0439 UNIQUEIDENTIFIER,
@Name_d9fd0439 NVARCHAR(255),
@Description_d9fd0439 NVARCHAR(MAX),
@Type_d9fd0439 NVARCHAR(20),
@DefaultValue_d9fd0439 NVARCHAR(MAX),
@IsRequired_d9fd0439 BIT,
@LinkedParameterName_d9fd0439 NVARCHAR(255),
@LinkedParameterField_d9fd0439 NVARCHAR(500),
@ExtraFilter_d9fd0439 NVARCHAR(MAX),
@EntityID_d9fd0439 UNIQUEIDENTIFIER,
@RecordID_d9fd0439 NVARCHAR(2000),
@OrderBy_d9fd0439 NVARCHAR(MAX),
@TemplateContentID_d9fd0439 UNIQUEIDENTIFIER,
@ID_d9fd0439 UNIQUEIDENTIFIER
SET
  @TemplateID_d9fd0439 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_d9fd0439 = N'FormList'
SET
  @Description_d9fd0439 = N'A list of forms owned by the user'
SET
  @Type_d9fd0439 = N'Scalar'
SET
  @IsRequired_d9fd0439 = 1
SET
  @ID_d9fd0439 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E95' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_d9fd0439,
  @Name = @Name_d9fd0439,
  @Description = @Description_d9fd0439,
  @Type = @Type_d9fd0439,
  @DefaultValue = @DefaultValue_d9fd0439,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_d9fd0439,
  @LinkedParameterName = @LinkedParameterName_d9fd0439,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_d9fd0439,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_d9fd0439,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_d9fd0439,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_d9fd0439,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_d9fd0439,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_d9fd0439,
  @TemplateContentID_Clear = 1,
  @ID = @ID_d9fd0439;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_55a9402d NVARCHAR(255),
@Description_55a9402d NVARCHAR(MAX),
@TemplateID_55a9402d UNIQUEIDENTIFIER,
@CategoryID_55a9402d UNIQUEIDENTIFIER,
@TypeID_55a9402d UNIQUEIDENTIFIER,
@Status_55a9402d NVARCHAR(50),
@ResponseFormat_55a9402d NVARCHAR(20),
@ModelSpecificResponseFormat_55a9402d NVARCHAR(MAX),
@AIModelTypeID_55a9402d UNIQUEIDENTIFIER,
@MinPowerRank_55a9402d INT,
@SelectionStrategy_55a9402d NVARCHAR(20),
@PowerPreference_55a9402d NVARCHAR(20),
@ParallelizationMode_55a9402d NVARCHAR(20),
@ParallelCount_55a9402d INT,
@ParallelConfigParam_55a9402d NVARCHAR(100),
@OutputType_55a9402d NVARCHAR(50),
@OutputExample_55a9402d NVARCHAR(MAX),
@ValidationBehavior_55a9402d NVARCHAR(50),
@MaxRetries_55a9402d INT,
@RetryDelayMS_55a9402d INT,
@RetryStrategy_55a9402d NVARCHAR(20),
@ResultSelectorPromptID_55a9402d UNIQUEIDENTIFIER,
@EnableCaching_55a9402d BIT,
@CacheTTLSeconds_55a9402d INT,
@CacheMatchType_55a9402d NVARCHAR(20),
@CacheSimilarityThreshold_55a9402d FLOAT(53),
@CacheMustMatchModel_55a9402d BIT,
@CacheMustMatchVendor_55a9402d BIT,
@CacheMustMatchAgent_55a9402d BIT,
@CacheMustMatchConfig_55a9402d BIT,
@PromptRole_55a9402d NVARCHAR(20),
@PromptPosition_55a9402d NVARCHAR(20),
@Temperature_55a9402d DECIMAL(3, 2),
@TopP_55a9402d DECIMAL(3, 2),
@TopK_55a9402d INT,
@MinP_55a9402d DECIMAL(3, 2),
@FrequencyPenalty_55a9402d DECIMAL(3, 2),
@PresencePenalty_55a9402d DECIMAL(3, 2),
@Seed_55a9402d INT,
@StopSequences_55a9402d NVARCHAR(1000),
@IncludeLogProbs_55a9402d BIT,
@TopLogProbs_55a9402d INT,
@FailoverStrategy_55a9402d NVARCHAR(50),
@FailoverMaxAttempts_55a9402d INT,
@FailoverDelaySeconds_55a9402d INT,
@FailoverModelStrategy_55a9402d NVARCHAR(50),
@FailoverErrorScope_55a9402d NVARCHAR(50),
@EffortLevel_55a9402d INT,
@AssistantPrefill_55a9402d NVARCHAR(MAX),
@PrefillFallbackMode_55a9402d NVARCHAR(20),
@RequireSpecificModels_55a9402d BIT,
@ID_55a9402d UNIQUEIDENTIFIER
SET
  @Name_55a9402d = N'Forms: Chat Assistant'
SET
  @Description_55a9402d = N'The conversational surface of AI authoring. Replies to the author AND declares an action — none, create, restyle, or unsupported — which deterministic code then performs. The model never touches the database, the same split the rest of the authoring pipeline uses. Model selection is metadata-driven and this prompt is the most likely to want a different tier from the structural stages, since it is conversational rather than generative.'
SET
  @TemplateID_55a9402d = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @CategoryID_55a9402d = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_55a9402d = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_55a9402d = N'Active'
SET
  @ResponseFormat_55a9402d = N'JSON'
SET
  @AIModelTypeID_55a9402d = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_55a9402d = 0
SET
  @SelectionStrategy_55a9402d = N'Specific'
SET
  @PowerPreference_55a9402d = N'Highest'
SET
  @ParallelizationMode_55a9402d = N'None'
SET
  @OutputType_55a9402d = N'object'
SET
  @OutputExample_55a9402d = N'{"reply":"For a **#152A63** background, a white button with **#152A63** text gives the strongest contrast. I''ve applied it.","action":"restyle","brief?":"A five-question event RSVP with dietary needs and a guest count.","cssVariables?":{"--mjf-accent":"#ffffff","--mjf-on-accent":"#152a63"},"imagePrompt?":"a sunlit conference hall with rows of empty chairs","imageTarget?":"welcome","operations?":[{"op":"addQuestion","handle":"p1","type":"Rating","prompt":"How likely are you to recommend us?","after":"q2"}],"openFormId?":"f2"}'
SET
  @ValidationBehavior_55a9402d = N'None'
SET
  @MaxRetries_55a9402d = 1
SET
  @RetryDelayMS_55a9402d = 0
SET
  @RetryStrategy_55a9402d = N'Fixed'
SET
  @EnableCaching_55a9402d = 0
SET
  @CacheMatchType_55a9402d = N'Exact'
SET
  @CacheMustMatchModel_55a9402d = 1
SET
  @CacheMustMatchVendor_55a9402d = 1
SET
  @CacheMustMatchAgent_55a9402d = 0
SET
  @CacheMustMatchConfig_55a9402d = 0
SET
  @PromptRole_55a9402d = N'System'
SET
  @PromptPosition_55a9402d = N'First'
SET
  @IncludeLogProbs_55a9402d = 0
SET
  @FailoverStrategy_55a9402d = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_55a9402d = 3
SET
  @FailoverDelaySeconds_55a9402d = 5
SET
  @FailoverModelStrategy_55a9402d = N'PreferSameModel'
SET
  @FailoverErrorScope_55a9402d = N'All'
SET
  @PrefillFallbackMode_55a9402d = N'Ignore'
SET
  @RequireSpecificModels_55a9402d = 0
SET
  @ID_55a9402d = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829308' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_55a9402d,
  @Description = @Description_55a9402d,
  @TemplateID = @TemplateID_55a9402d,
  @CategoryID = @CategoryID_55a9402d,
  @TypeID = @TypeID_55a9402d,
  @Status = @Status_55a9402d,
  @ResponseFormat = @ResponseFormat_55a9402d,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_55a9402d,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_55a9402d,
  @MinPowerRank = @MinPowerRank_55a9402d,
  @SelectionStrategy = @SelectionStrategy_55a9402d,
  @PowerPreference = @PowerPreference_55a9402d,
  @ParallelizationMode = @ParallelizationMode_55a9402d,
  @ParallelCount = @ParallelCount_55a9402d,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_55a9402d,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_55a9402d,
  @OutputExample = @OutputExample_55a9402d,
  @ValidationBehavior = @ValidationBehavior_55a9402d,
  @MaxRetries = @MaxRetries_55a9402d,
  @RetryDelayMS = @RetryDelayMS_55a9402d,
  @RetryStrategy = @RetryStrategy_55a9402d,
  @ResultSelectorPromptID = @ResultSelectorPromptID_55a9402d,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_55a9402d,
  @CacheTTLSeconds = @CacheTTLSeconds_55a9402d,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_55a9402d,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_55a9402d,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_55a9402d,
  @CacheMustMatchVendor = @CacheMustMatchVendor_55a9402d,
  @CacheMustMatchAgent = @CacheMustMatchAgent_55a9402d,
  @CacheMustMatchConfig = @CacheMustMatchConfig_55a9402d,
  @PromptRole = @PromptRole_55a9402d,
  @PromptPosition = @PromptPosition_55a9402d,
  @Temperature = @Temperature_55a9402d,
  @Temperature_Clear = 1,
  @TopP = @TopP_55a9402d,
  @TopP_Clear = 1,
  @TopK = @TopK_55a9402d,
  @TopK_Clear = 1,
  @MinP = @MinP_55a9402d,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_55a9402d,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_55a9402d,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_55a9402d,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_55a9402d,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_55a9402d,
  @TopLogProbs = @TopLogProbs_55a9402d,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_55a9402d,
  @FailoverMaxAttempts = @FailoverMaxAttempts_55a9402d,
  @FailoverDelaySeconds = @FailoverDelaySeconds_55a9402d,
  @FailoverModelStrategy = @FailoverModelStrategy_55a9402d,
  @FailoverErrorScope = @FailoverErrorScope_55a9402d,
  @EffortLevel = @EffortLevel_55a9402d,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_55a9402d,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_55a9402d,
  @RequireSpecificModels = @RequireSpecificModels_55a9402d,
  @ID = @ID_55a9402d;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_f7b732fc UNIQUEIDENTIFIER,
@EntityID_f7b732fc UNIQUEIDENTIFIER,
@Name_f7b732fc NVARCHAR(100),
@Description_f7b732fc NVARCHAR(MAX),
@CategoryID_f7b732fc UNIQUEIDENTIFIER,
@IsShared_f7b732fc BIT,
@IsDefault_f7b732fc BIT,
@GridState_f7b732fc NVARCHAR(MAX),
@FilterState_f7b732fc NVARCHAR(MAX),
@CustomFilterState_f7b732fc BIT,
@SmartFilterEnabled_f7b732fc BIT,
@SmartFilterPrompt_f7b732fc NVARCHAR(MAX),
@SmartFilterWhereClause_f7b732fc NVARCHAR(MAX),
@SmartFilterExplanation_f7b732fc NVARCHAR(MAX),
@WhereClause_f7b732fc NVARCHAR(MAX),
@CustomWhereClause_f7b732fc BIT,
@SortState_f7b732fc NVARCHAR(MAX),
@Thumbnail_f7b732fc NVARCHAR(MAX),
@CardState_f7b732fc NVARCHAR(MAX),
@DisplayState_f7b732fc NVARCHAR(MAX),
@ViewTypeID_f7b732fc UNIQUEIDENTIFIER,
@ID_f7b732fc UNIQUEIDENTIFIER
SET
  @UserID_f7b732fc = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_f7b732fc = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_f7b732fc = N'All Forms'
SET
  @Description_f7b732fc = N''
SET
  @IsShared_f7b732fc = 1
SET
  @IsDefault_f7b732fc = 0
SET
  @GridState_f7b732fc = N'{}'
SET
  @FilterState_f7b732fc = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_f7b732fc = 0
SET
  @SmartFilterEnabled_f7b732fc = 0
SET
  @WhereClause_f7b732fc = N''
SET
  @CustomWhereClause_f7b732fc = 0
SET
  @ID_f7b732fc = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_f7b732fc,
  @EntityID = @EntityID_f7b732fc,
  @Name = @Name_f7b732fc,
  @Description = @Description_f7b732fc,
  @CategoryID = @CategoryID_f7b732fc,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_f7b732fc,
  @IsDefault = @IsDefault_f7b732fc,
  @GridState = @GridState_f7b732fc,
  @FilterState = @FilterState_f7b732fc,
  @CustomFilterState = @CustomFilterState_f7b732fc,
  @SmartFilterEnabled = @SmartFilterEnabled_f7b732fc,
  @SmartFilterPrompt = @SmartFilterPrompt_f7b732fc,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_f7b732fc,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_f7b732fc,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_f7b732fc,
  @CustomWhereClause = @CustomWhereClause_f7b732fc,
  @SortState = @SortState_f7b732fc,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_f7b732fc,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_f7b732fc,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_f7b732fc,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_f7b732fc,
  @ViewTypeID_Clear = 1,
  @ID = @ID_f7b732fc;

GO


-- End of SQL Logging Session
-- Session ID: a033de3d-2c56-47dd-bdd3-6d10af58e4b9
-- Completed: 2026-08-21T02:50:43.506Z
-- Duration: 6990ms
-- Total Statements: 15
