-- ---------------------------------------------------------------------------------------------
-- Metadata seed delta: the chat can put pictures on a form.
--
-- WHAT THIS CARRIES
--   * 'MJ_BizApps_Forms: Chat Assistant' template text — a fifth action, `image`, with the two
--     fields that go with it (`imagePrompt`, `imageTarget`), and the guidance for using them.
--   * 'Forms: Chat Assistant' OutputExample — the same two fields, both suffixed `?` because MJ
--     treats every unsuffixed example key as REQUIRED and would otherwise burn every retry.
--
-- WHY A PROMPT EDIT IS A MIGRATION. The template previously said, in as many words, that the
-- assistant could not make images. It obeyed: asked for a photo on a welcome screen it replied
-- "I can't generate images" — while the pipeline behind it had generated images since the first
-- authoring release. The capability was real and the prompt was the only thing withholding it, so
-- the fix is a metadata change and it ships the way every other metadata change here does.
--
-- NO NEW RECORDS AND NO NEW TABLES. Eight updates, all to rows earlier seeds already created:
-- the template's five params are rewritten unchanged either side of the content (MetadataSync
-- always does this), and the single `spUpdateUserView` on 'All Forms' is the same benign churn
-- every one of the four preceding seed deltas carries.
--
-- Generated the same way as its predecessors: pushed against MJ_Install_Rehearsal, which stands at
-- the shipped chain's head with 0 Form rows. Every `${flyway:defaultSchema}` became `${mjSchema}` —
-- all four procedures here are CORE. No Forms-schema SP calls and no Form Respondent permission
-- records, so #41's watershed is untouched.
-- ---------------------------------------------------------------------------------------------

-- SQL Logging Session
-- Session ID: d08fdf86-08e8-4048-b508-ef9670b59f87
-- Started: 2026-08-20T23:31:10.401Z
-- Description: MetadataSync push operation
-- Format: Migration-ready with Flyway schema placeholders
-- Generated by MemberJunction

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_86d180bf UNIQUEIDENTIFIER,
@Name_86d180bf NVARCHAR(255),
@Description_86d180bf NVARCHAR(MAX),
@Type_86d180bf NVARCHAR(20),
@DefaultValue_86d180bf NVARCHAR(MAX),
@IsRequired_86d180bf BIT,
@LinkedParameterName_86d180bf NVARCHAR(255),
@LinkedParameterField_86d180bf NVARCHAR(500),
@ExtraFilter_86d180bf NVARCHAR(MAX),
@EntityID_86d180bf UNIQUEIDENTIFIER,
@RecordID_86d180bf NVARCHAR(2000),
@OrderBy_86d180bf NVARCHAR(MAX),
@TemplateContentID_86d180bf UNIQUEIDENTIFIER,
@ID_86d180bf UNIQUEIDENTIFIER
SET
  @TemplateID_86d180bf = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_86d180bf = N'Message'
SET
  @Description_86d180bf = N'What the author just typed.'
SET
  @Type_86d180bf = N'Scalar'
SET
  @IsRequired_86d180bf = 1
SET
  @ID_86d180bf = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_86d180bf,
  @Name = @Name_86d180bf,
  @Description = @Description_86d180bf,
  @Type = @Type_86d180bf,
  @DefaultValue = @DefaultValue_86d180bf,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_86d180bf,
  @LinkedParameterName = @LinkedParameterName_86d180bf,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_86d180bf,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_86d180bf,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_86d180bf,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_86d180bf,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_86d180bf,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_86d180bf,
  @TemplateContentID_Clear = 1,
  @ID = @ID_86d180bf;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_31a72cd9 UNIQUEIDENTIFIER,
@Name_31a72cd9 NVARCHAR(255),
@Description_31a72cd9 NVARCHAR(MAX),
@Type_31a72cd9 NVARCHAR(20),
@DefaultValue_31a72cd9 NVARCHAR(MAX),
@IsRequired_31a72cd9 BIT,
@LinkedParameterName_31a72cd9 NVARCHAR(255),
@LinkedParameterField_31a72cd9 NVARCHAR(500),
@ExtraFilter_31a72cd9 NVARCHAR(MAX),
@EntityID_31a72cd9 UNIQUEIDENTIFIER,
@RecordID_31a72cd9 NVARCHAR(2000),
@OrderBy_31a72cd9 NVARCHAR(MAX),
@TemplateContentID_31a72cd9 UNIQUEIDENTIFIER,
@ID_31a72cd9 UNIQUEIDENTIFIER
SET
  @TemplateID_31a72cd9 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_31a72cd9 = N'History'
SET
  @Description_31a72cd9 = N'The prior turns as a plain transcript, oldest first and capped, so the prompt does not grow without bound.'
SET
  @Type_31a72cd9 = N'Scalar'
SET
  @IsRequired_31a72cd9 = 1
SET
  @ID_31a72cd9 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_31a72cd9,
  @Name = @Name_31a72cd9,
  @Description = @Description_31a72cd9,
  @Type = @Type_31a72cd9,
  @DefaultValue = @DefaultValue_31a72cd9,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_31a72cd9,
  @LinkedParameterName = @LinkedParameterName_31a72cd9,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_31a72cd9,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_31a72cd9,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_31a72cd9,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_31a72cd9,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_31a72cd9,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_31a72cd9,
  @TemplateContentID_Clear = 1,
  @ID = @ID_31a72cd9;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_f6949aef UNIQUEIDENTIFIER,
@Name_f6949aef NVARCHAR(255),
@Description_f6949aef NVARCHAR(MAX),
@Type_f6949aef NVARCHAR(20),
@DefaultValue_f6949aef NVARCHAR(MAX),
@IsRequired_f6949aef BIT,
@LinkedParameterName_f6949aef NVARCHAR(255),
@LinkedParameterField_f6949aef NVARCHAR(500),
@ExtraFilter_f6949aef NVARCHAR(MAX),
@EntityID_f6949aef UNIQUEIDENTIFIER,
@RecordID_f6949aef NVARCHAR(2000),
@OrderBy_f6949aef NVARCHAR(MAX),
@TemplateContentID_f6949aef UNIQUEIDENTIFIER,
@ID_f6949aef UNIQUEIDENTIFIER
SET
  @TemplateID_f6949aef = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_f6949aef = N'HasOpenForm'
SET
  @Description_f6949aef = N'''yes'' when a form is open, so the prompt can drop the restyle affordance when there is nothing to restyle.'
SET
  @Type_f6949aef = N'Scalar'
SET
  @IsRequired_f6949aef = 1
SET
  @ID_f6949aef = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_f6949aef,
  @Name = @Name_f6949aef,
  @Description = @Description_f6949aef,
  @Type = @Type_f6949aef,
  @DefaultValue = @DefaultValue_f6949aef,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_f6949aef,
  @LinkedParameterName = @LinkedParameterName_f6949aef,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_f6949aef,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_f6949aef,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_f6949aef,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_f6949aef,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_f6949aef,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_f6949aef,
  @TemplateContentID_Clear = 1,
  @ID = @ID_f6949aef;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_92888adb UNIQUEIDENTIFIER,
@Name_92888adb NVARCHAR(255),
@Description_92888adb NVARCHAR(MAX),
@Type_92888adb NVARCHAR(20),
@DefaultValue_92888adb NVARCHAR(MAX),
@IsRequired_92888adb BIT,
@LinkedParameterName_92888adb NVARCHAR(255),
@LinkedParameterField_92888adb NVARCHAR(500),
@ExtraFilter_92888adb NVARCHAR(MAX),
@EntityID_92888adb UNIQUEIDENTIFIER,
@RecordID_92888adb NVARCHAR(2000),
@OrderBy_92888adb NVARCHAR(MAX),
@TemplateContentID_92888adb UNIQUEIDENTIFIER,
@ID_92888adb UNIQUEIDENTIFIER
SET
  @TemplateID_92888adb = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_92888adb = N'FormContext'
SET
  @Description_92888adb = N'A compact description of the form on screen: its name, its questions and its current tokens.'
SET
  @Type_92888adb = N'Scalar'
SET
  @IsRequired_92888adb = 1
SET
  @ID_92888adb = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_92888adb,
  @Name = @Name_92888adb,
  @Description = @Description_92888adb,
  @Type = @Type_92888adb,
  @DefaultValue = @DefaultValue_92888adb,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_92888adb,
  @LinkedParameterName = @LinkedParameterName_92888adb,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_92888adb,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_92888adb,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_92888adb,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_92888adb,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_92888adb,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_92888adb,
  @TemplateContentID_Clear = 1,
  @ID = @ID_92888adb;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_6dd3daad UNIQUEIDENTIFIER,
@Name_6dd3daad NVARCHAR(255),
@Description_6dd3daad NVARCHAR(MAX),
@Type_6dd3daad NVARCHAR(20),
@DefaultValue_6dd3daad NVARCHAR(MAX),
@IsRequired_6dd3daad BIT,
@LinkedParameterName_6dd3daad NVARCHAR(255),
@LinkedParameterField_6dd3daad NVARCHAR(500),
@ExtraFilter_6dd3daad NVARCHAR(MAX),
@EntityID_6dd3daad UNIQUEIDENTIFIER,
@RecordID_6dd3daad NVARCHAR(2000),
@OrderBy_6dd3daad NVARCHAR(MAX),
@TemplateContentID_6dd3daad UNIQUEIDENTIFIER,
@ID_6dd3daad UNIQUEIDENTIFIER
SET
  @TemplateID_6dd3daad = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_6dd3daad = N'Tokens'
SET
  @Description_6dd3daad = N'The --mjf-* vocabulary, supplied by the code that owns it so the prompt and the validator cannot disagree.'
SET
  @Type_6dd3daad = N'Scalar'
SET
  @IsRequired_6dd3daad = 1
SET
  @ID_6dd3daad = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_6dd3daad,
  @Name = @Name_6dd3daad,
  @Description = @Description_6dd3daad,
  @Type = @Type_6dd3daad,
  @DefaultValue = @DefaultValue_6dd3daad,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_6dd3daad,
  @LinkedParameterName = @LinkedParameterName_6dd3daad,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_6dd3daad,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_6dd3daad,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_6dd3daad,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_6dd3daad,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_6dd3daad,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_6dd3daad,
  @TemplateContentID_Clear = 1,
  @ID = @ID_6dd3daad;

GO

-- Save MJ: Template Contents (core SP call only)
DECLARE @TemplateID_88259aa7 UNIQUEIDENTIFIER,
@TypeID_88259aa7 UNIQUEIDENTIFIER,
@TemplateText_88259aa7 NVARCHAR(MAX),
@Priority_88259aa7 INT,
@IsActive_88259aa7 BIT,
@ID_88259aa7 UNIQUEIDENTIFIER
SET
  @TemplateID_88259aa7 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @TypeID_88259aa7 = 'E7AFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @TemplateText_88259aa7 = N'You help someone build a form in MJ Forms. Reply to them, and say what you want done about it. Return a single JSON object — no prose outside it, no markdown fences.

{
  "reply": string,        // what the author reads. Markdown. Always required.
  "action": "none" | "create" | "restyle" | "image" | "unsupported",
  "brief"?: string,       // action=create only
  "cssVariables"?: {},    // action=restyle only
  "imagePrompt"?: string, // action=image only
  "imageTarget"?: "welcome" | "ending"  // action=image only; defaults to welcome
}

CHOOSING THE ACTION
- `none` — they asked a question, wanted advice, or were chatting. Nothing changes. This is the most common one; use it freely.
- `create` — they asked for a NEW form. Put everything you know about what they want into "brief", written as a full description rather than an echo of their words: it is handed to a form designer that will not see this conversation.
- `restyle` — they asked to change how the form ON SCREEN looks, and there is one. Put the tokens in "cssVariables".
- `image` — they asked for a picture on the form''s start or finish screen. Describe the picture in "imagePrompt".
- `unsupported` — they asked for a real change you cannot make yet. Say so plainly in "reply" and name what you can do instead. Do NOT pretend it worked, and do NOT use `none` for this — a change that silently does not happen is the worst answer available.

WHAT YOU CANNOT DO YET
You cannot add, remove, reword or reorder questions on an existing form, and you cannot change pages. Asked for any of those, use `unsupported` and tell them they can edit it directly in the builder.

You CAN create a whole new form, restyle one, and put a picture on its start or finish screen. Never say you cannot make images — you can.

PICTURES
- "imagePrompt" describes the picture itself — "a sunlit conference hall with rows of empty chairs", "a bowl of ramen on a worn wooden table". Describe it; do not write an instruction like "generate an image of…".
- "imageTarget" is "welcome" unless they clearly meant the finish screen. Welcome is the default: it is the screen someone sees before deciding whether to start.
- One picture per turn. It takes a few seconds, so say what you are making in one line and do not promise more.
- Keep the description close to what they asked for. A picture that fights the form''s colours is worse than a plain one.

RESTYLING
Only these tokens exist. Anything else is discarded, so inventing one loses that part of the design:
{{ Tokens }}

- Colours as `#rrggbb`. Fonts as a full CSS stack ending in a generic family.
- `--mjf-page-bg` is the page, `--mjf-accent` is the buttons, `--mjf-on-accent` is the text ON the buttons, `--mjf-page-ink` is the body text, `--mjf-choice-selected-bg` is a selected answer.
- Set text and its background so the pair is genuinely readable — dark on light, light on dark. Pairs are checked afterwards and a failing one is corrected bluntly, so a pair you get right yourself looks better than one that has to be fixed.
- Send only the tokens you are changing. Everything you omit keeps its current value.
- Sizing, alignment and corner radius are NOT yours to set. If they ask, use `unsupported` and point them at the Design tab.

WRITING THE REPLY
- Talk like a colleague who knows forms. Short. No preamble, no "Certainly!", no restating the question.
- Markdown is rendered: use **bold** for colour values and bullet lists for options. Do not use headings.
- When you act, say what you did in one line. When you cannot, say why in one line.
- Answering a design question well IS the job — you do not have to change something every turn.

{% if HasOpenForm == ''yes'' %}
THE FORM ON SCREEN
{{ FormContext }}
{% else %}
There is no form open — they are on the forms list. You can create one; there is nothing to restyle.
{% endif %}

THE CONVERSATION SO FAR
{{ History }}

THE AUTHOR JUST SAID
"""{{ Message }}"""

Return only the JSON object.
'
SET
  @Priority_88259aa7 = 100
SET
  @IsActive_88259aa7 = 1
SET
  @ID_88259aa7 = '8F1B6C2A-3D4E-4F50-9A61-7B2C3D4E5F64' EXEC [${mjSchema}].spUpdateTemplateContent @TemplateID = @TemplateID_88259aa7,
  @TypeID = @TypeID_88259aa7,
  @TemplateText = @TemplateText_88259aa7,
  @Priority = @Priority_88259aa7,
  @IsActive = @IsActive_88259aa7,
  @ID = @ID_88259aa7;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_327ec9db UNIQUEIDENTIFIER,
@Name_327ec9db NVARCHAR(255),
@Description_327ec9db NVARCHAR(MAX),
@Type_327ec9db NVARCHAR(20),
@DefaultValue_327ec9db NVARCHAR(MAX),
@IsRequired_327ec9db BIT,
@LinkedParameterName_327ec9db NVARCHAR(255),
@LinkedParameterField_327ec9db NVARCHAR(500),
@ExtraFilter_327ec9db NVARCHAR(MAX),
@EntityID_327ec9db UNIQUEIDENTIFIER,
@RecordID_327ec9db NVARCHAR(2000),
@OrderBy_327ec9db NVARCHAR(MAX),
@TemplateContentID_327ec9db UNIQUEIDENTIFIER,
@ID_327ec9db UNIQUEIDENTIFIER
SET
  @TemplateID_327ec9db = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_327ec9db = N'Message'
SET
  @Description_327ec9db = N'The latest message sent by the user'
SET
  @Type_327ec9db = N'Scalar'
SET
  @IsRequired_327ec9db = 1
SET
  @ID_327ec9db = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E90' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_327ec9db,
  @Name = @Name_327ec9db,
  @Description = @Description_327ec9db,
  @Type = @Type_327ec9db,
  @DefaultValue = @DefaultValue_327ec9db,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_327ec9db,
  @LinkedParameterName = @LinkedParameterName_327ec9db,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_327ec9db,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_327ec9db,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_327ec9db,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_327ec9db,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_327ec9db,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_327ec9db,
  @TemplateContentID_Clear = 1,
  @ID = @ID_327ec9db;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_d16fec2b UNIQUEIDENTIFIER,
@Name_d16fec2b NVARCHAR(255),
@Description_d16fec2b NVARCHAR(MAX),
@Type_d16fec2b NVARCHAR(20),
@DefaultValue_d16fec2b NVARCHAR(MAX),
@IsRequired_d16fec2b BIT,
@LinkedParameterName_d16fec2b NVARCHAR(255),
@LinkedParameterField_d16fec2b NVARCHAR(500),
@ExtraFilter_d16fec2b NVARCHAR(MAX),
@EntityID_d16fec2b UNIQUEIDENTIFIER,
@RecordID_d16fec2b NVARCHAR(2000),
@OrderBy_d16fec2b NVARCHAR(MAX),
@TemplateContentID_d16fec2b UNIQUEIDENTIFIER,
@ID_d16fec2b UNIQUEIDENTIFIER
SET
  @TemplateID_d16fec2b = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_d16fec2b = N'History'
SET
  @Description_d16fec2b = N'The chat history between the user and the assistant'
SET
  @Type_d16fec2b = N'Scalar'
SET
  @IsRequired_d16fec2b = 1
SET
  @ID_d16fec2b = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E91' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_d16fec2b,
  @Name = @Name_d16fec2b,
  @Description = @Description_d16fec2b,
  @Type = @Type_d16fec2b,
  @DefaultValue = @DefaultValue_d16fec2b,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_d16fec2b,
  @LinkedParameterName = @LinkedParameterName_d16fec2b,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_d16fec2b,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_d16fec2b,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_d16fec2b,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_d16fec2b,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_d16fec2b,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_d16fec2b,
  @TemplateContentID_Clear = 1,
  @ID = @ID_d16fec2b;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_155928b7 UNIQUEIDENTIFIER,
@Name_155928b7 NVARCHAR(255),
@Description_155928b7 NVARCHAR(MAX),
@Type_155928b7 NVARCHAR(20),
@DefaultValue_155928b7 NVARCHAR(MAX),
@IsRequired_155928b7 BIT,
@LinkedParameterName_155928b7 NVARCHAR(255),
@LinkedParameterField_155928b7 NVARCHAR(500),
@ExtraFilter_155928b7 NVARCHAR(MAX),
@EntityID_155928b7 UNIQUEIDENTIFIER,
@RecordID_155928b7 NVARCHAR(2000),
@OrderBy_155928b7 NVARCHAR(MAX),
@TemplateContentID_155928b7 UNIQUEIDENTIFIER,
@ID_155928b7 UNIQUEIDENTIFIER
SET
  @TemplateID_155928b7 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_155928b7 = N'FormContext'
SET
  @Description_155928b7 = N'The context object containing information about the currently open form'
SET
  @Type_155928b7 = N'Scalar'
SET
  @IsRequired_155928b7 = 0
SET
  @ID_155928b7 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E92' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_155928b7,
  @Name = @Name_155928b7,
  @Description = @Description_155928b7,
  @Type = @Type_155928b7,
  @DefaultValue = @DefaultValue_155928b7,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_155928b7,
  @LinkedParameterName = @LinkedParameterName_155928b7,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_155928b7,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_155928b7,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_155928b7,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_155928b7,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_155928b7,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_155928b7,
  @TemplateContentID_Clear = 1,
  @ID = @ID_155928b7;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_bd3153b4 UNIQUEIDENTIFIER,
@Name_bd3153b4 NVARCHAR(255),
@Description_bd3153b4 NVARCHAR(MAX),
@Type_bd3153b4 NVARCHAR(20),
@DefaultValue_bd3153b4 NVARCHAR(MAX),
@IsRequired_bd3153b4 BIT,
@LinkedParameterName_bd3153b4 NVARCHAR(255),
@LinkedParameterField_bd3153b4 NVARCHAR(500),
@ExtraFilter_bd3153b4 NVARCHAR(MAX),
@EntityID_bd3153b4 UNIQUEIDENTIFIER,
@RecordID_bd3153b4 NVARCHAR(2000),
@OrderBy_bd3153b4 NVARCHAR(MAX),
@TemplateContentID_bd3153b4 UNIQUEIDENTIFIER,
@ID_bd3153b4 UNIQUEIDENTIFIER
SET
  @TemplateID_bd3153b4 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_bd3153b4 = N'HasOpenForm'
SET
  @Description_bd3153b4 = N'Flag indicating if a form is currently open in the editor'
SET
  @Type_bd3153b4 = N'Scalar'
SET
  @IsRequired_bd3153b4 = 0
SET
  @ID_bd3153b4 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E93' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_bd3153b4,
  @Name = @Name_bd3153b4,
  @Description = @Description_bd3153b4,
  @Type = @Type_bd3153b4,
  @DefaultValue = @DefaultValue_bd3153b4,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_bd3153b4,
  @LinkedParameterName = @LinkedParameterName_bd3153b4,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_bd3153b4,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_bd3153b4,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_bd3153b4,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_bd3153b4,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_bd3153b4,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_bd3153b4,
  @TemplateContentID_Clear = 1,
  @ID = @ID_bd3153b4;

GO

-- Save MJ: Template Params (core SP call only)
DECLARE @TemplateID_9e254f40 UNIQUEIDENTIFIER,
@Name_9e254f40 NVARCHAR(255),
@Description_9e254f40 NVARCHAR(MAX),
@Type_9e254f40 NVARCHAR(20),
@DefaultValue_9e254f40 NVARCHAR(MAX),
@IsRequired_9e254f40 BIT,
@LinkedParameterName_9e254f40 NVARCHAR(255),
@LinkedParameterField_9e254f40 NVARCHAR(500),
@ExtraFilter_9e254f40 NVARCHAR(MAX),
@EntityID_9e254f40 UNIQUEIDENTIFIER,
@RecordID_9e254f40 NVARCHAR(2000),
@OrderBy_9e254f40 NVARCHAR(MAX),
@TemplateContentID_9e254f40 UNIQUEIDENTIFIER,
@ID_9e254f40 UNIQUEIDENTIFIER
SET
  @TemplateID_9e254f40 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @Name_9e254f40 = N'Tokens'
SET
  @Description_9e254f40 = N'Template scalar parameter ''Tokens'''
SET
  @Type_9e254f40 = N'Scalar'
SET
  @IsRequired_9e254f40 = 1
SET
  @ID_9e254f40 = '1C2D3E4F-5A6B-4C7D-8E9F-0A1B2C3D4E94' EXEC [${mjSchema}].spUpdateTemplateParam @TemplateID = @TemplateID_9e254f40,
  @Name = @Name_9e254f40,
  @Description = @Description_9e254f40,
  @Type = @Type_9e254f40,
  @DefaultValue = @DefaultValue_9e254f40,
  @DefaultValue_Clear = 1,
  @IsRequired = @IsRequired_9e254f40,
  @LinkedParameterName = @LinkedParameterName_9e254f40,
  @LinkedParameterName_Clear = 1,
  @LinkedParameterField = @LinkedParameterField_9e254f40,
  @LinkedParameterField_Clear = 1,
  @ExtraFilter = @ExtraFilter_9e254f40,
  @ExtraFilter_Clear = 1,
  @EntityID = @EntityID_9e254f40,
  @EntityID_Clear = 1,
  @RecordID = @RecordID_9e254f40,
  @RecordID_Clear = 1,
  @OrderBy = @OrderBy_9e254f40,
  @OrderBy_Clear = 1,
  @TemplateContentID = @TemplateContentID_9e254f40,
  @TemplateContentID_Clear = 1,
  @ID = @ID_9e254f40;

GO

-- Save MJ: AI Prompts (core SP call only)
DECLARE @Name_27167a44 NVARCHAR(255),
@Description_27167a44 NVARCHAR(MAX),
@TemplateID_27167a44 UNIQUEIDENTIFIER,
@CategoryID_27167a44 UNIQUEIDENTIFIER,
@TypeID_27167a44 UNIQUEIDENTIFIER,
@Status_27167a44 NVARCHAR(50),
@ResponseFormat_27167a44 NVARCHAR(20),
@ModelSpecificResponseFormat_27167a44 NVARCHAR(MAX),
@AIModelTypeID_27167a44 UNIQUEIDENTIFIER,
@MinPowerRank_27167a44 INT,
@SelectionStrategy_27167a44 NVARCHAR(20),
@PowerPreference_27167a44 NVARCHAR(20),
@ParallelizationMode_27167a44 NVARCHAR(20),
@ParallelCount_27167a44 INT,
@ParallelConfigParam_27167a44 NVARCHAR(100),
@OutputType_27167a44 NVARCHAR(50),
@OutputExample_27167a44 NVARCHAR(MAX),
@ValidationBehavior_27167a44 NVARCHAR(50),
@MaxRetries_27167a44 INT,
@RetryDelayMS_27167a44 INT,
@RetryStrategy_27167a44 NVARCHAR(20),
@ResultSelectorPromptID_27167a44 UNIQUEIDENTIFIER,
@EnableCaching_27167a44 BIT,
@CacheTTLSeconds_27167a44 INT,
@CacheMatchType_27167a44 NVARCHAR(20),
@CacheSimilarityThreshold_27167a44 FLOAT(53),
@CacheMustMatchModel_27167a44 BIT,
@CacheMustMatchVendor_27167a44 BIT,
@CacheMustMatchAgent_27167a44 BIT,
@CacheMustMatchConfig_27167a44 BIT,
@PromptRole_27167a44 NVARCHAR(20),
@PromptPosition_27167a44 NVARCHAR(20),
@Temperature_27167a44 DECIMAL(3, 2),
@TopP_27167a44 DECIMAL(3, 2),
@TopK_27167a44 INT,
@MinP_27167a44 DECIMAL(3, 2),
@FrequencyPenalty_27167a44 DECIMAL(3, 2),
@PresencePenalty_27167a44 DECIMAL(3, 2),
@Seed_27167a44 INT,
@StopSequences_27167a44 NVARCHAR(1000),
@IncludeLogProbs_27167a44 BIT,
@TopLogProbs_27167a44 INT,
@FailoverStrategy_27167a44 NVARCHAR(50),
@FailoverMaxAttempts_27167a44 INT,
@FailoverDelaySeconds_27167a44 INT,
@FailoverModelStrategy_27167a44 NVARCHAR(50),
@FailoverErrorScope_27167a44 NVARCHAR(50),
@EffortLevel_27167a44 INT,
@AssistantPrefill_27167a44 NVARCHAR(MAX),
@PrefillFallbackMode_27167a44 NVARCHAR(20),
@RequireSpecificModels_27167a44 BIT,
@ID_27167a44 UNIQUEIDENTIFIER
SET
  @Name_27167a44 = N'Forms: Chat Assistant'
SET
  @Description_27167a44 = N'The conversational surface of AI authoring. Replies to the author AND declares an action — none, create, restyle, or unsupported — which deterministic code then performs. The model never touches the database, the same split the rest of the authoring pipeline uses. Model selection is metadata-driven and this prompt is the most likely to want a different tier from the structural stages, since it is conversational rather than generative.'
SET
  @TemplateID_27167a44 = '7E0A1B2C-3D4E-4F50-8A61-9B2C3D4E5F65'
SET
  @CategoryID_27167a44 = '4F5A6B7C-8D9E-4F0A-1B2C-3D4E5F607182'
SET
  @TypeID_27167a44 = 'A6DA423E-F36B-1410-8DAC-00021F8B792E'
SET
  @Status_27167a44 = N'Active'
SET
  @ResponseFormat_27167a44 = N'JSON'
SET
  @AIModelTypeID_27167a44 = 'E8A5CCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @MinPowerRank_27167a44 = 0
SET
  @SelectionStrategy_27167a44 = N'Specific'
SET
  @PowerPreference_27167a44 = N'Highest'
SET
  @ParallelizationMode_27167a44 = N'None'
SET
  @OutputType_27167a44 = N'object'
SET
  @OutputExample_27167a44 = N'{"reply":"For a **#152A63** background, a white button with **#152A63** text gives the strongest contrast. I''ve applied it.","action":"restyle","brief?":"A five-question event RSVP with dietary needs and a guest count.","cssVariables?":{"--mjf-accent":"#ffffff","--mjf-on-accent":"#152a63"},"imagePrompt?":"a sunlit conference hall with rows of empty chairs","imageTarget?":"welcome"}'
SET
  @ValidationBehavior_27167a44 = N'None'
SET
  @MaxRetries_27167a44 = 1
SET
  @RetryDelayMS_27167a44 = 0
SET
  @RetryStrategy_27167a44 = N'Fixed'
SET
  @EnableCaching_27167a44 = 0
SET
  @CacheMatchType_27167a44 = N'Exact'
SET
  @CacheMustMatchModel_27167a44 = 1
SET
  @CacheMustMatchVendor_27167a44 = 1
SET
  @CacheMustMatchAgent_27167a44 = 0
SET
  @CacheMustMatchConfig_27167a44 = 0
SET
  @PromptRole_27167a44 = N'System'
SET
  @PromptPosition_27167a44 = N'First'
SET
  @IncludeLogProbs_27167a44 = 0
SET
  @FailoverStrategy_27167a44 = N'SameModelDifferentVendor'
SET
  @FailoverMaxAttempts_27167a44 = 3
SET
  @FailoverDelaySeconds_27167a44 = 5
SET
  @FailoverModelStrategy_27167a44 = N'PreferSameModel'
SET
  @FailoverErrorScope_27167a44 = N'All'
SET
  @PrefillFallbackMode_27167a44 = N'Ignore'
SET
  @RequireSpecificModels_27167a44 = 0
SET
  @ID_27167a44 = '6B7C8D9E-0F1A-4B2C-3D4E-5F6071829308' EXEC [${mjSchema}].spUpdateAIPrompt @Name = @Name_27167a44,
  @Description = @Description_27167a44,
  @TemplateID = @TemplateID_27167a44,
  @CategoryID = @CategoryID_27167a44,
  @TypeID = @TypeID_27167a44,
  @Status = @Status_27167a44,
  @ResponseFormat = @ResponseFormat_27167a44,
  @ModelSpecificResponseFormat = @ModelSpecificResponseFormat_27167a44,
  @ModelSpecificResponseFormat_Clear = 1,
  @AIModelTypeID = @AIModelTypeID_27167a44,
  @MinPowerRank = @MinPowerRank_27167a44,
  @SelectionStrategy = @SelectionStrategy_27167a44,
  @PowerPreference = @PowerPreference_27167a44,
  @ParallelizationMode = @ParallelizationMode_27167a44,
  @ParallelCount = @ParallelCount_27167a44,
  @ParallelCount_Clear = 1,
  @ParallelConfigParam = @ParallelConfigParam_27167a44,
  @ParallelConfigParam_Clear = 1,
  @OutputType = @OutputType_27167a44,
  @OutputExample = @OutputExample_27167a44,
  @ValidationBehavior = @ValidationBehavior_27167a44,
  @MaxRetries = @MaxRetries_27167a44,
  @RetryDelayMS = @RetryDelayMS_27167a44,
  @RetryStrategy = @RetryStrategy_27167a44,
  @ResultSelectorPromptID = @ResultSelectorPromptID_27167a44,
  @ResultSelectorPromptID_Clear = 1,
  @EnableCaching = @EnableCaching_27167a44,
  @CacheTTLSeconds = @CacheTTLSeconds_27167a44,
  @CacheTTLSeconds_Clear = 1,
  @CacheMatchType = @CacheMatchType_27167a44,
  @CacheSimilarityThreshold = @CacheSimilarityThreshold_27167a44,
  @CacheSimilarityThreshold_Clear = 1,
  @CacheMustMatchModel = @CacheMustMatchModel_27167a44,
  @CacheMustMatchVendor = @CacheMustMatchVendor_27167a44,
  @CacheMustMatchAgent = @CacheMustMatchAgent_27167a44,
  @CacheMustMatchConfig = @CacheMustMatchConfig_27167a44,
  @PromptRole = @PromptRole_27167a44,
  @PromptPosition = @PromptPosition_27167a44,
  @Temperature = @Temperature_27167a44,
  @Temperature_Clear = 1,
  @TopP = @TopP_27167a44,
  @TopP_Clear = 1,
  @TopK = @TopK_27167a44,
  @TopK_Clear = 1,
  @MinP = @MinP_27167a44,
  @MinP_Clear = 1,
  @FrequencyPenalty = @FrequencyPenalty_27167a44,
  @FrequencyPenalty_Clear = 1,
  @PresencePenalty = @PresencePenalty_27167a44,
  @PresencePenalty_Clear = 1,
  @Seed = @Seed_27167a44,
  @Seed_Clear = 1,
  @StopSequences = @StopSequences_27167a44,
  @StopSequences_Clear = 1,
  @IncludeLogProbs = @IncludeLogProbs_27167a44,
  @TopLogProbs = @TopLogProbs_27167a44,
  @TopLogProbs_Clear = 1,
  @FailoverStrategy = @FailoverStrategy_27167a44,
  @FailoverMaxAttempts = @FailoverMaxAttempts_27167a44,
  @FailoverDelaySeconds = @FailoverDelaySeconds_27167a44,
  @FailoverModelStrategy = @FailoverModelStrategy_27167a44,
  @FailoverErrorScope = @FailoverErrorScope_27167a44,
  @EffortLevel = @EffortLevel_27167a44,
  @EffortLevel_Clear = 1,
  @AssistantPrefill = @AssistantPrefill_27167a44,
  @AssistantPrefill_Clear = 1,
  @PrefillFallbackMode = @PrefillFallbackMode_27167a44,
  @RequireSpecificModels = @RequireSpecificModels_27167a44,
  @ID = @ID_27167a44;

GO

-- Save MJ: User Views (core SP call only)
DECLARE @UserID_ebd0a56c UNIQUEIDENTIFIER,
@EntityID_ebd0a56c UNIQUEIDENTIFIER,
@Name_ebd0a56c NVARCHAR(100),
@Description_ebd0a56c NVARCHAR(MAX),
@CategoryID_ebd0a56c UNIQUEIDENTIFIER,
@IsShared_ebd0a56c BIT,
@IsDefault_ebd0a56c BIT,
@GridState_ebd0a56c NVARCHAR(MAX),
@FilterState_ebd0a56c NVARCHAR(MAX),
@CustomFilterState_ebd0a56c BIT,
@SmartFilterEnabled_ebd0a56c BIT,
@SmartFilterPrompt_ebd0a56c NVARCHAR(MAX),
@SmartFilterWhereClause_ebd0a56c NVARCHAR(MAX),
@SmartFilterExplanation_ebd0a56c NVARCHAR(MAX),
@WhereClause_ebd0a56c NVARCHAR(MAX),
@CustomWhereClause_ebd0a56c BIT,
@SortState_ebd0a56c NVARCHAR(MAX),
@Thumbnail_ebd0a56c NVARCHAR(MAX),
@CardState_ebd0a56c NVARCHAR(MAX),
@DisplayState_ebd0a56c NVARCHAR(MAX),
@ViewTypeID_ebd0a56c UNIQUEIDENTIFIER,
@ID_ebd0a56c UNIQUEIDENTIFIER
SET
  @UserID_ebd0a56c = 'ECAFCCEC-6A37-EF11-86D4-000D3A4E707E'
SET
  @EntityID_ebd0a56c = 'C6DB9AD8-11EA-451B-B0E1-71D7BFD894B8'
SET
  @Name_ebd0a56c = N'All Forms'
SET
  @Description_ebd0a56c = N''
SET
  @IsShared_ebd0a56c = 1
SET
  @IsDefault_ebd0a56c = 0
SET
  @GridState_ebd0a56c = N'{}'
SET
  @FilterState_ebd0a56c = N'{"logic":"and","filters":[]}'
SET
  @CustomFilterState_ebd0a56c = 0
SET
  @SmartFilterEnabled_ebd0a56c = 0
SET
  @WhereClause_ebd0a56c = N''
SET
  @CustomWhereClause_ebd0a56c = 0
SET
  @ID_ebd0a56c = '7F0D0001-A1B2-4C3D-8E4F-000000000001' EXEC [${mjSchema}].spUpdateUserView @UserID = @UserID_ebd0a56c,
  @EntityID = @EntityID_ebd0a56c,
  @Name = @Name_ebd0a56c,
  @Description = @Description_ebd0a56c,
  @CategoryID = @CategoryID_ebd0a56c,
  @CategoryID_Clear = 1,
  @IsShared = @IsShared_ebd0a56c,
  @IsDefault = @IsDefault_ebd0a56c,
  @GridState = @GridState_ebd0a56c,
  @FilterState = @FilterState_ebd0a56c,
  @CustomFilterState = @CustomFilterState_ebd0a56c,
  @SmartFilterEnabled = @SmartFilterEnabled_ebd0a56c,
  @SmartFilterPrompt = @SmartFilterPrompt_ebd0a56c,
  @SmartFilterPrompt_Clear = 1,
  @SmartFilterWhereClause = @SmartFilterWhereClause_ebd0a56c,
  @SmartFilterWhereClause_Clear = 1,
  @SmartFilterExplanation = @SmartFilterExplanation_ebd0a56c,
  @SmartFilterExplanation_Clear = 1,
  @WhereClause = @WhereClause_ebd0a56c,
  @CustomWhereClause = @CustomWhereClause_ebd0a56c,
  @SortState = @SortState_ebd0a56c,
  @SortState_Clear = 1,
  @Thumbnail = @Thumbnail_ebd0a56c,
  @Thumbnail_Clear = 1,
  @CardState = @CardState_ebd0a56c,
  @CardState_Clear = 1,
  @DisplayState = @DisplayState_ebd0a56c,
  @DisplayState_Clear = 1,
  @ViewTypeID = @ViewTypeID_ebd0a56c,
  @ViewTypeID_Clear = 1,
  @ID = @ID_ebd0a56c;

GO


-- End of SQL Logging Session
-- Session ID: d08fdf86-08e8-4048-b508-ef9670b59f87
-- Completed: 2026-08-20T23:31:17.027Z
-- Duration: 6626ms
-- Total Statements: 13
